const BROWSE=[
// A1 - Beginner
['able','/ˈeɪbl/','có thể','A1','adj'],['about','/əˈbaʊt/','về, khoảng','A1','prep'],['after','/ˈæftər/','sau','A1','prep'],['again','/əˈɡen/','lại','A1','adv'],['all','/ɔːl/','tất cả','A1','det'],['also','/ˈɔːlsoʊ/','cũng','A1','adv'],['always','/ˈɔːlweɪz/','luôn luôn','A1','adv'],['and','/ænd/','và','A1','conj'],['animal','/ˈænɪməl/','động vật','A1','n'],['answer','/ˈænsər/','trả lời','A1','v'],
['ask','/æsk/','hỏi','A1','v'],['bad','/bæd/','xấu, tệ','A1','adj'],['beautiful','/ˈbjuːtɪfl/','đẹp','A1','adj'],['because','/bɪˈkɒz/','bởi vì','A1','conj'],['before','/bɪˈfɔːr/','trước','A1','prep'],['begin','/bɪˈɡɪn/','bắt đầu','A1','v'],['between','/bɪˈtwiːn/','giữa','A1','prep'],['big','/bɪɡ/','to, lớn','A1','adj'],['book','/bʊk/','sách','A1','n'],['boy','/bɔɪ/','con trai','A1','n'],
['bring','/brɪŋ/','mang đến','A1','v'],['brother','/ˈbrʌðər/','anh/em trai','A1','n'],['buy','/baɪ/','mua','A1','v'],['call','/kɔːl/','gọi','A1','v'],['car','/kɑːr/','xe hơi','A1','n'],['cat','/kæt/','con mèo','A1','n'],['child','/tʃaɪld/','trẻ em','A1','n'],['city','/ˈsɪti/','thành phố','A1','n'],['close','/kloʊz/','đóng','A1','v'],['cold','/koʊld/','lạnh','A1','adj'],
['come','/kʌm/','đến','A1','v'],['cook','/kʊk/','nấu ăn','A1','v'],['country','/ˈkʌntri/','đất nước','A1','n'],['day','/deɪ/','ngày','A1','n'],['different','/ˈdɪfrənt/','khác nhau','A1','adj'],['difficult','/ˈdɪfɪkəlt/','khó','A1','adj'],['do','/duː/','làm','A1','v'],['dog','/dɔːɡ/','con chó','A1','n'],['door','/dɔːr/','cửa','A1','n'],['drink','/drɪŋk/','uống','A1','v'],
['drive','/draɪv/','lái xe','A1','v'],['eat','/iːt/','ăn','A1','v'],['end','/end/','kết thúc','A1','n'],['every','/ˈevri/','mỗi','A1','det'],['eye','/aɪ/','mắt','A1','n'],['family','/ˈfæməli/','gia đình','A1','n'],['far','/fɑːr/','xa','A1','adj'],['fast','/fæst/','nhanh','A1','adj'],['father','/ˈfɑːðər/','cha','A1','n'],['find','/faɪnd/','tìm','A1','v'],
['first','/fɜːrst/','đầu tiên','A1','adj'],['food','/fuːd/','thức ăn','A1','n'],['friend','/frend/','bạn bè','A1','n'],['get','/ɡet/','lấy, được','A1','v'],['girl','/ɡɜːrl/','con gái','A1','n'],['give','/ɡɪv/','cho','A1','v'],['go','/ɡoʊ/','đi','A1','v'],['good','/ɡʊd/','tốt','A1','adj'],['great','/ɡreɪt/','tuyệt vời','A1','adj'],['green','/ɡriːn/','xanh lá','A1','adj'],
['hand','/hænd/','tay','A1','n'],['happy','/ˈhæpi/','vui','A1','adj'],['have','/hæv/','có','A1','v'],['he','/hiː/','anh ấy','A1','pron'],['hear','/hɪr/','nghe','A1','v'],['help','/help/','giúp đỡ','A1','v'],['here','/hɪr/','ở đây','A1','adv'],['home','/hoʊm/','nhà','A1','n'],['hot','/hɒt/','nóng','A1','adj'],['house','/haʊs/','ngôi nhà','A1','n'],
['important','/ɪmˈpɔːrtənt/','quan trọng','A1','adj'],['in','/ɪn/','trong','A1','prep'],['interesting','/ˈɪntrəstɪŋ/','thú vị','A1','adj'],['job','/dʒɒb/','công việc','A1','n'],['know','/noʊ/','biết','A1','v'],['large','/lɑːrdʒ/','lớn','A1','adj'],['last','/læst/','cuối cùng','A1','adj'],['late','/leɪt/','muộn','A1','adj'],['learn','/lɜːrn/','học','A1','v'],['leave','/liːv/','rời đi','A1','v'],
['life','/laɪf/','cuộc sống','A1','n'],['like','/laɪk/','thích','A1','v'],['listen','/ˈlɪsn/','lắng nghe','A1','v'],['little','/ˈlɪtl/','nhỏ, ít','A1','adj'],['live','/lɪv/','sống','A1','v'],['long','/lɔːŋ/','dài','A1','adj'],['look','/lʊk/','nhìn','A1','v'],['love','/lʌv/','yêu','A1','v'],['make','/meɪk/','làm, tạo','A1','v'],['man','/mæn/','đàn ông','A1','n'],
// A2 - Elementary
['accept','/əkˈsept/','chấp nhận','A2','v'],['accident','/ˈæksɪdənt/','tai nạn','A2','n'],['achieve','/əˈtʃiːv/','đạt được','A2','v'],['across','/əˈkrɒs/','ngang qua','A2','prep'],['advice','/ədˈvaɪs/','lời khuyên','A2','n'],['agree','/əˈɡriː/','đồng ý','A2','v'],['allow','/əˈlaʊ/','cho phép','A2','v'],['although','/ɔːlˈðoʊ/','mặc dù','A2','conj'],['amount','/əˈmaʊnt/','số lượng','A2','n'],['appear','/əˈpɪr/','xuất hiện','A2','v'],
['apply','/əˈplaɪ/','nộp đơn','A2','v'],['arrive','/əˈraɪv/','đến nơi','A2','v'],['attention','/əˈtenʃn/','sự chú ý','A2','n'],['available','/əˈveɪləbl/','có sẵn','A2','adj'],['avoid','/əˈvɔɪd/','tránh','A2','v'],['basic','/ˈbeɪsɪk/','cơ bản','A2','adj'],['become','/bɪˈkʌm/','trở thành','A2','v'],['believe','/bɪˈliːv/','tin','A2','v'],['belong','/bɪˈlɔːŋ/','thuộc về','A2','v'],['benefit','/ˈbenɪfɪt/','lợi ích','A2','n'],
['borrow','/ˈbɒroʊ/','mượn','A2','v'],['break','/breɪk/','phá vỡ','A2','v'],['build','/bɪld/','xây dựng','A2','v'],['burn','/bɜːrn/','đốt cháy','A2','v'],['business','/ˈbɪznəs/','kinh doanh','A2','n'],['cancel','/ˈkænsəl/','hủy bỏ','A2','v'],['care','/ker/','quan tâm','A2','v'],['carry','/ˈkæri/','mang','A2','v'],['cause','/kɔːz/','nguyên nhân','A2','n'],['certain','/ˈsɜːrtn/','chắc chắn','A2','adj'],
['chance','/tʃæns/','cơ hội','A2','n'],['change','/tʃeɪndʒ/','thay đổi','A2','v'],['cheap','/tʃiːp/','rẻ','A2','adj'],['check','/tʃek/','kiểm tra','A2','v'],['choose','/tʃuːz/','chọn','A2','v'],['clear','/klɪr/','rõ ràng','A2','adj'],['collect','/kəˈlekt/','thu thập','A2','v'],['comfortable','/ˈkʌmftəbl/','thoải mái','A2','adj'],['common','/ˈkɒmən/','phổ biến','A2','adj'],['communicate','/kəˈmjuːnɪkeɪt/','giao tiếp','A2','v'],
['compare','/kəmˈper/','so sánh','A2','v'],['complete','/kəmˈpliːt/','hoàn thành','A2','v'],['consider','/kənˈsɪdər/','cân nhắc','A2','v'],['contain','/kənˈteɪn/','chứa','A2','v'],['continue','/kənˈtɪnjuː/','tiếp tục','A2','v'],['control','/kənˈtroʊl/','kiểm soát','A2','v'],['correct','/kəˈrekt/','đúng','A2','adj'],['cost','/kɒst/','chi phí','A2','n'],['create','/kriˈeɪt/','tạo ra','A2','v'],['cross','/krɒs/','băng qua','A2','v'],
['crowd','/kraʊd/','đám đông','A2','n'],['customer','/ˈkʌstəmər/','khách hàng','A2','n'],['damage','/ˈdæmɪdʒ/','thiệt hại','A2','n'],['danger','/ˈdeɪndʒər/','nguy hiểm','A2','n'],['decide','/dɪˈsaɪd/','quyết định','A2','v'],['deliver','/dɪˈlɪvər/','giao hàng','A2','v'],['depend','/dɪˈpend/','phụ thuộc','A2','v'],['describe','/dɪˈskraɪb/','mô tả','A2','v'],['develop','/dɪˈveləp/','phát triển','A2','v'],['discover','/dɪˈskʌvər/','khám phá','A2','v'],
// B1 - Intermediate
['accomplish','/əˈkɒmplɪʃ/','hoàn thành','B1','v'],['accurate','/ˈækjərət/','chính xác','B1','adj'],['advantage','/ədˈvæntɪdʒ/','lợi thế','B1','n'],['afford','/əˈfɔːrd/','đủ khả năng','B1','v'],['annual','/ˈænjuəl/','hàng năm','B1','adj'],['anxious','/ˈæŋkʃəs/','lo lắng','B1','adj'],['apparent','/əˈpærənt/','rõ ràng','B1','adj'],['appropriate','/əˈproʊpriət/','phù hợp','B1','adj'],['arrangement','/əˈreɪndʒmənt/','sự sắp xếp','B1','n'],['assist','/əˈsɪst/','hỗ trợ','B1','v'],
['assume','/əˈsuːm/','giả định','B1','v'],['attempt','/əˈtempt/','cố gắng','B1','v'],['attitude','/ˈætɪtjuːd/','thái độ','B1','n'],['authority','/ɔːˈθɒrəti/','quyền lực','B1','n'],['aware','/əˈwer/','nhận thức','B1','adj'],['background','/ˈbækɡraʊnd/','nền tảng','B1','n'],['behavior','/bɪˈheɪvjər/','hành vi','B1','n'],['capable','/ˈkeɪpəbl/','có khả năng','B1','adj'],['career','/kəˈrɪr/','sự nghiệp','B1','n'],['challenge','/ˈtʃælɪndʒ/','thách thức','B1','n'],
['circumstance','/ˈsɜːrkəmstæns/','hoàn cảnh','B1','n'],['claim','/kleɪm/','tuyên bố','B1','v'],['colleague','/ˈkɒliːɡ/','đồng nghiệp','B1','n'],['compete','/kəmˈpiːt/','cạnh tranh','B1','v'],['complex','/ˈkɒmpleks/','phức tạp','B1','adj'],['concentrate','/ˈkɒnsntreɪt/','tập trung','B1','v'],['concern','/kənˈsɜːrn/','lo ngại','B1','n'],['condition','/kənˈdɪʃn/','điều kiện','B1','n'],['confidence','/ˈkɒnfɪdəns/','sự tự tin','B1','n'],['confirm','/kənˈfɜːrm/','xác nhận','B1','v'],
['connect','/kəˈnekt/','kết nối','B1','v'],['consequence','/ˈkɒnsɪkwəns/','hậu quả','B1','n'],['contribute','/kənˈtrɪbjuːt/','đóng góp','B1','v'],['convince','/kənˈvɪns/','thuyết phục','B1','v'],['crisis','/ˈkraɪsɪs/','khủng hoảng','B1','n'],['critic','/ˈkrɪtɪk/','nhà phê bình','B1','n'],['crucial','/ˈkruːʃl/','then chốt','B1','adj'],['debate','/dɪˈbeɪt/','tranh luận','B1','n'],['decline','/dɪˈklaɪn/','suy giảm','B1','v'],['demand','/dɪˈmænd/','yêu cầu','B1','n'],
['demonstrate','/ˈdemənstreɪt/','chứng minh','B1','v'],['despite','/dɪˈspaɪt/','mặc dù','B1','prep'],['determine','/dɪˈtɜːrmɪn/','xác định','B1','v'],['disappoint','/ˌdɪsəˈpɔɪnt/','thất vọng','B1','v'],['economy','/ɪˈkɒnəmi/','nền kinh tế','B1','n'],['effective','/ɪˈfektɪv/','hiệu quả','B1','adj'],['eliminate','/ɪˈlɪmɪneɪt/','loại bỏ','B1','v'],['embarrass','/ɪmˈbærəs/','xấu hổ','B1','v'],['employ','/ɪmˈplɔɪ/','tuyển dụng','B1','v'],['encourage','/ɪnˈkɜːrɪdʒ/','khuyến khích','B1','v'],
// B2 - Upper Intermediate
['acknowledge','/əkˈnɒlɪdʒ/','thừa nhận','B2','v'],['adapt','/əˈdæpt/','thích nghi','B2','v'],['adequate','/ˈædɪkwət/','đầy đủ','B2','adj'],['allocate','/ˈæləkeɪt/','phân bổ','B2','v'],['ambition','/æmˈbɪʃn/','tham vọng','B2','n'],['anticipate','/ænˈtɪsɪpeɪt/','dự đoán','B2','v'],['apparent','/əˈpærənt/','hiển nhiên','B2','adj'],['assess','/əˈses/','đánh giá','B2','v'],['assumption','/əˈsʌmpʃn/','giả định','B2','n'],['bias','/ˈbaɪəs/','thiên vị','B2','n'],
['capacity','/kəˈpæsəti/','năng lực','B2','n'],['collaborate','/kəˈlæbəreɪt/','hợp tác','B2','v'],['comprehensive','/ˌkɒmprɪˈhensɪv/','toàn diện','B2','adj'],['conflict','/ˈkɒnflɪkt/','xung đột','B2','n'],['consensus','/kənˈsensəs/','đồng thuận','B2','n'],['constraint','/kənˈstreɪnt/','ràng buộc','B2','n'],['controversy','/ˈkɒntrəvɜːrsi/','tranh cãi','B2','n'],['criteria','/kraɪˈtɪəriə/','tiêu chí','B2','n'],['depict','/dɪˈpɪkt/','mô tả','B2','v'],['deteriorate','/dɪˈtɪəriəreɪt/','xấu đi','B2','v'],
['diminish','/dɪˈmɪnɪʃ/','giảm sút','B2','v'],['dilemma','/dɪˈlemə/','tình thế khó xử','B2','n'],['discrimination','/dɪˌskrɪmɪˈneɪʃn/','phân biệt đối xử','B2','n'],['diverse','/daɪˈvɜːrs/','đa dạng','B2','adj'],['elaborate','/ɪˈlæbərət/','phức tạp','B2','adj'],['emphasize','/ˈemfəsaɪz/','nhấn mạnh','B2','v'],['enhance','/ɪnˈhæns/','nâng cao','B2','v'],['enormous','/ɪˈnɔːrməs/','khổng lồ','B2','adj'],['establish','/ɪˈstæblɪʃ/','thiết lập','B2','v'],['evaluate','/ɪˈvæljueɪt/','đánh giá','B2','v'],
['exploit','/ɪkˈsplɔɪt/','khai thác','B2','v'],['fluctuate','/ˈflʌktʃueɪt/','dao động','B2','v'],['fundamental','/ˌfʌndəˈmentl/','cơ bản','B2','adj'],['generate','/ˈdʒenəreɪt/','tạo ra','B2','v'],['genuine','/ˈdʒenjuɪn/','chân thật','B2','adj'],['highlight','/ˈhaɪlaɪt/','nổi bật','B2','v'],['hypothesis','/haɪˈpɒθəsɪs/','giả thuyết','B2','n'],['implement','/ˈɪmplɪment/','triển khai','B2','v'],['implication','/ˌɪmplɪˈkeɪʃn/','hệ quả','B2','n'],['indicate','/ˈɪndɪkeɪt/','chỉ ra','B2','v'],
// C1 - Advanced / IELTS
['alleviate','/əˈliːvieɪt/','giảm bớt','C1','v'],['ambiguous','/æmˈbɪɡjuəs/','mơ hồ','C1','adj'],['autonomous','/ɔːˈtɒnəməs/','tự trị','C1','adj'],['catastrophic','/ˌkætəˈstrɒfɪk/','thảm khốc','C1','adj'],['cohesion','/koʊˈhiːʒn/','sự gắn kết','C1','n'],['compelling','/kəmˈpelɪŋ/','hấp dẫn','C1','adj'],['constitute','/ˈkɒnstɪtjuːt/','cấu thành','C1','v'],['contemplate','/ˈkɒntəmpleɪt/','suy ngẫm','C1','v'],['contradict','/ˌkɒntrəˈdɪkt/','mâu thuẫn','C1','v'],['correlation','/ˌkɒrəˈleɪʃn/','tương quan','C1','n'],
['demographic','/ˌdeməˈɡræfɪk/','nhân khẩu học','C1','adj'],['deplete','/dɪˈpliːt/','cạn kiệt','C1','v'],['detrimental','/ˌdetrɪˈmentl/','có hại','C1','adj'],['disparity','/dɪˈspærəti/','bất bình đẳng','C1','n'],['elicit','/ɪˈlɪsɪt/','gợi ra','C1','v'],['encompass','/ɪnˈkʌmpəs/','bao gồm','C1','v'],['exacerbate','/ɪɡˈzæsərbeɪt/','làm trầm trọng','C1','v'],['exemplify','/ɪɡˈzemplɪfaɪ/','minh họa','C1','v'],['facilitate','/fəˈsɪlɪteɪt/','tạo điều kiện','C1','v'],['holistic','/hoʊˈlɪstɪk/','toàn diện','C1','adj'],
['impede','/ɪmˈpiːd/','cản trở','C1','v'],['incentive','/ɪnˈsentɪv/','động lực','C1','n'],['inevitable','/ɪnˈevɪtəbl/','không thể tránh','C1','adj'],['interdisciplinary','/ˌɪntərdɪsəˈplɪnəri/','liên ngành','C1','adj'],['mitigate','/ˈmɪtɪɡeɪt/','giảm nhẹ','C1','v'],['nuanced','/ˈnjuːɑːnst/','tinh tế','C1','adj'],['paradigm','/ˈpærədaɪm/','mô hình','C1','n'],['phenomenon','/fɪˈnɒmɪnən/','hiện tượng','C1','n'],['prevalent','/ˈprevələnt/','phổ biến','C1','adj'],['proliferate','/prəˈlɪfəreɪt/','lan rộng','C1','v'],
['resilience','/rɪˈzɪliəns/','sức chống chịu','C1','n'],['scrutinize','/ˈskruːtɪnaɪz/','xem xét kỹ','C1','v'],['significant','/sɪɡˈnɪfɪkənt/','quan trọng','C1','adj'],['substantiate','/səbˈstænʃieɪt/','chứng minh','C1','v'],['sustainable','/səˈsteɪnəbl/','bền vững','C1','adj'],['undermine','/ˌʌndərˈmaɪn/','phá hoại','C1','v'],['unprecedented','/ʌnˈpresɪdentɪd/','chưa từng có','C1','adj'],['volatile','/ˈvɒlətaɪl/','biến động','C1','adj'],['vulnerability','/ˌvʌlnərəˈbɪləti/','tính dễ tổn thương','C1','n'],['warrant','/ˈwɒrənt/','bảo đảm','C1','v'],
];
