const BROWSE=[
// A1 - Beginner
['able','/ˈeɪbl/','có thể','A1','adj'],['about','/əˈbaʊt/','về, khoảng','A1','prep'],['after','/ˈæftər/','sau','A1','prep'],['again','/əˈɡen/','lại','A1','adv'],['all','/ɔːl/','tất cả','A1','det'],['also','/ˈɔːlsoʊ/','cũng','A1','adv'],['always','/ˈɔːlweɪz/','luôn luôn','A1','adv'],['and','/ænd/','và','A1','conj'],['animal','/ˈænɪməl/','động vật','A1','n'],['answer','/ˈænsər/','trả lời','A1','v'],
['ask','/æsk/','hỏi','A1','v'],['bad','/bæd/','xấu, tệ','A1','adj'],['beautiful','/ˈbjuːtɪfl/','đẹp','A1','adj'],['because','/bɪˈkɒz/','bởi vì','A1','conj'],['before','/bɪˈfɔːr/','trước','A1','prep'],['begin','/bɪˈɡɪn/','bắt đầu','A1','v'],['between','/bɪˈtwiːn/','giữa','A1','prep'],['big','/bɪɡ/','to, lớn','A1','adj'],['book','/bʊk/','sách','A1','n'],['boy','/bɔɪ/','con trai','A1','n'],
['bring','/brɪŋ/','mang đến','A1','v'],['brother','/ˈbrʌðər/','anh/em trai','A1','n'],['buy','/baɪ/','mua','A1','v'],['call','/kɔːl/','gọi','A1','v'],['car','/kɑːr/','xe hơi','A1','n'],['cat','/kæt/','con mèo','A1','n'],['child','/tʃaɪld/','trẻ em','A1','n'],['city','/ˈsɪti/','thành phố','A1','n'],['close','/kloʊz/','đóng','A1','v'],['cold','/koʊld/','lạnh','A1','adj'],
['come','/kʌm/','đến','A1','v'],['cook','/kʊk/','nấu ăn','A1','v'],['country','/ˈkʌntri/','đất nước','A1','n'],['day','/deɪ/','ngày','A1','n'],['different','/ˈdɪfrənt/','khác nhau','A1','adj'],['difficult','/ˈdɪfɪkəlt/','khó','A1','adj'],['do','/duː/','làm','A1','v'],['dog','/dɔːɡ/','con chó','A1','n'],['door','/dɔːr/','cửa','A1','n'],['drink','/drɪŋk/','uống','A1','v'],
['drive','/draɪv/','lái xe','A1','v'],['eat','/iːt/','ăn','A1','v'],['end','/end/','kết thúc','A1','n'],['every','/ˈevri/','mỗi','A1','det'],['eye','/aɪ/','mắt','A1','n'],['family','/ˈfæməli/','gia đình','A1','n'],['far','/fɑːr/','xa','A1','adj'],['fast','/fæst/','nhanh','A1','adj'],['father','/ˈfɑːðər/','cha','A1','n'],['find','/faɪnd/','tìm','A1','v'],
['first','/fɜːrst/','đầu tiên','A1','adj'],['food','/fuːd/','thức ăn','A1','n'],['friend','/frend/','bạn bè','A1','n'],['get','/ɡet/','lấy, được','A1','v'],['girl','/ɡɜːrl/','con gái','A1','n'],['give','/ɡɪv/','cho','A1','v'],['go','/ɡoʊ/','đi','A1','v'],['good','/ɡʊd/','tốt','A1','adj'],['great','/ɡreɪt/','tuyệt vời','A1','adj'],['green','/ɡriːn/','xanh lá','A1','adj'],
['hand','/hænd/','tay','A1','n'],['happy','/ˈhæpi/','vui','A1','adj'],['have','/hæv/','có','A1','v'],['he','/hiː/','anh ấy','A1','pron'],['hear','/hɪr/','nghe','A1','v'],['help','/help/','giúp đỡ','A1','v'],['here','/hɪr/','ở đây','A1','adv'],['home','/hoʊm/','nhà','A1','n'],['hot','/hɒt/','nóng','A1','adj'],['house','/haʊs/','ngôi nhà','A1','n'],
['important','/ɪmˈpɔːrtənt/','quan trọng','A1','adj'],['in','/ɪn/','trong','A1','prep'],['interesting','/ˈɪntrəstɪŋ/','thú vị','A1','adj'],['job','/dʒɒb/','công việc','A1','n'],['know','/noʊ/','biết','A1','v'],['large','/lɑːrdʒ/','lớn','A1','adj'],['last','/læst/','cuối cùng','A1','adj'],['late','/leɪt/','muộn','A1','adj'],['learn','/lɜːrn/','học','A1','v'],['leave','/liːv/','rời đi','A1','v'],
['life','/laɪf/','cuộc sống','A1','n'],['like','/laɪk/','thích','A1','v'],['listen','/ˈlɪsn/','lắng nghe','A1','v'],['little','/ˈlɪtl/','nhỏ, ít','A1','adj'],['live','/lɪv/','sống','A1','v'],['long','/lɔːŋ/','dài','A1','adj'],['look','/lʊk/','nhìn','A1','v'],['love','/lʌv/','yêu','A1','v'],['make','/meɪk/','làm, tạo','A1','v'],['man','/mæn/','đàn ông','A1','n'],
// A2 - Elementary
['accept','/əkˈsept/','chấp nhận','A2','v'],['accident','/ˈæksɪdənt/','tai nạn','A2','n'],['achieve','/əˈtʃiːv/','đạt được','A2','v'],['across','/əˈkrɒs/','ngang qua','A2','prep'],['advice','/ədˈvaɪs/','lời khuyên','A2','n'],['agree','/əˈɡriː/','đồng ý','A2','v'],['allow','/əˈlaʊ/','cho phép','A2','v'],['although','/ɔːlˈðoʊ/','mặc dù','A2','conj'],['amount','/əˈmaʊnt/','số lượng','A2','n'],['appear','/əˈpɪr/','xuất hiện','A2','v'],
['apply','/əˈplaɪ/','nộp đơn','A2','v'],['arrive','/əˈraɪv/','đến nơi','A2','v'],['attention','/əˈtenʃn/','sự chú ý','A2','n'],['available','/əˈveɪləbl/','có sẵn','A2','adj'],['avoid','/əˈvɔɪd/','tránh','A2','v'],['basic','/ˈbeɪsɪk/','cơ bản','A2','adj'],['become','/bɪˈkʌm/','trở thành','A2','v'],['believe','/bɪˈliːv/','tin','A2','v'],['belong','/bɪˈlɔːŋ/','thuộc về','A2','v'],['benefit','/ˈbenɪfɪt/','lợi ích','A2','n'],
['borrow','/ˈbɒroʊ/','mượn','A2','v'],['break','/breɪk/','phá vỡ','A2','v'],['build','/bɪld/','xây dựng','A2','v'],['burn','/bɜːrn/','đốt cháy','A2','v'],['business','/ˈbɪznəs/','kinh doanh','A2','n'],['cancel','/ˈkænsəl/','hủy bỏ','A2','v'],['care','/ker/','quan tâm','A2','v'],['carry','/ˈkæri/','mang','A2','v'],['cause','/kɔːz/','nguyên nhân','A2','n'],['certain','/ˈsɜːrtn/','chắc chắn','A2','adj'],
['chance','/tʃæns/','cơ hội','A2','n'],['change','/tʃeɪndʒ/','thay đổi','A2','v'],['cheap','/tʃiːp/','rẻ','A2','adj'],['check','/tʃek/','kiểm tra','A2','v'],['choose','/tʃuːz/','chọn','A2','v'],['clear','/klɪr/','rõ ràng','A2','adj'],['collect','/kəˈlekt/','thu thập','A2','v'],['comfortable','/ˈkʌmftəbl/','thoải mái','A2','adj'],['common','/ˈkɒmən/','phổ biến','A2','adj'],['communicate','/kəˈmjuːnɪkeɪt/','giao tiếp','A2','v'],
['compare','/kəmˈper/','so sánh','A2','v'],['complete','/kəmˈpliːt/','hoàn thành','A2','v'],['consider','/kənˈsɪdər/','cân nhắc','A2','v'],['contain','/kənˈteɪn/','chứa','A2','v'],['continue','/kənˈtɪnjuː/','tiếp tục','A2','v'],['control','/kənˈtroʊl/','kiểm soát','A2','v'],['correct','/kəˈrekt/','đúng','A2','adj'],['cost','/kɒst/','chi phí','A2','n'],['create','/kriˈeɪt/','tạo ra','A2','v'],['cross','/krɒs/','băng qua','A2','v'],
['crowd','/kraʊd/','đám đông','A2','n'],['customer','/ˈkʌstəmər/','khách hàng','A2','n'],['damage','/ˈdæmɪdʒ/','thiệt hại','A2','n'],['danger','/ˈdeɪndʒər/','nguy hiểm','A2','n'],['decide','/dɪˈsaɪd/','quyết định','A2','v'],['deliver','/dɪˈlɪvər/','giao hàng','A2','v'],['depend','/dɪˈpend/','phụ thuộc','A2','v'],['describe','/dɪˈskraɪb/','mô tả','A2','v'],['develop','/dɪˈveləp/','phát triển','A2','v'],['discover','/dɪˈskʌvər/','khám phá','A2','v'],
// B1 - Intermediate
['accomplish','/əˈkɒmplɪʃ/','hoàn thành','B1','v'],['accurate','/ˈækjərət/','chính xác','B1','adj'],['advantage','/ədˈvæntɪdʒ/','lợi thế','B1','n'],['afford','/əˈfɔːrd/','đủ khả năng','B1','v'],['annual','/ˈænjuəl/','hàng năm','B1','adj'],['anxious','/ˈæŋkʃəs/','lo lắng','B1','adj'],['apparent','/əˈpærənt/','rõ ràng','B1','adj'],['appropriate','/əˈproʊpriət/','phù hợp','B1','adj'],['arrangement','/əˈreɪndʒmənt/','sự sắp xếp','B1','n'],['assist','/əˈsɪst/','hỗ trợ','B1','v'],
['assume','/əˈsuːm/','giả định','B1','v'],['attempt','/əˈtempt/','cố gắng','B1','v'],['attitude','/ˈætɪtjuːd/','thái độ','B1','n'],['authority','/ɔːˈθɒrəti/','quyền lực','B1','n'],['aware','/əˈwer/','nhận thức','B1','adj'],['background','/ˈbækɡraʊnd/','nền tảng','B1','n'],['behavior','/bɪˈheɪvjər/','hành vi','B1','n'],['capable','/ˈkeɪpəbl/','có khả năng','B1','adj'],['career','/kəˈrɪr/','sự nghiệp','B1','n'],['challenge','/ˈtʃælɪndʒ/','thách thức','B1','n'],
['circumstance','/ˈsɜːrkəmstæns/','hoàn cảnh','B1','n'],['claim','/kleɪm/','tuyên bố','B1','v'],['colleague','/ˈkɒliːɡ/','đồng nghiệp','B1','n'],['compete','/kəmˈpiːt/','cạnh tranh','B1','v'],['complex','/ˈkɒmpleks/','phức tạp','B1','adj'],['concentrate','/ˈkɒnsntreɪt/','tập trung','B1','v'],['concern','/kənˈsɜːrn/','lo ngại','B1','n'],['condition','/kənˈdɪʃn/','điều kiện','B1','n'],['confidence','/ˈkɒnfɪdəns/','sự tự tin','B1','n'],['confirm','/kənˈfɜːrm/','xác nhận','B1','v'],
['connect','/kəˈnekt/','kết nối','B1','v'],['consequence','/ˈkɒnsɪkwəns/','hậu quả','B1','n'],['contribute','/kənˈtrɪbjuːt/','đóng góp','B1','v'],['convince','/kənˈvɪns/','thuyết phục','B1','v'],['crisis','/ˈkraɪsɪs/','khủng hoảng','B1','n'],['critic','/ˈkrɪtɪk/','nhà phê bình','B1','n'],['crucial','/ˈkruːʃl/','then chốt','B1','adj'],['debate','/dɪˈbeɪt/','tranh luận','B1','n'],['decline','/dɪˈklaɪn/','suy giảm','B1','v'],['demand','/dɪˈmænd/','yêu cầu','B1','n'],
['demonstrate','/ˈdemənstreɪt/','chứng minh','B1','v'],['despite','/dɪˈspaɪt/','mặc dù','B1','prep'],['determine','/dɪˈtɜːrmɪn/','xác định','B1','v'],['disappoint','/ˌdɪsəˈpɔɪnt/','thất vọng','B1','v'],['economy','/ɪˈkɒnəmi/','nền kinh tế','B1','n'],['effective','/ɪˈfektɪv/','hiệu quả','B1','adj'],['eliminate','/ɪˈlɪmɪneɪt/','loại bỏ','B1','v'],['embarrass','/ɪmˈbærəs/','xấu hổ','B1','v'],['employ','/ɪmˈplɔɪ/','tuyển dụng','B1','v'],['encourage','/ɪnˈkɜːrɪdʒ/','khuyến khích','B1','v'],
// B2 - Upper Intermediate
['acknowledge','/əkˈnɒlɪdʒ/','thừa nhận','B2','v'],['adapt','/əˈdæpt/','thích nghi','B2','v'],['adequate','/ˈædɪkwət/','đầy đủ','B2','adj'],['allocate','/ˈæləkeɪt/','phân bổ','B2','v'],['ambition','/æmˈbɪʃn/','tham vọng','B2','n'],['anticipate','/ænˈtɪsɪpeɪt/','dự đoán','B2','v'],['apparent','/əˈpærənt/','hiển nhiên','B2','adj'],['assess','/əˈses/','đánh giá','B2','v'],['assumption','/əˈsʌmpʃn/','giả định','B2','n'],['bias','/ˈbaɪəs/','thiên vị','B2','n'],
['capacity','/kəˈpæsəti/','năng lực','B2','n'],['collaborate','/kəˈlæbəreɪt/','hợp tác','B2','v'],['comprehensive','/ˌkɒmprɪˈhensɪv/','toàn diện','B2','adj'],['conflict','/ˈkɒnflɪkt/','xung đột','B2','n'],['consensus','/kənˈsensəs/','đồng thuận','B2','n'],['constraint','/kənˈstreɪnt/','ràng buộc','B2','n'],['controversy','/ˈkɒntrəvɜːrsi/','tranh cãi','B2','n'],['criteria','/kraɪˈtɪəriə/','tiêu chí','B2','n'],['depict','/dɪˈpɪkt/','mô tả','B2','v'],['deteriorate','/dɪˈtɪəriəreɪt/','xấu đi','B2','v'],
['diminish','/dɪˈmɪnɪʃ/','giảm sút','B2','v'],['dilemma','/dɪˈlemə/','tình thế khó xử','B2','n'],['discrimination','/dɪˌskrɪmɪˈneɪʃn/','phân biệt đối xử','B2','n'],['diverse','/daɪˈvɜːrs/','đa dạng','B2','adj'],['elaborate','/ɪˈlæbərət/','phức tạp','B2','adj'],['emphasize','/ˈemfəsaɪz/','nhấn mạnh','B2','v'],['enhance','/ɪnˈhæns/','nâng cao','B2','v'],['enormous','/ɪˈnɔːrməs/','khổng lồ','B2','adj'],['establish','/ɪˈstæblɪʃ/','thiết lập','B2','v'],['evaluate','/ɪˈvæljueɪt/','đánh giá','B2','v'],
['exploit','/ɪkˈsplɔɪt/','khai thác','B2','v'],['fluctuate','/ˈflʌktʃueɪt/','dao động','B2','v'],['fundamental','/ˌfʌndəˈmentl/','cơ bản','B2','adj'],['generate','/ˈdʒenəreɪt/','tạo ra','B2','v'],['genuine','/ˈdʒenjuɪn/','chân thật','B2','adj'],['highlight','/ˈhaɪlaɪt/','nổi bật','B2','v'],['hypothesis','/haɪˈpɒθəsɪs/','giả thuyết','B2','n'],['implement','/ˈɪmplɪment/','triển khai','B2','v'],['implication','/ˌɪmplɪˈkeɪʃn/','hệ quả','B2','n'],['indicate','/ˈɪndɪkeɪt/','chỉ ra','B2','v'],
// C1 - Advanced / IELTS
['alleviate','/əˈliːvieɪt/','giảm bớt','C1','v'],['ambiguous','/æmˈbɪɡjuəs/','mơ hồ','C1','adj'],['autonomous','/ɔːˈtɒnəməs/','tự trị','C1','adj'],['catastrophic','/ˌkætəˈstrɒfɪk/','thảm khốc','C1','adj'],['cohesion','/koʊˈhiːʒn/','sự gắn kết','C1','n'],['compelling','/kəmˈpelɪŋ/','hấp dẫn','C1','adj'],['constitute','/ˈkɒnstɪtjuːt/','cấu thành','C1','v'],['contemplate','/ˈkɒntəmpleɪt/','suy ngẫm','C1','v'],['contradict','/ˌkɒntrəˈdɪkt/','mâu thuẫn','C1','v'],['correlation','/ˌkɒrəˈleɪʃn/','tương quan','C1','n'],
['demographic','/ˌdeməˈɡræfɪk/','nhân khẩu học','C1','adj'],['deplete','/dɪˈpliːt/','cạn kiệt','C1','v'],['detrimental','/ˌdetrɪˈmentl/','có hại','C1','adj'],['disparity','/dɪˈspærəti/','bất bình đẳng','C1','n'],['elicit','/ɪˈlɪsɪt/','gợi ra','C1','v'],['encompass','/ɪnˈkʌmpəs/','bao gồm','C1','v'],['exacerbate','/ɪɡˈzæsərbeɪt/','làm trầm trọng','C1','v'],['exemplify','/ɪɡˈzemplɪfaɪ/','minh họa','C1','v'],['facilitate','/fəˈsɪlɪteɪt/','tạo điều kiện','C1','v'],['holistic','/hoʊˈlɪstɪk/','toàn diện','C1','adj'],
['impede','/ɪmˈpiːd/','cản trở','C1','v'],['incentive','/ɪnˈsentɪv/','động lực','C1','n'],['inevitable','/ɪnˈevɪtəbl/','không thể tránh','C1','adj'],['interdisciplinary','/ˌɪntərdɪsəˈplɪnəri/','liên ngành','C1','adj'],['mitigate','/ˈmɪtɪɡeɪt/','giảm nhẹ','C1','v'],['nuanced','/ˈnjuːɑːnst/','tinh tế','C1','adj'],['paradigm','/ˈpærədaɪm/','mô hình','C1','n'],['phenomenon','/fɪˈnɒmɪnən/','hiện tượng','C1','n'],['prevalent','/ˈprevələnt/','phổ biến','C1','adj'],['proliferate','/prəˈlɪfəreɪt/','lan rộng','C1','v'],
['resilience','/rɪˈzɪliəns/','sức chống chịu','C1','n'],['scrutinize','/ˈskruːtɪnaɪz/','xem xét kỹ','C1','v'],['significant','/sɪɡˈnɪfɪkənt/','quan trọng','C1','adj'],['substantiate','/səbˈstænʃieɪt/','chứng minh','C1','v'],['sustainable','/səˈsteɪnəbl/','bền vững','C1','adj'],['undermine','/ˌʌndərˈmaɪn/','phá hoại','C1','v'],['unprecedented','/ʌnˈpresɪdentɪd/','chưa từng có','C1','adj'],['volatile','/ˈvɒlətaɪl/','biến động','C1','adj'],['vulnerability','/ˌvʌlnərəˈbɪləti/','tính dễ tổn thương','C1','n'],['warrant','/ˈwɒrənt/','bảo đảm','C1','v'],
// C2 - Proficiency
['aberration','/ˌæbəˈreɪʃn/','sự lệch lạc','C2','n'],['acquiesce','/ˌækwiˈes/','miễn cưỡng đồng ý','C2','v'],['anachronistic','/əˌnækrəˈnɪstɪk/','lỗi thời','C2','adj'],['bellicose','/ˈbelɪkoʊs/','hiếu chiến','C2','adj'],['capitulate','/kəˈpɪtʃuleɪt/','đầu hàng','C2','v'],['conundrum','/kəˈnʌndrəm/','câu đố hóc búa','C2','n'],['delineate','/dɪˈlɪnieɪt/','phác thảo rõ ràng','C2','v'],['dichotomy','/daɪˈkɒtəmi/','sự phân đôi','C2','n'],['efficacious','/ˌefɪˈkeɪʃəs/','có hiệu lực','C2','adj'],['ephemeral','/ɪˈfemərəl/','phù du, tạm thời','C2','adj'],
['equivocate','/ɪˈkwɪvəkeɪt/','nói nước đôi','C2','v'],['furtive','/ˈfɜːrtɪv/','lén lút','C2','adj'],['gregarious','/ɡrɪˈɡeriəs/','thích giao du','C2','adj'],['hubris','/ˈhjuːbrɪs/','sự kiêu ngạo thái quá','C2','n'],['idiosyncratic','/ˌɪdiəsɪŋˈkrætɪk/','đặc thù cá nhân','C2','adj'],['juxtapose','/ˌdʒʌkstəˈpoʊz/','đặt cạnh nhau so sánh','C2','v'],['loquacious','/loʊˈkweɪʃəs/','nói nhiều','C2','adj'],['magnanimous','/mæɡˈnænɪməs/','độ lượng','C2','adj'],['nefarious','/nɪˈferiəs/','xấu xa','C2','adj'],['obfuscate','/ˈɒbfʌskeɪt/','làm rối, che đậy','C2','v'],
['pernicious','/pərˈnɪʃəs/','độc hại','C2','adj'],['quintessential','/ˌkwɪntɪˈsenʃl/','tinh túy nhất','C2','adj'],['recalcitrant','/rɪˈkælsɪtrənt/','bướng bỉnh','C2','adj'],['surreptitious','/ˌsɜːrəpˈtɪʃəs/','bí mật, lén lút','C2','adj'],['trepidation','/ˌtrepɪˈdeɪʃn/','sự lo sợ','C2','n'],['ubiquitous','/juːˈbɪkwɪtəs/','có mặt khắp nơi','C2','adj'],['vacillate','/ˈvæsɪleɪt/','do dự, lưỡng lự','C2','v'],['vicissitude','/vɪˈsɪsɪtjuːd/','sự thăng trầm','C2','n'],['zealous','/ˈzeləs/','nhiệt thành','C2','adj'],['amalgamate','/əˈmælɡəmeɪt/','hợp nhất','C2','v'],
// A1 - Bổ sung
['mother','/ˈmʌðər/','mẹ','A1','n'],['name','/neɪm/','tên','A1','n'],['new','/njuː/','mới','A1','adj'],['night','/naɪt/','đêm','A1','n'],['number','/ˈnʌmbər/','số','A1','n'],['old','/oʊld/','cũ, già','A1','adj'],['open','/ˈoʊpən/','mở','A1','v'],['part','/pɑːrt/','phần','A1','n'],['people','/ˈpiːpl/','người, mọi người','A1','n'],['place','/pleɪs/','nơi, chỗ','A1','n'],
['play','/pleɪ/','chơi','A1','v'],['problem','/ˈprɒbləm/','vấn đề','A1','n'],['put','/pʊt/','đặt, để','A1','v'],['read','/riːd/','đọc','A1','v'],['right','/raɪt/','đúng, phải','A1','adj'],['room','/ruːm/','phòng','A1','n'],['run','/rʌn/','chạy','A1','v'],['say','/seɪ/','nói','A1','v'],['school','/skuːl/','trường học','A1','n'],['see','/siː/','thấy, nhìn thấy','A1','v'],
['she','/ʃiː/','cô ấy','A1','pron'],['show','/ʃoʊ/','cho xem','A1','v'],['sister','/ˈsɪstər/','chị/em gái','A1','n'],['sit','/sɪt/','ngồi','A1','v'],['sleep','/sliːp/','ngủ','A1','v'],['small','/smɔːl/','nhỏ','A1','adj'],['start','/stɑːrt/','bắt đầu','A1','v'],['stop','/stɒp/','dừng lại','A1','v'],['student','/ˈstjuːdnt/','sinh viên','A1','n'],['study','/ˈstʌdi/','học','A1','v'],
['swim','/swɪm/','bơi','A1','v'],['table','/ˈteɪbl/','bàn','A1','n'],['take','/teɪk/','lấy','A1','v'],['talk','/tɔːk/','nói chuyện','A1','v'],['teacher','/ˈtiːtʃər/','giáo viên','A1','n'],['tell','/tel/','kể','A1','v'],['think','/θɪŋk/','nghĩ','A1','v'],['time','/taɪm/','thời gian','A1','n'],['try','/traɪ/','cố gắng','A1','v'],['turn','/tɜːrn/','quay','A1','v'],
['understand','/ˌʌndərˈstænd/','hiểu','A1','v'],['use','/juːz/','sử dụng','A1','v'],['very','/ˈveri/','rất','A1','adv'],['wait','/weɪt/','đợi','A1','v'],['walk','/wɔːk/','đi bộ','A1','v'],['want','/wɒnt/','muốn','A1','v'],['watch','/wɒtʃ/','xem','A1','v'],['water','/ˈwɔːtər/','nước','A1','n'],['week','/wiːk/','tuần','A1','n'],['woman','/ˈwʊmən/','phụ nữ','A1','n'],
['work','/wɜːrk/','làm việc','A1','v'],['world','/wɜːrld/','thế giới','A1','n'],['write','/raɪt/','viết','A1','v'],['year','/jɪr/','năm','A1','n'],['young','/jʌŋ/','trẻ','A1','adj'],['color','/ˈkʌlər/','màu sắc','A1','n'],['money','/ˈmʌni/','tiền','A1','n'],['morning','/ˈmɔːrnɪŋ/','buổi sáng','A1','n'],['music','/ˈmjuːzɪk/','âm nhạc','A1','n'],['weather','/ˈweðər/','thời tiết','A1','n'],
// A2 - Bổ sung
['discuss','/dɪˈskʌs/','thảo luận','A2','v'],['doubt','/daʊt/','nghi ngờ','A2','v'],['earn','/ɜːrn/','kiếm được','A2','v'],['effort','/ˈefərt/','nỗ lực','A2','n'],['encourage','/ɪnˈkɜːrɪdʒ/','khuyến khích','A2','v'],['enemy','/ˈenəmi/','kẻ thù','A2','n'],['energy','/ˈenərdʒi/','năng lượng','A2','n'],['enjoy','/ɪnˈdʒɔɪ/','tận hưởng','A2','v'],['environment','/ɪnˈvaɪrənmənt/','môi trường','A2','n'],['especially','/ɪˈspeʃəli/','đặc biệt','A2','adv'],
['examine','/ɪɡˈzæmɪn/','kiểm tra','A2','v'],['exercise','/ˈeksərsaɪz/','bài tập, tập thể dục','A2','n'],['expect','/ɪkˈspekt/','mong đợi','A2','v'],['experience','/ɪkˈspɪriəns/','kinh nghiệm','A2','n'],['explain','/ɪkˈspleɪn/','giải thích','A2','v'],['explore','/ɪkˈsplɔːr/','khám phá','A2','v'],['express','/ɪkˈspres/','diễn đạt','A2','v'],['fail','/feɪl/','thất bại','A2','v'],['fair','/fer/','công bằng','A2','adj'],['fault','/fɔːlt/','lỗi','A2','n'],
['feature','/ˈfiːtʃər/','đặc điểm','A2','n'],['focus','/ˈfoʊkəs/','tập trung','A2','v'],['follow','/ˈfɒloʊ/','theo dõi','A2','v'],['force','/fɔːrs/','lực, ép buộc','A2','n'],['foreign','/ˈfɒrən/','ngoại quốc','A2','adj'],['forever','/fərˈevər/','mãi mãi','A2','adv'],['forget','/fərˈɡet/','quên','A2','v'],['freedom','/ˈfriːdəm/','tự do','A2','n'],['fresh','/freʃ/','tươi','A2','adj'],['frighten','/ˈfraɪtn/','làm sợ hãi','A2','v'],
['gain','/ɡeɪn/','đạt được','A2','v'],['gentle','/ˈdʒentl/','nhẹ nhàng','A2','adj'],['gift','/ɡɪft/','quà tặng','A2','n'],['goal','/ɡoʊl/','mục tiêu','A2','n'],['guard','/ɡɑːrd/','bảo vệ','A2','v'],['guess','/ɡes/','đoán','A2','v'],['guide','/ɡaɪd/','hướng dẫn','A2','v'],['habit','/ˈhæbɪt/','thói quen','A2','n'],['harm','/hɑːrm/','gây hại','A2','v'],['honest','/ˈɒnɪst/','trung thực','A2','adj'],
// B1 - Bổ sung
['enthusiasm','/ɪnˈθjuːziæzəm/','sự nhiệt tình','B1','n'],['estimate','/ˈestɪmeɪt/','ước tính','B1','v'],['eventual','/ɪˈventʃuəl/','cuối cùng','B1','adj'],['evidence','/ˈevɪdəns/','bằng chứng','B1','n'],['evolution','/ˌiːvəˈluːʃn/','sự tiến hóa','B1','n'],['exception','/ɪkˈsepʃn/','ngoại lệ','B1','n'],['exchange','/ɪksˈtʃeɪndʒ/','trao đổi','B1','v'],['executive','/ɪɡˈzekjətɪv/','giám đốc điều hành','B1','n'],['expand','/ɪkˈspænd/','mở rộng','B1','v'],['expert','/ˈekspɜːrt/','chuyên gia','B1','n'],
['expose','/ɪkˈspoʊz/','phơi bày','B1','v'],['extend','/ɪkˈstend/','kéo dài','B1','v'],['extreme','/ɪkˈstriːm/','cực đoan','B1','adj'],['factor','/ˈfæktər/','yếu tố','B1','n'],['fiction','/ˈfɪkʃn/','tiểu thuyết, hư cấu','B1','n'],['fortunate','/ˈfɔːrtʃənət/','may mắn','B1','adj'],['foundation','/faʊnˈdeɪʃn/','nền tảng','B1','n'],['framework','/ˈfreɪmwɜːrk/','khung, cơ cấu','B1','n'],['frequent','/ˈfriːkwənt/','thường xuyên','B1','adj'],['frustrated','/frʌˈstreɪtɪd/','thất vọng','B1','adj'],
['fulfill','/fʊlˈfɪl/','hoàn thành','B1','v'],['function','/ˈfʌŋkʃn/','chức năng','B1','n'],['global','/ˈɡloʊbl/','toàn cầu','B1','adj'],['gradually','/ˈɡrædʒuəli/','dần dần','B1','adv'],['guarantee','/ˌɡærənˈtiː/','bảo đảm','B1','v'],['identity','/aɪˈdentəti/','danh tính','B1','n'],['ignore','/ɪɡˈnɔːr/','phớt lờ','B1','v'],['illustrate','/ˈɪləstreɪt/','minh họa','B1','v'],['impact','/ˈɪmpækt/','tác động','B1','n'],['impose','/ɪmˈpoʊz/','áp đặt','B1','v'],
// B2 - Bổ sung
['infrastructure','/ˈɪnfrəstrʌktʃər/','cơ sở hạ tầng','B2','n'],['inherent','/ɪnˈhɪrənt/','vốn có','B2','adj'],['innovation','/ˌɪnəˈveɪʃn/','sự đổi mới','B2','n'],['insight','/ˈɪnsaɪt/','cái nhìn sâu sắc','B2','n'],['integrity','/ɪnˈteɡrəti/','sự chính trực','B2','n'],['intervention','/ˌɪntərˈvenʃn/','sự can thiệp','B2','n'],['justify','/ˈdʒʌstɪfaɪ/','biện minh','B2','v'],['legitimate','/lɪˈdʒɪtɪmət/','hợp pháp','B2','adj'],['liable','/ˈlaɪəbl/','có trách nhiệm pháp lý','B2','adj'],['likewise','/ˈlaɪkwaɪz/','tương tự','B2','adv'],
['manipulation','/məˌnɪpjuˈleɪʃn/','sự thao túng','B2','n'],['mechanism','/ˈmekənɪzəm/','cơ chế','B2','n'],['minimal','/ˈmɪnɪməl/','tối thiểu','B2','adj'],['modify','/ˈmɒdɪfaɪ/','sửa đổi','B2','v'],['negotiate','/nɪˈɡoʊʃieɪt/','đàm phán','B2','v'],['notion','/ˈnoʊʃn/','khái niệm','B2','n'],['obligation','/ˌɒblɪˈɡeɪʃn/','nghĩa vụ','B2','n'],['obtain','/əbˈteɪn/','đạt được','B2','v'],['outcome','/ˈaʊtkʌm/','kết quả','B2','n'],['perceive','/pərˈsiːv/','nhận thức','B2','v'],
['perspective','/pərˈspektɪv/','quan điểm','B2','n'],['phenomenon','/fɪˈnɒmɪnən/','hiện tượng','B2','n'],['portion','/ˈpɔːrʃn/','phần','B2','n'],['potential','/pəˈtenʃl/','tiềm năng','B2','n'],['predominantly','/prɪˈdɒmɪnəntli/','chủ yếu','B2','adv'],['presumably','/prɪˈzjuːməbli/','có lẽ','B2','adv'],['principle','/ˈprɪnsəpl/','nguyên tắc','B2','n'],['priority','/praɪˈɒrəti/','ưu tiên','B2','n'],['prospect','/ˈprɒspekt/','triển vọng','B2','n'],['pursue','/pərˈsjuː/','theo đuổi','B2','v'],
// C1 - Bổ sung
['ramification','/ˌræmɪfɪˈkeɪʃn/','hệ quả phức tạp','C1','n'],['rationale','/ˌræʃəˈnæl/','lý do cơ bản','C1','n'],['reconcile','/ˈrekənsaɪl/','hòa giải','C1','v'],['redundant','/rɪˈdʌndənt/','dư thừa','C1','adj'],['reinforce','/ˌriːɪnˈfɔːrs/','củng cố','C1','v'],['relinquish','/rɪˈlɪŋkwɪʃ/','từ bỏ','C1','v'],['repercussion','/ˌriːpərˈkʌʃn/','hậu quả','C1','n'],['rhetoric','/ˈretərɪk/','tu từ học','C1','n'],['rigorous','/ˈrɪɡərəs/','nghiêm ngặt','C1','adj'],['salient','/ˈseɪliənt/','nổi bật','C1','adj'],
['spectrum','/ˈspektrəm/','phổ, dải','C1','n'],['stipulate','/ˈstɪpjuleɪt/','quy định','C1','v'],['subsidiary','/səbˈsɪdiəri/','công ty con','C1','n'],['sufficient','/səˈfɪʃnt/','đầy đủ','C1','adj'],['supplement','/ˈsʌplɪmənt/','bổ sung','C1','v'],['symmetry','/ˈsɪmətri/','sự đối xứng','C1','n'],['tangible','/ˈtændʒəbl/','hữu hình','C1','adj'],['tenacious','/tɪˈneɪʃəs/','kiên trì','C1','adj'],['trajectory','/trəˈdʒektəri/','quỹ đạo','C1','n'],['transcend','/trænˈsend/','vượt qua','C1','v'],
// C2 - Bổ sung
['antithesis','/ænˈtɪθəsɪs/','đối lập','C2','n'],['cacophony','/kəˈkɒfəni/','tiếng ồn chói tai','C2','n'],['circumvent','/ˌsɜːrkəmˈvent/','lách, né tránh','C2','v'],['cogent','/ˈkoʊdʒənt/','thuyết phục','C2','adj'],['conflagration','/ˌkɒnfləˈɡreɪʃn/','đám cháy lớn','C2','n'],['debilitate','/dɪˈbɪlɪteɪt/','làm suy yếu','C2','v'],['disparage','/dɪˈspærɪdʒ/','coi thường','C2','v'],['elucidate','/ɪˈluːsɪdeɪt/','làm sáng tỏ','C2','v'],['enervate','/ˈenərveɪt/','làm kiệt sức','C2','v'],['extricate','/ˈekstrɪkeɪt/','giải thoát','C2','v'],
['fastidious','/fæˈstɪdiəs/','cầu kỳ, khó tính','C2','adj'],['garrulous','/ˈɡærələs/','nói nhiều','C2','adj'],['harangue','/həˈræŋ/','bài diễn thuyết dài dòng','C2','n'],['iconoclast','/aɪˈkɒnəklæst/','người phá bỏ truyền thống','C2','n'],['impetuous','/ɪmˈpetʃuəs/','bốc đồng','C2','adj'],['inscrutable','/ɪnˈskruːtəbl/','bí ẩn, khó hiểu','C2','adj'],['laconic','/ləˈkɒnɪk/','ngắn gọn','C2','adj'],['malfeasance','/mælˈfiːzns/','hành vi sai trái','C2','n'],['mendacious','/menˈdeɪʃəs/','dối trá','C2','adj'],['obsequious','/əbˈsiːkwiəs/','nịnh hót','C2','adj'],
['parsimonious','/ˌpɑːrsɪˈmoʊniəs/','keo kiệt','C2','adj'],['perfunctory','/pərˈfʌŋktəri/','qua loa, chiếu lệ','C2','adj'],['promulgate','/ˈprɒməlɡeɪt/','ban hành, công bố','C2','v'],['propitious','/prəˈpɪʃəs/','thuận lợi','C2','adj'],['remuneration','/rɪˌmjuːnəˈreɪʃn/','thù lao','C2','n'],['sanguine','/ˈsæŋɡwɪn/','lạc quan','C2','adj'],['soporific','/ˌsɒpəˈrɪfɪk/','gây buồn ngủ','C2','adj'],['truculent','/ˈtrʌkjələnt/','hung hãn','C2','adj'],['verisimilitude','/ˌverɪsɪˈmɪlɪtjuːd/','tính chân thực','C2','n'],['vituperate','/vɪˈtjuːpəreɪt/','chửi rủa','C2','v'],
// ═══════════ CHUYÊN NGÀNH: Y TẾ (Medical) ═══════════
['diagnosis','/ˌdaɪəɡˈnoʊsɪs/','chẩn đoán','B2','n'],['symptom','/ˈsɪmptəm/','triệu chứng','B1','n'],['prescription','/prɪˈskrɪpʃn/','đơn thuốc','B1','n'],['surgery','/ˈsɜːrdʒəri/','phẫu thuật','B1','n'],['vaccine','/vækˈsiːn/','vắc-xin','A2','n'],['infection','/ɪnˈfekʃn/','nhiễm trùng','B1','n'],['chronic','/ˈkrɒnɪk/','mãn tính','B2','adj'],['acute','/əˈkjuːt/','cấp tính','B2','adj'],['therapy','/ˈθerəpi/','liệu pháp','B1','n'],['antibiotic','/ˌæntɪbaɪˈɒtɪk/','kháng sinh','B2','n'],
['anesthesia','/ˌænəsˈθiːziə/','gây mê','C1','n'],['pathology','/pəˈθɒlədʒi/','bệnh lý học','C1','n'],['prognosis','/prɒɡˈnoʊsɪs/','tiên lượng','C1','n'],['rehabilitation','/ˌriːhəˌbɪlɪˈteɪʃn/','phục hồi chức năng','B2','n'],['outpatient','/ˈaʊtpeɪʃnt/','bệnh nhân ngoại trú','B2','n'],['inpatient','/ˈɪnpeɪʃnt/','bệnh nhân nội trú','B2','n'],['dosage','/ˈdoʊsɪdʒ/','liều lượng','B2','n'],['specimen','/ˈspesɪmən/','mẫu xét nghiệm','C1','n'],['epidemic','/ˌepɪˈdemɪk/','dịch bệnh','B2','n'],['pandemic','/pænˈdemɪk/','đại dịch','B2','n'],
['immune','/ɪˈmjuːn/','miễn dịch','B2','adj'],['allergy','/ˈælədʒi/','dị ứng','B1','n'],['fracture','/ˈfræktʃər/','gãy xương','B2','n'],['blood pressure','/blʌd ˈpreʃər/','huyết áp','B1','n'],['organ','/ˈɔːrɡən/','cơ quan, nội tạng','B1','n'],['transplant','/trænsˈplænt/','cấy ghép','B2','n'],['paramedic','/ˌpærəˈmedɪk/','nhân viên cấp cứu','B2','n'],['ward','/wɔːrd/','phòng bệnh, khoa','B1','n'],['nursing','/ˈnɜːrsɪŋ/','điều dưỡng','B1','n'],['clinic','/ˈklɪnɪk/','phòng khám','A2','n'],
// ═══════════ CHUYÊN NGÀNH: PHÁP LÝ (Legal) ═══════════
['plaintiff','/ˈpleɪntɪf/','nguyên đơn','C1','n'],['defendant','/dɪˈfendənt/','bị đơn','B2','n'],['verdict','/ˈvɜːrdɪkt/','phán quyết','B2','n'],['testimony','/ˈtestɪmoʊni/','lời khai','B2','n'],['jurisdiction','/ˌdʒʊrɪsˈdɪkʃn/','quyền tài phán','C1','n'],['legislation','/ˌledʒɪsˈleɪʃn/','pháp luật','B2','n'],['litigation','/ˌlɪtɪˈɡeɪʃn/','kiện tụng','C1','n'],['statute','/ˈstætʃuːt/','đạo luật','C1','n'],['acquittal','/əˈkwɪtl/','sự tha bổng','C1','n'],['prosecution','/ˌprɒsɪˈkjuːʃn/','truy tố','B2','n'],
['appeal','/əˈpiːl/','kháng cáo','B2','n'],['bail','/beɪl/','tiền bảo lãnh','B2','n'],['contract','/ˈkɒntrækt/','hợp đồng','B1','n'],['breach','/briːtʃ/','vi phạm','B2','n'],['liability','/ˌlaɪəˈbɪləti/','trách nhiệm pháp lý','B2','n'],['negligence','/ˈneɡlɪdʒəns/','sự cẩu thả','C1','n'],['arbitration','/ˌɑːrbɪˈtreɪʃn/','trọng tài','C1','n'],['comply','/kəmˈplaɪ/','tuân thủ','B2','v'],['amendment','/əˈmendmənt/','sửa đổi (luật)','B2','n'],['intellectual property','/ˌɪntəˈlektʃuəl ˈprɒpəti/','sở hữu trí tuệ','B2','n'],
// ═══════════ CHUYÊN NGÀNH: KINH DOANH & TÀI CHÍNH (Business & Finance) ═══════════
['revenue','/ˈrevənjuː/','doanh thu','B2','n'],['profit','/ˈprɒfɪt/','lợi nhuận','B1','n'],['investment','/ɪnˈvestmənt/','đầu tư','B1','n'],['shareholder','/ˈʃerhoʊldər/','cổ đông','B2','n'],['merger','/ˈmɜːrdʒər/','sáp nhập','C1','n'],['acquisition','/ˌækwɪˈzɪʃn/','mua lại','C1','n'],['dividend','/ˈdɪvɪdend/','cổ tức','C1','n'],['equity','/ˈekwəti/','vốn chủ sở hữu','C1','n'],['asset','/ˈæset/','tài sản','B2','n'],['liability','/ˌlaɪəˈbɪləti/','nợ phải trả','B2','n'],
['inflation','/ɪnˈfleɪʃn/','lạm phát','B2','n'],['recession','/rɪˈseʃn/','suy thoái','B2','n'],['bankruptcy','/ˈbæŋkrʌptsi/','phá sản','B2','n'],['entrepreneur','/ˌɒntrəprəˈnɜːr/','doanh nhân','B2','n'],['startup','/ˈstɑːrtʌp/','công ty khởi nghiệp','B1','n'],['marketing','/ˈmɑːrkɪtɪŋ/','tiếp thị','B1','n'],['supply chain','/səˈplaɪ tʃeɪn/','chuỗi cung ứng','B2','n'],['logistics','/ləˈdʒɪstɪks/','hậu cần','B2','n'],['wholesale','/ˈhoʊlseɪl/','bán buôn','B1','n'],['retail','/ˈriːteɪl/','bán lẻ','B1','n'],
['depreciation','/dɪˌpriːʃiˈeɪʃn/','khấu hao','C1','n'],['amortization','/əˌmɔːrtɪˈzeɪʃn/','phân bổ chi phí','C1','n'],['audit','/ˈɔːdɪt/','kiểm toán','B2','n'],['budget','/ˈbʌdʒɪt/','ngân sách','B1','n'],['forecast','/ˈfɔːrkæst/','dự báo','B2','n'],['stock','/stɒk/','cổ phiếu, kho','B1','n'],['bond','/bɒnd/','trái phiếu','B2','n'],['interest rate','/ˈɪntrəst reɪt/','lãi suất','B1','n'],['currency','/ˈkʌrənsi/','tiền tệ','B1','n'],['commodity','/kəˈmɒdəti/','hàng hóa','B2','n'],
// ═══════════ CHUYÊN NGÀNH: CÔNG NGHỆ THÔNG TIN (IT) ═══════════
['algorithm','/ˈælɡərɪðəm/','thuật toán','B2','n'],['database','/ˈdeɪtəbeɪs/','cơ sở dữ liệu','B1','n'],['server','/ˈsɜːrvər/','máy chủ','B1','n'],['bandwidth','/ˈbændwɪdθ/','băng thông','B2','n'],['encryption','/ɪnˈkrɪpʃn/','mã hóa','B2','n'],['authentication','/ɔːˌθentɪˈkeɪʃn/','xác thực','B2','n'],['interface','/ˈɪntərfeɪs/','giao diện','B1','n'],['repository','/rɪˈpɒzɪtəri/','kho lưu trữ','B2','n'],['debugging','/diːˈbʌɡɪŋ/','gỡ lỗi','B2','n'],['deployment','/dɪˈplɔɪmənt/','triển khai','B2','n'],
['scalability','/ˌskeɪləˈbɪləti/','khả năng mở rộng','C1','n'],['latency','/ˈleɪtənsi/','độ trễ','B2','n'],['middleware','/ˈmɪdlwer/','phần mềm trung gian','C1','n'],['microservice','/ˈmaɪkroʊˌsɜːrvɪs/','vi dịch vụ','C1','n'],['containerization','/kənˌteɪnəraɪˈzeɪʃn/','container hóa','C1','n'],['refactoring','/riːˈfæktərɪŋ/','tái cấu trúc code','B2','n'],['API','/ˌeɪpiːˈaɪ/','giao diện lập trình','B2','n'],['framework','/ˈfreɪmwɜːrk/','khung làm việc','B1','n'],['cloud computing','/klaʊd kəmˈpjuːtɪŋ/','điện toán đám mây','B2','n'],['cybersecurity','/ˌsaɪbərsɪˈkjʊrəti/','an ninh mạng','B2','n'],
['machine learning','/məˈʃiːn ˈlɜːrnɪŋ/','học máy','B2','n'],['artificial intelligence','/ˌɑːrtɪfɪʃl ɪnˈtelɪdʒəns/','trí tuệ nhân tạo','B2','n'],['blockchain','/ˈblɒktʃeɪn/','chuỗi khối','B2','n'],['firewall','/ˈfaɪərwɔːl/','tường lửa','B1','n'],['malware','/ˈmælwer/','phần mềm độc hại','B2','n'],['phishing','/ˈfɪʃɪŋ/','lừa đảo qua mạng','B2','n'],['DevOps','/ˈdevɒps/','vận hành phát triển','B2','n'],['agile','/ˈædʒaɪl/','phát triển linh hoạt','B2','adj'],['sprint','/sprɪnt/','chu kỳ phát triển','B2','n'],['pipeline','/ˈpaɪplaɪn/','quy trình tự động','B2','n'],
// ═══════════ CHUYÊN NGÀNH: KHOA HỌC (Science) ═══════════
['hypothesis','/haɪˈpɒθəsɪs/','giả thuyết','B2','n'],['experiment','/ɪkˈsperɪmənt/','thí nghiệm','B1','n'],['molecule','/ˈmɒlɪkjuːl/','phân tử','B2','n'],['atom','/ˈætəm/','nguyên tử','B1','n'],['enzyme','/ˈenzaɪm/','enzym','C1','n'],['photosynthesis','/ˌfoʊtoʊˈsɪnθəsɪs/','quang hợp','B2','n'],['ecosystem','/ˈiːkoʊsɪstəm/','hệ sinh thái','B2','n'],['biodiversity','/ˌbaɪoʊdaɪˈvɜːrsəti/','đa dạng sinh học','B2','n'],['chromosome','/ˈkroʊməsoʊm/','nhiễm sắc thể','C1','n'],['genome','/ˈdʒiːnoʊm/','bộ gen','C1','n'],
['climate change','/ˈklaɪmət tʃeɪndʒ/','biến đổi khí hậu','B1','n'],['renewable energy','/rɪˈnjuːəbl ˈenərdʒi/','năng lượng tái tạo','B2','n'],['carbon footprint','/ˈkɑːrbən ˈfʊtprɪnt/','dấu chân carbon','B2','n'],['sustainability','/səˌsteɪnəˈbɪləti/','tính bền vững','B2','n'],['specimen','/ˈspesɪmən/','mẫu vật','B2','n'],['catalyst','/ˈkætəlɪst/','chất xúc tác','C1','n'],['gravity','/ˈɡrævəti/','trọng lực','B1','n'],['velocity','/vəˈlɒsəti/','vận tốc','B2','n'],['radiation','/ˌreɪdiˈeɪʃn/','bức xạ','B2','n'],['nucleus','/ˈnjuːkliəs/','hạt nhân','C1','n'],
// ═══════════ CHUYÊN NGÀNH: GIÁO DỤC (Education) ═══════════
['curriculum','/kəˈrɪkjələm/','chương trình học','B2','n'],['syllabus','/ˈsɪləbəs/','đề cương môn học','B2','n'],['enrollment','/ɪnˈroʊlmənt/','ghi danh','B2','n'],['tuition','/tjuːˈɪʃn/','học phí','B1','n'],['scholarship','/ˈskɒlərʃɪp/','học bổng','B1','n'],['dissertation','/ˌdɪsərˈteɪʃn/','luận văn','C1','n'],['seminar','/ˈsemɪnɑːr/','hội thảo chuyên đề','B2','n'],['pedagogy','/ˈpedəɡɒdʒi/','phương pháp sư phạm','C1','n'],['assessment','/əˈsesmənt/','đánh giá','B2','n'],['accreditation','/əˌkredɪˈteɪʃn/','kiểm định chất lượng','C1','n'],
['extracurricular','/ˌekstrəkəˈrɪkjələr/','ngoại khóa','B2','adj'],['plagiarism','/ˈpleɪdʒərɪzəm/','đạo văn','B2','n'],['thesis','/ˈθiːsɪs/','luận điểm','B2','n'],['undergraduate','/ˌʌndərˈɡrædʒuət/','sinh viên đại học','B2','n'],['postgraduate','/ˌpoʊstˈɡrædʒuət/','sau đại học','B2','n'],['lecture','/ˈlektʃər/','bài giảng','B1','n'],['faculty','/ˈfækəlti/','khoa, ban','B2','n'],['dean','/diːn/','trưởng khoa','B2','n'],['alumni','/əˈlʌmnaɪ/','cựu sinh viên','B2','n'],['literacy','/ˈlɪtərəsi/','khả năng đọc viết','B2','n'],
// ═══════════ CHUYÊN NGÀNH: TÂM LÝ HỌC (Psychology) ═══════════
['cognition','/kɒɡˈnɪʃn/','nhận thức','C1','n'],['consciousness','/ˈkɒnʃəsnəs/','ý thức','B2','n'],['anxiety','/æŋˈzaɪəti/','lo âu','B2','n'],['depression','/dɪˈpreʃn/','trầm cảm','B2','n'],['trauma','/ˈtrɔːmə/','chấn thương tâm lý','B2','n'],['empathy','/ˈempəθi/','sự đồng cảm','B2','n'],['perception','/pərˈsepʃn/','nhận thức, tri giác','B2','n'],['stimulus','/ˈstɪmjələs/','kích thích','C1','n'],['motivation','/ˌmoʊtɪˈveɪʃn/','động lực','B1','n'],['introvert','/ˈɪntrəvɜːrt/','hướng nội','B2','n'],
['extrovert','/ˈekstrəvɜːrt/','hướng ngoại','B2','n'],['phobia','/ˈfoʊbiə/','ám ảnh sợ hãi','B2','n'],['obsession','/əbˈseʃn/','ám ảnh','B2','n'],['subconscious','/sʌbˈkɒnʃəs/','tiềm thức','B2','adj'],['mindfulness','/ˈmaɪndfəlnəs/','chánh niệm','B2','n'],['resilience','/rɪˈzɪliəns/','khả năng phục hồi','B2','n'],['self-esteem','/self ɪˈstiːm/','lòng tự trọng','B2','n'],['burnout','/ˈbɜːrnaʊt/','kiệt sức nghề nghiệp','B2','n'],['neuroscience','/ˈnjʊroʊsaɪəns/','khoa học thần kinh','C1','n'],['psychotherapy','/ˌsaɪkoʊˈθerəpi/','tâm lý trị liệu','C1','n'],
// ═══════════ CHUYÊN NGÀNH: KIẾN TRÚC & XÂY DỰNG (Architecture & Construction) ═══════════
['blueprint','/ˈbluːprɪnt/','bản thiết kế','B2','n'],['foundation','/faʊnˈdeɪʃn/','nền móng','B1','n'],['scaffolding','/ˈskæfəldɪŋ/','giàn giáo','B2','n'],['renovation','/ˌrenəˈveɪʃn/','cải tạo','B2','n'],['contractor','/ˈkɒntræktər/','nhà thầu','B2','n'],['insulation','/ˌɪnsəˈleɪʃn/','cách nhiệt','B2','n'],['demolition','/ˌdeməˈlɪʃn/','phá dỡ','C1','n'],['facade','/fəˈsɑːd/','mặt tiền','C1','n'],['cantilever','/ˈkæntɪliːvər/','công-xôn, cánh hẫng','C1','n'],['load-bearing','/loʊd ˈberɪŋ/','chịu lực','B2','adj'],
['ventilation','/ˌventɪˈleɪʃn/','thông gió','B2','n'],['beam','/biːm/','dầm','B1','n'],['column','/ˈkɒləm/','cột','B1','n'],['concrete','/ˈkɒŋkriːt/','bê tông','B1','n'],['reinforcement','/ˌriːɪnˈfɔːrsmənt/','cốt thép','B2','n'],['plumbing','/ˈplʌmɪŋ/','hệ thống ống nước','B2','n'],['drainage','/ˈdreɪnɪdʒ/','thoát nước','B2','n'],['zoning','/ˈzoʊnɪŋ/','quy hoạch','B2','n'],['elevation','/ˌelɪˈveɪʃn/','mặt đứng','B2','n'],['sustainability','/səˌsteɪnəˈbɪləti/','bền vững','B2','n'],
// ═══════════ CHUYÊN NGÀNH: BÁO CHÍ & TRUYỀN THÔNG (Journalism & Media) ═══════════
['headline','/ˈhedlaɪn/','tiêu đề báo','B1','n'],['editorial','/ˌedɪˈtɔːriəl/','bài xã luận','B2','n'],['correspondent','/ˌkɒrəˈspɒndənt/','phóng viên thường trú','B2','n'],['broadcast','/ˈbrɔːdkæst/','phát sóng','B1','v'],['exclusive','/ɪkˈskluːsɪv/','tin độc quyền','B2','adj'],['press release','/pres rɪˈliːs/','thông cáo báo chí','B2','n'],['censorship','/ˈsensərʃɪp/','kiểm duyệt','B2','n'],['propaganda','/ˌprɒpəˈɡændə/','tuyên truyền','B2','n'],['paparazzi','/ˌpæpəˈrætsi/','thợ ảnh săn sao','B2','n'],['tabloid','/ˈtæblɔɪd/','báo lá cải','B2','n'],
['anchor','/ˈæŋkər/','người dẫn chương trình','B2','n'],['byline','/ˈbaɪlaɪn/','tên tác giả bài báo','C1','n'],['circulation','/ˌsɜːrkjəˈleɪʃn/','số phát hành','B2','n'],['defamation','/ˌdefəˈmeɪʃn/','phỉ báng','C1','n'],['investigative','/ɪnˈvestɪɡeɪtɪv/','điều tra','B2','adj'],['scoop','/skuːp/','tin nóng độc quyền','B2','n'],['source','/sɔːrs/','nguồn tin','B1','n'],['bias','/ˈbaɪəs/','thiên kiến','B2','n'],['podcast','/ˈpɒdkæst/','podcast','B1','n'],['viral','/ˈvaɪrəl/','lan truyền','B1','adj'],
// ═══════════ CHUYÊN NGÀNH: HÀNG KHÔNG (Aviation) ═══════════
['fuselage','/ˈfjuːzəlɑːʒ/','thân máy bay','C1','n'],['cockpit','/ˈkɒkpɪt/','buồng lái','B2','n'],['turbulence','/ˈtɜːrbjələns/','nhiễu loạn khí quyển','B2','n'],['altitude','/ˈæltɪtjuːd/','độ cao','B2','n'],['runway','/ˈrʌnweɪ/','đường băng','B1','n'],['taxiway','/ˈtæksiweɪ/','đường lăn','C1','n'],['aviation','/ˌeɪviˈeɪʃn/','hàng không','B2','n'],['navigator','/ˈnævɪɡeɪtər/','hoa tiêu','B2','n'],['autopilot','/ˈɔːtoʊpaɪlət/','lái tự động','B2','n'],['departure','/dɪˈpɑːrtʃər/','khởi hành','B1','n'],
['boarding','/ˈbɔːrdɪŋ/','lên máy bay','A2','n'],['layover','/ˈleɪoʊvər/','quá cảnh','B2','n'],['cargo','/ˈkɑːrɡoʊ/','hàng hóa vận chuyển','B2','n'],['hangar','/ˈhæŋər/','nhà chứa máy bay','C1','n'],['jet lag','/dʒet læɡ/','lệch múi giờ','B1','n'],['mayday','/ˈmeɪdeɪ/','tín hiệu cấp cứu','B2','n'],['airspace','/ˈerˌspeɪs/','không phận','B2','n'],['flight attendant','/flaɪt əˈtendənt/','tiếp viên hàng không','A2','n'],['terminal','/ˈtɜːrmɪnl/','nhà ga','B1','n'],['captain','/ˈkæptɪn/','cơ trưởng','B1','n'],
// ═══════════ CHUYÊN NGÀNH: NHÁCH & DU LỊCH (Hospitality & Tourism) ═══════════
['accommodation','/əˌkɒməˈdeɪʃn/','chỗ ở','B1','n'],['hospitality','/ˌhɒspɪˈtæləti/','ngành khách sạn','B2','n'],['concierge','/ˌkɒnsiˈerʒ/','nhân viên lễ tân','B2','n'],['itinerary','/aɪˈtɪnəreri/','lịch trình','B2','n'],['excursion','/ɪkˈskɜːrʒn/','chuyến tham quan','B2','n'],['amenity','/əˈmenəti/','tiện nghi','B2','n'],['reservation','/ˌrezərˈveɪʃn/','đặt phòng/bàn','B1','n'],['check-in','/ˈtʃekɪn/','nhận phòng','A2','n'],['check-out','/ˈtʃekaʊt/','trả phòng','A2','n'],['suite','/swiːt/','phòng hạng sang','B2','n'],
['buffet','/bəˈfeɪ/','tiệc tự chọn','B1','n'],['cuisine','/kwɪˈziːn/','ẩm thực','B2','n'],['souvenir','/ˌsuːvəˈnɪr/','quà lưu niệm','B1','n'],['tourist attraction','/ˈtʊrɪst əˈtrækʃn/','điểm du lịch','B1','n'],['heritage','/ˈherɪtɪdʒ/','di sản','B2','n'],['landmark','/ˈlændmɑːrk/','danh thắng','B1','n'],['passport','/ˈpæspɔːrt/','hộ chiếu','A2','n'],['customs','/ˈkʌstəmz/','hải quan','B1','n'],['immigration','/ˌɪmɪˈɡreɪʃn/','nhập cảnh','B1','n'],['visa','/ˈviːzə/','thị thực','A2','n'],
// ═══════════ CHUYÊN NGÀNH: NÔNG NGHIỆP (Agriculture) ═══════════
['harvest','/ˈhɑːrvɪst/','thu hoạch','B1','n'],['irrigation','/ˌɪrɪˈɡeɪʃn/','tưới tiêu','B2','n'],['fertilizer','/ˈfɜːrtɪlaɪzər/','phân bón','B2','n'],['pesticide','/ˈpestɪsaɪd/','thuốc trừ sâu','B2','n'],['livestock','/ˈlaɪvstɒk/','gia súc','B2','n'],['organic','/ɔːrˈɡænɪk/','hữu cơ','B1','adj'],['crop','/krɒp/','vụ mùa, cây trồng','B1','n'],['drought','/draʊt/','hạn hán','B2','n'],['soil','/sɔɪl/','đất','B1','n'],['yield','/jiːld/','sản lượng','B2','n'],
['plantation','/plænˈteɪʃn/','đồn điền','B2','n'],['greenhouse','/ˈɡriːnhaʊs/','nhà kính','B1','n'],['poultry','/ˈpoʊltri/','gia cầm','B2','n'],['aquaculture','/ˈækwəkʌltʃər/','nuôi trồng thủy sản','C1','n'],['genetically modified','/dʒəˈnetɪkli ˈmɒdɪfaɪd/','biến đổi gen','B2','adj'],['subsistence','/səbˈsɪstəns/','tự cung tự cấp','C1','n'],['famine','/ˈfæmɪn/','nạn đói','B2','n'],['arable','/ˈærəbl/','có thể canh tác','C1','adj'],['horticulture','/ˈhɔːrtɪkʌltʃər/','làm vườn','C1','n'],['erosion','/ɪˈroʊʒn/','xói mòn','B2','n'],
// ═══════════ CHUYÊN NGÀNH: QUẢNG CÁO & MARKETING (Advertising & Marketing) ═══════════
['branding','/ˈbrændɪŋ/','xây dựng thương hiệu','B2','n'],['campaign','/kæmˈpeɪn/','chiến dịch','B1','n'],['target audience','/ˈtɑːrɡɪt ˈɔːdiəns/','đối tượng mục tiêu','B2','n'],['conversion','/kənˈvɜːrʒn/','chuyển đổi','B2','n'],['engagement','/ɪnˈɡeɪdʒmənt/','tương tác','B2','n'],['influencer','/ˈɪnfluənsər/','người có ảnh hưởng','B1','n'],['SEO','/ˌesˌiːˈoʊ/','tối ưu công cụ tìm kiếm','B2','n'],['analytics','/ˌænəˈlɪtɪks/','phân tích dữ liệu','B2','n'],['ROI','/ˌɑːrˌoʊˈaɪ/','lợi tức đầu tư','B2','n'],['KPI','/ˌkeɪˌpiːˈaɪ/','chỉ số hiệu suất','B2','n'],
['slogan','/ˈsloʊɡən/','khẩu hiệu','B1','n'],['testimonial','/ˌtestɪˈmoʊniəl/','lời chứng thực','B2','n'],['demographic','/ˌdeməˈɡræfɪk/','nhân khẩu học','B2','adj'],['billboard','/ˈbɪlbɔːrd/','biển quảng cáo','B1','n'],['sponsor','/ˈspɒnsər/','nhà tài trợ','B1','n'],['endorsement','/ɪnˈdɔːrsmənt/','sự bảo chứng','B2','n'],['merchandise','/ˈmɜːrtʃəndaɪz/','hàng hóa thương mại','B2','n'],['niche','/niːʃ/','thị trường ngách','B2','n'],['outreach','/ˈaʊtriːtʃ/','tiếp cận cộng đồng','B2','n'],['rebrand','/riːˈbrænd/','tái xây dựng thương hiệu','B2','v'],
// ═══════════ CHUYÊN NGÀNH: VẬN TẢI & LOGISTICS (Transport & Logistics) ═══════════
['freight','/freɪt/','vận chuyển hàng hóa','B2','n'],['warehouse','/ˈwerhaʊs/','kho hàng','B1','n'],['inventory','/ˈɪnvəntɔːri/','hàng tồn kho','B2','n'],['shipment','/ˈʃɪpmənt/','lô hàng','B2','n'],['dispatch','/dɪˈspætʃ/','gửi đi, điều phối','B2','v'],['procurement','/prəˈkjʊrmənt/','thu mua','C1','n'],['consignment','/kənˈsaɪnmənt/','lô hàng ký gửi','C1','n'],['tariff','/ˈtærɪf/','thuế quan','B2','n'],['customs clearance','/ˈkʌstəmz ˈklɪrəns/','thông quan','B2','n'],['bill of lading','/bɪl əv ˈleɪdɪŋ/','vận đơn','C1','n'],
['distribution','/ˌdɪstrɪˈbjuːʃn/','phân phối','B2','n'],['tracking','/ˈtrækɪŋ/','theo dõi đơn hàng','B1','n'],['transit','/ˈtrænzɪt/','quá cảnh','B2','n'],['container','/kənˈteɪnər/','container','B1','n'],['forklift','/ˈfɔːrklɪft/','xe nâng','B2','n'],['pallet','/ˈpælɪt/','pallet gỗ','B2','n'],['bulk','/bʌlk/','số lượng lớn','B2','n'],['lead time','/liːd taɪm/','thời gian giao hàng','B2','n'],['outsourcing','/ˈaʊtsɔːrsɪŋ/','thuê ngoài','B2','n'],['fleet','/fliːt/','đội xe/tàu','B2','n'],
// ═══════════ CHUYÊN NGÀNH: MÔI TRƯỜNG (Environment) ═══════════
['pollution','/pəˈluːʃn/','ô nhiễm','B1','n'],['deforestation','/diːˌfɒrɪˈsteɪʃn/','phá rừng','B2','n'],['conservation','/ˌkɒnsərˈveɪʃn/','bảo tồn','B2','n'],['emission','/ɪˈmɪʃn/','khí thải','B2','n'],['fossil fuel','/ˈfɒsl fjuːəl/','nhiên liệu hóa thạch','B2','n'],['recycling','/riːˈsaɪklɪŋ/','tái chế','B1','n'],['ozone layer','/ˈoʊzoʊn ˈleɪər/','tầng ozon','B2','n'],['endangered species','/ɪnˈdeɪndʒərd ˈspiːʃiːz/','loài có nguy cơ tuyệt chủng','B2','n'],['habitat','/ˈhæbɪtæt/','môi trường sống','B2','n'],['carbon neutral','/ˈkɑːrbən ˈnjuːtrəl/','trung hòa carbon','B2','adj'],
['greenhouse effect','/ˈɡriːnhaʊs ɪˈfekt/','hiệu ứng nhà kính','B2','n'],['waste management','/weɪst ˈmænɪdʒmənt/','quản lý chất thải','B2','n'],['sustainable development','/səˈsteɪnəbl dɪˈveləpmənt/','phát triển bền vững','B2','n'],['biodegradable','/ˌbaɪoʊdɪˈɡreɪdəbl/','có thể phân hủy sinh học','B2','adj'],['reforestation','/ˌriːfɒrɪˈsteɪʃn/','trồng rừng lại','B2','n'],['toxic waste','/ˈtɒksɪk weɪst/','chất thải độc hại','B2','n'],['solar panel','/ˈsoʊlər ˈpænl/','tấm pin mặt trời','B1','n'],['wind turbine','/wɪnd ˈtɜːrbaɪn/','tuabin gió','B2','n'],['ecological','/ˌiːkəˈlɒdʒɪkl/','sinh thái','B2','adj'],['contamination','/kənˌtæmɪˈneɪʃn/','sự nhiễm bẩn','B2','n'],
// ═══════════ KẾ TOÁN (Accounting) ═══════════
['ledger','/ˈledʒər/','sổ cái','B2','n'],['accounts payable','/əˈkaʊnts ˈpeɪəbl/','khoản phải trả','B2','n'],['accounts receivable','/əˈkaʊnts rɪˈsiːvəbl/','khoản phải thu','B2','n'],['balance sheet','/ˈbæləns ʃiːt/','bảng cân đối kế toán','B2','n'],['cash flow','/kæʃ floʊ/','dòng tiền','B2','n'],['tax return','/tæks rɪˈtɜːrn/','tờ khai thuế','B2','n'],['bookkeeping','/ˈbʊkkiːpɪŋ/','ghi sổ kế toán','B2','n'],['fiscal year','/ˈfɪskl jɪr/','năm tài chính','B2','n'],['gross income','/ɡroʊs ˈɪnkʌm/','thu nhập gộp','B2','n'],['net income','/net ˈɪnkʌm/','thu nhập ròng','B2','n'],
// ═══════════ NGÂN HÀNG (Banking) ═══════════
['mortgage','/ˈmɔːrɡɪdʒ/','thế chấp','B2','n'],['loan','/loʊn/','khoản vay','B1','n'],['deposit','/dɪˈpɒzɪt/','tiền gửi','B1','n'],['withdrawal','/wɪðˈdrɔːəl/','rút tiền','B2','n'],['savings account','/ˈseɪvɪŋz əˈkaʊnt/','tài khoản tiết kiệm','B1','n'],['credit score','/ˈkredɪt skɔːr/','điểm tín dụng','B2','n'],['collateral','/kəˈlætərəl/','tài sản thế chấp','C1','n'],['liquidity','/lɪˈkwɪdəti/','tính thanh khoản','C1','n'],['transaction','/trænˈzækʃn/','giao dịch','B1','n'],['exchange rate','/ɪksˈtʃeɪndʒ reɪt/','tỷ giá hối đoái','B2','n'],
// ═══════════ QUẢN TRỊ NHÂN SỰ (Human Resources) ═══════════
['recruitment','/rɪˈkruːtmənt/','tuyển dụng','B2','n'],['onboarding','/ˈɒnbɔːrdɪŋ/','đào tạo hội nhập','B2','n'],['payroll','/ˈpeɪroʊl/','bảng lương','B2','n'],['appraisal','/əˈpreɪzl/','đánh giá hiệu suất','B2','n'],['severance','/ˈsevərəns/','trợ cấp thôi việc','C1','n'],['turnover','/ˈtɜːrnoʊvər/','tỷ lệ nghỉ việc','B2','n'],['workforce','/ˈwɜːrkfɔːrs/','lực lượng lao động','B2','n'],['compensation','/ˌkɒmpənˈseɪʃn/','đãi ngộ','B2','n'],['probation','/proʊˈbeɪʃn/','thử việc','B2','n'],['headhunter','/ˈhedˌhʌntər/','tuyển dụng cấp cao','B2','n'],
// ═══════════ QUAN HỆ QUỐC TẾ (International Relations) ═══════════
['diplomacy','/dɪˈploʊməsi/','ngoại giao','B2','n'],['sovereignty','/ˈsɒvrənti/','chủ quyền','C1','n'],['treaty','/ˈtriːti/','hiệp ước','B2','n'],['embargo','/ɪmˈbɑːrɡoʊ/','cấm vận','C1','n'],['sanction','/ˈsæŋkʃn/','trừng phạt','B2','n'],['alliance','/əˈlaɪəns/','liên minh','B2','n'],['geopolitics','/ˌdʒiːoʊˈpɒlɪtɪks/','địa chính trị','C1','n'],['asylum','/əˈsaɪləm/','tị nạn','B2','n'],['multilateral','/ˌmʌltɪˈlætərəl/','đa phương','C1','adj'],['ratification','/ˌrætɪfɪˈkeɪʃn/','phê chuẩn','C1','n'],
// ═══════════ XÃ HỘI HỌC (Sociology) ═══════════
['stratification','/ˌstrætɪfɪˈkeɪʃn/','phân tầng xã hội','C1','n'],['urbanization','/ˌɜːrbənɪˈzeɪʃn/','đô thị hóa','B2','n'],['inequality','/ˌɪnɪˈkwɒləti/','bất bình đẳng','B2','n'],['migration','/maɪˈɡreɪʃn/','di cư','B2','n'],['stereotype','/ˈsteriətaɪp/','định kiến','B2','n'],['assimilation','/əˌsɪmɪˈleɪʃn/','đồng hóa','C1','n'],['ethnicity','/eθˈnɪsəti/','dân tộc','B2','n'],['welfare','/ˈwelfer/','phúc lợi','B2','n'],['norm','/nɔːrm/','chuẩn mực','B2','n'],['deviance','/ˈdiːviəns/','lệch chuẩn','C1','n'],
// ═══════════ CƠ KHÍ (Mechanical Engineering) ═══════════
['torque','/tɔːrk/','mô-men xoắn','B2','n'],['friction','/ˈfrɪkʃn/','ma sát','B2','n'],['hydraulic','/haɪˈdrɔːlɪk/','thủy lực','B2','adj'],['turbine','/ˈtɜːrbaɪn/','tuabin','B2','n'],['piston','/ˈpɪstən/','pít-tông','B2','n'],['bearing','/ˈberɪŋ/','ổ trục','B2','n'],['welding','/ˈweldɪŋ/','hàn','B2','n'],['assembly','/əˈsembli/','lắp ráp','B2','n'],['alloy','/ˈælɔɪ/','hợp kim','B2','n'],['corrosion','/kəˈroʊʒn/','ăn mòn','B2','n'],
// ═══════════ ĐIỆN - ĐIỆN TỬ (Electrical Engineering) ═══════════
['circuit','/ˈsɜːrkɪt/','mạch điện','B2','n'],['voltage','/ˈvoʊltɪdʒ/','điện áp','B2','n'],['current','/ˈkʌrənt/','dòng điện','B2','n'],['resistor','/rɪˈzɪstər/','điện trở','B2','n'],['capacitor','/kəˈpæsɪtər/','tụ điện','C1','n'],['semiconductor','/ˌsemikənˈdʌktər/','bán dẫn','B2','n'],['transistor','/trænˈzɪstər/','bóng bán dẫn','C1','n'],['diode','/ˈdaɪoʊd/','đi-ốt','C1','n'],['transformer','/trænsˈfɔːrmər/','máy biến áp','B2','n'],['wattage','/ˈwɒtɪdʒ/','công suất','B2','n'],
// ═══════════ HÓA HỌC (Chemistry) ═══════════
['compound','/ˈkɒmpaʊnd/','hợp chất','B2','n'],['element','/ˈelɪmənt/','nguyên tố','B1','n'],['reaction','/riˈækʃn/','phản ứng','B1','n'],['solution','/səˈluːʃn/','dung dịch','B1','n'],['acid','/ˈæsɪd/','axit','B1','n'],['alkaline','/ˈælkəlaɪn/','kiềm','B2','adj'],['concentration','/ˌkɒnsnˈtreɪʃn/','nồng độ','B2','n'],['distillation','/ˌdɪstɪˈleɪʃn/','chưng cất','C1','n'],['oxidation','/ˌɒksɪˈdeɪʃn/','oxy hóa','C1','n'],['polymer','/ˈpɒlɪmər/','polyme','C1','n'],
// ═══════════ SINH HỌC (Biology) ═══════════
['cell','/sel/','tế bào','B1','n'],['organism','/ˈɔːrɡənɪzəm/','sinh vật','B2','n'],['genetics','/dʒəˈnetɪks/','di truyền học','B2','n'],['mutation','/mjuːˈteɪʃn/','đột biến','B2','n'],['evolution','/ˌiːvəˈluːʃn/','tiến hóa','B2','n'],['species','/ˈspiːʃiːz/','loài','B1','n'],['metabolism','/məˈtæbəlɪzəm/','trao đổi chất','B2','n'],['mitosis','/maɪˈtoʊsɪs/','nguyên phân','C1','n'],['protein','/ˈproʊtiːn/','protein','B1','n'],['microorganism','/ˌmaɪkroʊˈɔːrɡənɪzəm/','vi sinh vật','B2','n'],
// ═══════════ TOÁN HỌC (Mathematics) ═══════════
['equation','/ɪˈkweɪʒn/','phương trình','B1','n'],['variable','/ˈveriəbl/','biến số','B2','n'],['theorem','/ˈθɪərəm/','định lý','B2','n'],['integral','/ˈɪntɪɡrəl/','tích phân','C1','n'],['derivative','/dɪˈrɪvətɪv/','đạo hàm','C1','n'],['probability','/ˌprɒbəˈbɪləti/','xác suất','B2','n'],['statistics','/stəˈtɪstɪks/','thống kê','B1','n'],['matrix','/ˈmeɪtrɪks/','ma trận','B2','n'],['coefficient','/ˌkoʊɪˈfɪʃnt/','hệ số','C1','n'],['logarithm','/ˈlɒɡərɪðəm/','logarit','C1','n'],
// ═══════════ DƯỢC HỌC (Pharmacy) ═══════════
['pharmaceutical','/ˌfɑːrməˈsjuːtɪkl/','dược phẩm','B2','adj'],['dosage','/ˈdoʊsɪdʒ/','liều dùng','B2','n'],['side effect','/saɪd ɪˈfekt/','tác dụng phụ','B1','n'],['generic drug','/dʒəˈnerɪk drʌɡ/','thuốc gốc','B2','n'],['over-the-counter','/ˌoʊvər ðə ˈkaʊntər/','thuốc không kê đơn','B2','adj'],['clinical trial','/ˈklɪnɪkl ˈtraɪəl/','thử nghiệm lâm sàng','B2','n'],['pharmacology','/ˌfɑːrməˈkɒlədʒi/','dược lý học','C1','n'],['toxicology','/ˌtɒksɪˈkɒlədʒi/','độc chất học','C1','n'],['tablet','/ˈtæblɪt/','viên thuốc','B1','n'],['capsule','/ˈkæpsjuːl/','viên nang','B2','n'],
// ═══════════ NHA KHOA (Dentistry) ═══════════
['cavity','/ˈkævəti/','lỗ sâu răng','B2','n'],['crown','/kraʊn/','mão răng','B2','n'],['orthodontics','/ˌɔːrθoʊˈdɒntɪks/','chỉnh nha','C1','n'],['implant','/ˈɪmplænt/','răng cấy ghép','B2','n'],['extraction','/ɪkˈstrækʃn/','nhổ răng','B2','n'],['plaque','/plæk/','mảng bám','B2','n'],['dental floss','/ˈdentl flɒs/','chỉ nha khoa','B1','n'],['filling','/ˈfɪlɪŋ/','trám răng','B2','n'],['gum disease','/ɡʌm dɪˈziːz/','bệnh nướu','B2','n'],['enamel','/ɪˈnæml/','men răng','B2','n'],
// ═══════════ THÚ Y (Veterinary) ═══════════
['veterinarian','/ˌvetərɪˈneriən/','bác sĩ thú y','B2','n'],['vaccination','/ˌvæksɪˈneɪʃn/','tiêm phòng','B1','n'],['parasite','/ˈpærəsaɪt/','ký sinh trùng','B2','n'],['quarantine','/ˈkwɒrəntiːn/','cách ly','B2','n'],['breeding','/ˈbriːdɪŋ/','nhân giống','B2','n'],['neutering','/ˈnjuːtərɪŋ/','triệt sản','C1','n'],['rabies','/ˈreɪbiːz/','bệnh dại','B2','n'],['kennel','/ˈkenl/','chuồng chó','B2','n'],['stethoscope','/ˈsteθəskoʊp/','ống nghe','B2','n'],['zoonotic','/ˌzoʊəˈnɒtɪk/','lây từ động vật','C1','adj'],
// ═══════════ CÔNG NGHỆ THỰC PHẨM (Food Technology) ═══════════
['pasteurization','/ˌpæstʃərɪˈzeɪʃn/','tiệt trùng','C1','n'],['fermentation','/ˌfɜːrmenˈteɪʃn/','lên men','B2','n'],['preservative','/prɪˈzɜːrvətɪv/','chất bảo quản','B2','n'],['additive','/ˈædɪtɪv/','phụ gia','B2','n'],['shelf life','/ʃelf laɪf/','hạn sử dụng','B2','n'],['nutrition','/njuːˈtrɪʃn/','dinh dưỡng','B1','n'],['contamination','/kənˌtæmɪˈneɪʃn/','nhiễm bẩn','B2','n'],['processing','/ˈprɒsesɪŋ/','chế biến','B2','n'],['packaging','/ˈpækɪdʒɪŋ/','bao bì','B1','n'],['calorie','/ˈkæləri/','calo','B1','n'],
// ═══════════ DỆT MAY (Textile) ═══════════
['fabric','/ˈfæbrɪk/','vải','B1','n'],['thread','/θred/','sợi chỉ','B1','n'],['weaving','/ˈwiːvɪŋ/','dệt','B2','n'],['garment','/ˈɡɑːrmənt/','hàng may mặc','B2','n'],['pattern','/ˈpætərn/','mẫu, rập','B1','n'],['dyeing','/ˈdaɪɪŋ/','nhuộm','B2','n'],['embroidery','/ɪmˈbrɔɪdəri/','thêu','B2','n'],['synthetic','/sɪnˈθetɪk/','tổng hợp','B2','adj'],['tailoring','/ˈteɪlərɪŋ/','may đo','B2','n'],['seam','/siːm/','đường may','B2','n'],
// ═══════════ BẤT ĐỘNG SẢN (Real Estate) ═══════════
['property','/ˈprɒpərti/','bất động sản','B1','n'],['lease','/liːs/','hợp đồng thuê','B2','n'],['tenant','/ˈtenənt/','người thuê','B2','n'],['landlord','/ˈlændlɔːrd/','chủ nhà','B2','n'],['valuation','/ˌvæljuˈeɪʃn/','định giá','B2','n'],['foreclosure','/fɔːrˈkloʊʒər/','tịch thu tài sản','C1','n'],['appraisal','/əˈpreɪzl/','thẩm định giá','B2','n'],['zoning','/ˈzoʊnɪŋ/','quy hoạch đất','B2','n'],['deed','/diːd/','giấy chứng nhận quyền sở hữu','C1','n'],['equity','/ˈekwəti/','giá trị sở hữu thực','B2','n'],
// ═══════════ MỸ THUẬT & THIẾT KẾ (Art & Design) ═══════════
['canvas','/ˈkænvəs/','toan vẽ','B2','n'],['palette','/ˈpælɪt/','bảng màu','B2','n'],['composition','/ˌkɒmpəˈzɪʃn/','bố cục','B2','n'],['perspective','/pərˈspektɪv/','phối cảnh','B2','n'],['sculpture','/ˈskʌlptʃər/','điêu khắc','B2','n'],['typography','/taɪˈpɒɡrəfi/','kiểu chữ','B2','n'],['illustration','/ˌɪləˈstreɪʃn/','minh họa','B2','n'],['portfolio','/pɔːrtˈfoʊlioʊ/','hồ sơ tác phẩm','B2','n'],['aesthetic','/esˈθetɪk/','thẩm mỹ','B2','adj'],['sketch','/sketʃ/','phác thảo','B1','n'],
// ═══════════ NGÔN NGỮ HỌC (Linguistics) ═══════════
['phonetics','/fəˈnetɪks/','ngữ âm học','B2','n'],['syntax','/ˈsɪntæks/','cú pháp','C1','n'],['morphology','/mɔːrˈfɒlədʒi/','hình thái học','C1','n'],['semantics','/sɪˈmæntɪks/','ngữ nghĩa học','C1','n'],['pragmatics','/præɡˈmætɪks/','ngữ dụng học','C1','n'],['dialect','/ˈdaɪəlekt/','phương ngữ','B2','n'],['bilingual','/baɪˈlɪŋɡwəl/','song ngữ','B2','adj'],['acquisition','/ˌækwɪˈzɪʃn/','thụ đắc ngôn ngữ','B2','n'],['fluency','/ˈfluːənsi/','lưu loát','B2','n'],['intonation','/ˌɪntəˈneɪʃn/','ngữ điệu','B2','n'],
// ═══════════ TRIẾT HỌC (Philosophy) ═══════════
['epistemology','/ɪˌpɪstəˈmɒlədʒi/','nhận thức luận','C2','n'],['ontology','/ɒnˈtɒlədʒi/','bản thể luận','C2','n'],['ethics','/ˈeθɪks/','đạo đức học','B2','n'],['logic','/ˈlɒdʒɪk/','logic học','B1','n'],['existentialism','/ˌeɡzɪˈstenʃəlɪzəm/','chủ nghĩa hiện sinh','C1','n'],['metaphysics','/ˌmetəˈfɪzɪks/','siêu hình học','C1','n'],['utilitarianism','/ˌjuːtɪlɪˈteriənɪzəm/','chủ nghĩa vị lợi','C1','n'],['paradox','/ˈpærədɒks/','nghịch lý','B2','n'],['dogma','/ˈdɒɡmə/','giáo điều','C1','n'],['skepticism','/ˈskeptɪsɪzəm/','chủ nghĩa hoài nghi','C1','n'],
// ═══════════ THỂ DỤC THỂ THAO (Sports Science) ═══════════
['endurance','/ɪnˈdjʊrəns/','sức bền','B2','n'],['stamina','/ˈstæmɪnə/','thể lực','B2','n'],['metabolism','/məˈtæbəlɪzəm/','trao đổi chất','B2','n'],['rehabilitation','/ˌriːhəˌbɪlɪˈteɪʃn/','phục hồi chấn thương','B2','n'],['aerobic','/eˈroʊbɪk/','có oxy','B2','adj'],['anaerobic','/ˌænəˈroʊbɪk/','yếm khí','C1','adj'],['physiology','/ˌfɪziˈɒlədʒi/','sinh lý học','C1','n'],['kinesiology','/kɪˌniːsiˈɒlədʒi/','vận động học','C1','n'],['doping','/ˈdoʊpɪŋ/','sử dụng chất cấm','B2','n'],['sportsmanship','/ˈspɔːrtsmənʃɪp/','tinh thần thể thao','B2','n'],
// ═══════════ ĐỊA CHẤT (Geology) ═══════════
['mineral','/ˈmɪnərəl/','khoáng vật','B1','n'],['sediment','/ˈsedɪmənt/','trầm tích','B2','n'],['tectonic','/tekˈtɒnɪk/','kiến tạo','C1','adj'],['volcanic','/vɒlˈkænɪk/','núi lửa','B2','adj'],['fossil','/ˈfɒsl/','hóa thạch','B2','n'],['earthquake','/ˈɜːrθkweɪk/','động đất','B1','n'],['stratum','/ˈstrɑːtəm/','địa tầng','C1','n'],['ore','/ɔːr/','quặng','B2','n'],['aquifer','/ˈækwɪfər/','tầng ngậm nước','C1','n'],['lithosphere','/ˈlɪθəsfɪr/','thạch quyển','C1','n'],
// ═══════════ THỦY LỢI (Water Resources) ═══════════
['dam','/dæm/','đập','B1','n'],['reservoir','/ˈrezərvwɑːr/','hồ chứa','B2','n'],['canal','/kəˈnæl/','kênh','B1','n'],['floodplain','/ˈflʌdpleɪn/','vùng ngập lụt','B2','n'],['levee','/ˈlevi/','đê','B2','n'],['watershed','/ˈwɔːtərʃed/','lưu vực','B2','n'],['groundwater','/ˈɡraʊndwɔːtər/','nước ngầm','B2','n'],['hydrology','/haɪˈdrɒlədʒi/','thủy văn học','C1','n'],['sluice','/sluːs/','cống','C1','n'],['embankment','/ɪmˈbæŋkmənt/','đê điều','B2','n'],
// ═══════════ ÂM NHẠC (Music) ═══════════
['melody','/ˈmelədi/','giai điệu','B1','n'],['harmony','/ˈhɑːrməni/','hòa âm','B2','n'],['rhythm','/ˈrɪðəm/','nhịp điệu','B1','n'],['tempo','/ˈtempoʊ/','tốc độ nhịp','B2','n'],['chord','/kɔːrd/','hợp âm','B2','n'],['orchestra','/ˈɔːrkɪstrə/','dàn nhạc','B1','n'],['conductor','/kənˈdʌktər/','nhạc trưởng','B2','n'],['symphony','/ˈsɪmfəni/','giao hưởng','B2','n'],['pitch','/pɪtʃ/','cao độ','B2','n'],['soprano','/səˈprænoʊ/','giọng nữ cao','B2','n'],
// ═══════════ THƯƠNG MẠI ĐIỆN TỬ (E-commerce) ═══════════
['checkout','/ˈtʃekaʊt/','thanh toán','B1','n'],['cart','/kɑːrt/','giỏ hàng','B1','n'],['payment gateway','/ˈpeɪmənt ˈɡeɪtweɪ/','cổng thanh toán','B2','n'],['dropshipping','/ˈdrɒpʃɪpɪŋ/','giao hàng tận nơi','B2','n'],['marketplace','/ˈmɑːrkɪtpleɪs/','sàn thương mại','B1','n'],['affiliate','/əˈfɪliət/','tiếp thị liên kết','B2','n'],['subscription','/səbˈskrɪpʃn/','đăng ký thuê bao','B2','n'],['refund','/ˈriːfʌnd/','hoàn tiền','B1','n'],['customer retention','/ˈkʌstəmər rɪˈtenʃn/','giữ chân khách hàng','B2','n'],['user experience','/ˈjuːzər ɪkˈspɪriəns/','trải nghiệm người dùng','B2','n'],
// ═══════════ QUẢN LÝ CÔNG (Public Administration) ═══════════
['bureaucracy','/bjʊˈrɒkrəsi/','bộ máy hành chính','B2','n'],['governance','/ˈɡʌvərnəns/','quản trị','B2','n'],['transparency','/trænsˈpærənsi/','minh bạch','B2','n'],['accountability','/əˌkaʊntəˈbɪləti/','trách nhiệm giải trình','B2','n'],['municipality','/mjuːˌnɪsɪˈpæləti/','chính quyền thành phố','C1','n'],['fiscal policy','/ˈfɪskl ˈpɒləsi/','chính sách tài khóa','B2','n'],['constituency','/kənˈstɪtjuənsi/','khu vực bầu cử','C1','n'],['subsidy','/ˈsʌbsədi/','trợ cấp','B2','n'],['decentralization','/diːˌsentrəlaɪˈzeɪʃn/','phân cấp','C1','n'],['referendum','/ˌrefəˈrendəm/','trưng cầu dân ý','C1','n'],
// ═══════════ VẬT LÝ (Physics) ═══════════
['momentum','/moʊˈmentəm/','động lượng','B2','n'],['acceleration','/əkˌseləˈreɪʃn/','gia tốc','B2','n'],['wavelength','/ˈweɪvleŋθ/','bước sóng','B2','n'],['frequency','/ˈfriːkwənsi/','tần số','B2','n'],['thermodynamics','/ˌθɜːrmoʊdaɪˈnæmɪks/','nhiệt động lực học','C1','n'],['quantum','/ˈkwɒntəm/','lượng tử','C1','n'],['relativity','/ˌrelɪˈtɪvəti/','thuyết tương đối','C1','n'],['magnetism','/ˈmæɡnətɪzəm/','từ tính','B2','n'],['optics','/ˈɒptɪks/','quang học','C1','n'],['particle','/ˈpɑːrtɪkl/','hạt','B2','n'],
];

