var DT1_EXTRA=[
// FEELINGS
{w:'jealous',p:'/ˈdʒeləs/',type:'adj',band:'A2',usage:'daily',topic:'feelings',vi:'ghen tị',meanings:[{vi:'ghen tị, đố kỵ',en:'feeling unhappy because someone has something you want',ex:[{en:'She was jealous of her friend\'s success.',vi:'Cô ấy ghen tị với thành công của bạn.'}]}],synonyms:['envious','covetous','resentful'],antonyms:['content','supportive'],collocations:['jealous of','get jealous','jealous boyfriend'],tip:'"Jealous" = ghen tị. "Envious" nhẹ hơn, ít tiêu cực hơn.'},
{w:'grateful',p:'/ˈɡreɪtfəl/',type:'adj',band:'A2',usage:'daily',topic:'feelings',vi:'biết ơn',meanings:[{vi:'cảm kích, biết ơn',en:'feeling thankful',ex:[{en:'I am grateful for your help.',vi:'Tôi biết ơn sự giúp đỡ của bạn.'}]}],synonyms:['thankful','appreciative'],antonyms:['ungrateful','unappreciative'],collocations:['grateful for','deeply grateful','forever grateful'],tip:'"I would be grateful if..." = cách nhờ vả lịch sự.'},
{w:'frustrated',p:'/frʌˈstreɪtɪd/',type:'adj',band:'B1',usage:'daily',topic:'feelings',vi:'bực bội, nản lòng',meanings:[{vi:'bực bội vì không đạt được mục tiêu',en:'upset because you cannot achieve something',ex:[{en:'I feel frustrated with this homework.',vi:'Tôi bực bội với bài tập này.'}]}],synonyms:['annoyed','exasperated','irritated'],antonyms:['satisfied','content'],collocations:['feel frustrated','get frustrated','frustrated with'],tip:'"Frustrating" (adj cho vật) vs "frustrated" (adj cho người).'},
{w:'relieved',p:'/rɪˈliːvd/',type:'adj',band:'B1',usage:'daily',topic:'feelings',vi:'nhẹ nhõm',meanings:[{vi:'cảm thấy nhẹ nhõm sau lo lắng',en:'happy because something unpleasant has stopped',ex:[{en:'I was so relieved when I passed the exam.',vi:'Tôi nhẹ nhõm biết bao khi đỗ kỳ thi.'}]}],synonyms:['reassured','comforted'],antonyms:['anxious','worried'],collocations:['feel relieved','relieved to hear','sigh of relief'],tip:'"What a relief!" = Nhẹ cả người!'},
{w:'embarrassed',p:'/ɪmˈbærəst/',type:'adj',band:'A2',usage:'daily',topic:'feelings',vi:'xấu hổ, ngượng ngùng',meanings:[{vi:'cảm thấy xấu hổ trước người khác',en:'feeling shy or ashamed',ex:[{en:'I was so embarrassed when I tripped.',vi:'Tôi xấu hổ quá khi bị vấp.'}]}],synonyms:['ashamed','self-conscious','mortified'],antonyms:['proud','confident'],collocations:['feel embarrassed','embarrassing moment','how embarrassing'],tip:'"Embarrassed" (người) vs "embarrassing" (tình huống).'},

// ACTIONS
{w:'apologise',p:'/əˈpɒlədʒaɪz/',type:'v',band:'A2',usage:'daily',topic:'actions',vi:'xin lỗi',meanings:[{vi:'nói lời xin lỗi',en:'to say sorry for something',ex:[{en:'I want to apologise for being late.',vi:'Tôi muốn xin lỗi vì đến trễ.'}]}],synonyms:['say sorry','express regret'],antonyms:['blame','accuse'],collocations:['apologise for','sincerely apologise','owe an apology'],tip:'"Apologise" (Anh) = "Apologize" (Mỹ).'},
{w:'complain',p:'/kəmˈpleɪn/',type:'v',band:'A2',usage:'daily',topic:'actions',vi:'phàn nàn, kêu ca',meanings:[{vi:'bày tỏ sự không hài lòng',en:'to express dissatisfaction',ex:[{en:'Stop complaining and start working!',vi:'Đừng phàn nàn nữa mà làm đi!'}]}],synonyms:['grumble','moan','whine','gripe'],antonyms:['praise','compliment'],collocations:['complain about','file a complaint','constant complaining'],tip:'"File a complaint" = gửi đơn khiếu nại (trang trọng).'},
{w:'hesitate',p:'/ˈhezɪteɪt/',type:'v',band:'B1',usage:'daily',topic:'actions',vi:'do dự, lưỡng lự',meanings:[{vi:'chần chừ trước khi hành động',en:'to pause before doing something',ex:[{en:'Don\'t hesitate to ask for help.',vi:'Đừng ngại hỏi giúp đỡ.'}]}],synonyms:['waver','pause','dither','falter'],antonyms:['decide','act'],collocations:['hesitate to ask','without hesitation','a moment of hesitation'],tip:'"Don\'t hesitate to contact me" = rất phổ biến trong email.'},
{w:'pretend',p:'/prɪˈtend/',type:'v',band:'A2',usage:'daily',topic:'actions',vi:'giả vờ, giả bộ',meanings:[{vi:'làm ra vẻ, giả vờ',en:'to behave as if something is true when it is not',ex:[{en:'He pretended to be asleep.',vi:'Anh ấy giả vờ ngủ.'}]}],synonyms:['fake','act','feign','simulate'],antonyms:['be genuine','be honest'],collocations:['pretend to be','pretend not to','stop pretending'],tip:'"Let\'s pretend" = chơi giả vờ (trẻ em).'},
{w:'recommend',p:'/ˌrekəˈmend/',type:'v',band:'A2',usage:'daily',topic:'actions',vi:'giới thiệu, khuyên',meanings:[{vi:'gợi ý hoặc khuyên ai đó',en:'to suggest something as good or suitable',ex:[{en:'Can you recommend a good restaurant?',vi:'Bạn có thể giới thiệu nhà hàng nào ngon không?'}]}],synonyms:['suggest','advise','endorse','propose'],antonyms:['discourage','warn against'],collocations:['highly recommend','recommend a book','recommendation letter'],tip:'"I would highly recommend it" = rất phổ biến trong reviews.'},
{w:'struggle',p:'/ˈstrʌɡəl/',type:'v/n',band:'B1',usage:'daily',topic:'actions',vi:'vật lộn, chật vật',meanings:[{vi:'cố gắng rất khó khăn',en:'to try very hard to do something difficult',ex:[{en:'Many students struggle with math.',vi:'Nhiều học sinh chật vật với toán.'}]}],synonyms:['fight','strive','battle','grapple'],antonyms:['breeze through','succeed easily'],collocations:['struggle with','struggle to','daily struggle','power struggle'],tip:'"Struggle" vừa là danh từ vừa là động từ.'},
{w:'afford',p:'/əˈfɔːrd/',type:'v',band:'A2',usage:'daily',topic:'actions',vi:'có khả năng chi trả',meanings:[{vi:'đủ tiền hoặc thời gian để làm gì',en:'to have enough money or time for something',ex:[{en:'I can\'t afford a new phone.',vi:'Tôi không đủ tiền mua điện thoại mới.'}]}],synonyms:['pay for','manage','bear the cost'],antonyms:[],collocations:['can\'t afford','afford to buy','affordable price'],tip:'"Affordable" = giá phải chăng. Rất thông dụng.'},

// SOCIAL
{w:'agree',p:'/əˈɡriː/',type:'v',band:'A1',usage:'daily',topic:'social',vi:'đồng ý, thỏa thuận',meanings:[{vi:'thỏa thuận, đồng ý với nhau',en:'a shared decision between people',ex:[{en:'We agreed to meet at 5 PM.',vi:'Chúng tôi đồng ý gặp lúc 5 giờ.'}]}],synonyms:['concur','consent','accept'],antonyms:['disagree','refuse'],collocations:['agree on','agree to','agree with','reach an agreement'],tip:'"Agree with" (đồng ý với người), "agree on" (đồng ý về vấn đề).'},
{w:'interrupt',p:'/ˌɪntəˈrʌpt/',type:'v',band:'B1',usage:'daily',topic:'social',vi:'ngắt lời, xen ngang',meanings:[{vi:'ngắt lời ai đó đang nói',en:'to stop someone while they are speaking',ex:[{en:'Please don\'t interrupt me.',vi:'Xin đừng ngắt lời tôi.'}]}],synonyms:['cut in','butt in','break in','interject'],antonyms:['listen','let finish'],collocations:['interrupt a conversation','sorry to interrupt','constant interruption'],tip:'"Sorry to interrupt, but..." = xin lỗi ngắt lời nhưng...'},
{w:'invite',p:'/ɪnˈvaɪt/',type:'v',band:'A1',usage:'daily',topic:'social',vi:'mời',meanings:[{vi:'mời ai đó tham gia',en:'to ask someone to come to an event',ex:[{en:'I invited her to the party.',vi:'Tôi mời cô ấy đến bữa tiệc.'}]}],synonyms:['ask','request','welcome'],antonyms:['exclude','uninvite'],collocations:['invite someone over','wedding invitation','invite to dinner'],tip:'"Invitation" (n) = lời mời. "RSVP" = xin hồi âm.'},
{w:'respect',p:'/rɪˈspekt/',type:'n/v',band:'A2',usage:'daily',topic:'social',vi:'tôn trọng',meanings:[{vi:'cảm giác ngưỡng mộ hoặc coi trọng',en:'admiration for someone or something',ex:[{en:'You should respect your teachers.',vi:'Bạn nên tôn trọng thầy cô.'}]}],synonyms:['admire','honour','esteem','value'],antonyms:['disrespect','despise'],collocations:['show respect','earn respect','with all due respect','mutual respect'],tip:'"With all due respect..." = xin phép nói thẳng — trước khi phản đối lịch sự.'},
{w:'trust',p:'/trʌst/',type:'n/v',band:'A2',usage:'daily',topic:'social',vi:'tin tưởng',meanings:[{vi:'tin cậy ai đó',en:'to believe in someone\'s honesty',ex:[{en:'I trust you completely.',vi:'Tôi tin tưởng bạn hoàn toàn.'}]}],synonyms:['believe in','rely on','have faith in'],antonyms:['distrust','suspect','doubt'],collocations:['trust someone','build trust','trust issues','breach of trust'],tip:'"Trust issues" = vấn đề niềm tin — rất phổ biến hiện nay.'},

// WORK
{w:'resign',p:'/rɪˈzaɪn/',type:'v',band:'B1',usage:'daily',topic:'work',vi:'từ chức, nghỉ việc',meanings:[{vi:'rời bỏ công việc chính thức',en:'to formally leave a job',ex:[{en:'She resigned from her position.',vi:'Cô ấy từ chức.'}]}],synonyms:['quit','step down','leave','hand in notice'],antonyms:['stay','continue','join'],collocations:['resign from','letter of resignation','resign immediately'],tip:'"Hand in your resignation" = nộp đơn từ chức.'},
{w:'promote',p:'/prəˈmoʊt/',type:'v',band:'B1',usage:'daily',topic:'work',vi:'thăng chức / quảng bá',meanings:[{vi:'nâng cấp vị trí hoặc quảng bá',en:'to raise to a higher position or advertise',ex:[{en:'She was promoted to manager.',vi:'Cô ấy được thăng chức quản lý.'}]}],synonyms:['advance','upgrade','advertise','boost'],antonyms:['demote','downgrade'],collocations:['get promoted','promote a product','promotion'],tip:'"Get a promotion" = được thăng chức.'},
{w:'salary',p:'/ˈsæləri/',type:'n',band:'A2',usage:'daily',topic:'work',vi:'lương tháng',meanings:[{vi:'tiền lương trả hàng tháng',en:'a fixed regular payment for work',ex:[{en:'What is the average salary here?',vi:'Lương trung bình ở đây bao nhiêu?'}]}],synonyms:['pay','wage','income','earnings'],antonyms:[],collocations:['annual salary','salary raise','starting salary','salary negotiation'],tip:'"Salary" (lương tháng) vs "wage" (lương giờ/ngày).'},
{w:'colleague',p:'/ˈkɒliːɡ/',type:'n',band:'A2',usage:'daily',topic:'work',vi:'đồng nghiệp',meanings:[{vi:'người làm việc cùng',en:'a person you work with',ex:[{en:'My colleagues are very friendly.',vi:'Đồng nghiệp của tôi rất thân thiện.'}]}],synonyms:['coworker','workmate','associate','peer'],antonyms:['rival','competitor'],collocations:['work colleague','former colleague','close colleague'],tip:'"Colleague" trang trọng hơn "coworker".'},

// HEALTH
{w:'symptom',p:'/ˈsɪmptəm/',type:'n',band:'B1',usage:'daily',topic:'health',vi:'triệu chứng',meanings:[{vi:'dấu hiệu của bệnh',en:'a sign of illness',ex:[{en:'What are your symptoms?',vi:'Triệu chứng của bạn là gì?'}]}],synonyms:['sign','indication','manifestation'],antonyms:[],collocations:['common symptoms','mild symptoms','show symptoms','symptom checker'],tip:'Bác sĩ hỏi: "What symptoms do you have?"'},
{w:'prescribe',p:'/prɪˈskraɪb/',type:'v',band:'B1',usage:'daily',topic:'health',vi:'kê đơn thuốc',meanings:[{vi:'bác sĩ kê thuốc cho bệnh nhân',en:'to recommend medicine as treatment',ex:[{en:'The doctor prescribed antibiotics.',vi:'Bác sĩ kê đơn kháng sinh.'}]}],synonyms:['recommend','order','advise'],antonyms:[],collocations:['prescribe medicine','prescription','over-the-counter'],tip:'"Prescription" = đơn thuốc. "Over-the-counter" = mua không cần đơn.'},
{w:'allergy',p:'/ˈælɜrdʒi/',type:'n',band:'A2',usage:'daily',topic:'health',vi:'dị ứng',meanings:[{vi:'phản ứng cơ thể với chất nào đó',en:'a bad reaction to certain substances',ex:[{en:'I have an allergy to peanuts.',vi:'Tôi bị dị ứng đậu phộng.'}]}],synonyms:['sensitivity','intolerance','reaction'],antonyms:[],collocations:['food allergy','allergic reaction','allergy season','allergic to'],tip:'"Allergic to" = bị dị ứng với. "I\'m allergic to cats."'},

// FOOD
{w:'starving',p:'/ˈstɑːrvɪŋ/',type:'adj',band:'A2',usage:'daily',topic:'food',vi:'đói lả, đói kinh khủng',meanings:[{vi:'rất đói (cường điệu)',en:'extremely hungry (informal exaggeration)',ex:[{en:'I\'m starving! Let\'s eat.',vi:'Tôi đói lả rồi! Ăn thôi.'}]}],synonyms:['famished','ravenous','hungry'],antonyms:['full','stuffed','satisfied'],collocations:['absolutely starving','starving to death'],tip:'"I\'m starving" = cách nói phóng đại rất phổ biến.'},
{w:'recipe',p:'/ˈresɪpi/',type:'n',band:'A2',usage:'daily',topic:'food',vi:'công thức nấu ăn',meanings:[{vi:'hướng dẫn cách nấu món ăn',en:'instructions for cooking a dish',ex:[{en:'Can you share the recipe?',vi:'Bạn có thể chia sẻ công thức không?'}]}],synonyms:['formula','instructions','method'],antonyms:[],collocations:['follow a recipe','family recipe','recipe book','secret recipe'],tip:'Phát âm: /ˈresɪpi/ — KHÔNG phải /rɪˈsiːp/.'},
{w:'spicy',p:'/ˈspaɪsi/',type:'adj',band:'A1',usage:'daily',topic:'food',vi:'cay',meanings:[{vi:'có vị cay',en:'having a strong hot flavour',ex:[{en:'Thai food is very spicy.',vi:'Đồ ăn Thái rất cay.'}]}],synonyms:['hot','fiery','peppery','pungent'],antonyms:['mild','bland','plain'],collocations:['spicy food','too spicy','mildly spicy'],tip:'"How spicy can you handle?" = bạn ăn cay được mức nào?'},

// TRAVEL
{w:'destination',p:'/ˌdestɪˈneɪʃən/',type:'n',band:'A2',usage:'daily',topic:'travel',vi:'điểm đến',meanings:[{vi:'nơi bạn đang đi tới',en:'the place where someone is going',ex:[{en:'What is your travel destination?',vi:'Điểm đến du lịch của bạn là gì?'}]}],synonyms:['endpoint','target','goal','stop'],antonyms:['origin','departure point'],collocations:['travel destination','popular destination','final destination','dream destination'],tip:'"Dream destination" = điểm đến mơ ước.'},
{w:'souvenir',p:'/ˌsuːvəˈnɪər/',type:'n',band:'A2',usage:'daily',topic:'travel',vi:'quà lưu niệm',meanings:[{vi:'vật mua về để nhớ chuyến đi',en:'something bought to remember a place',ex:[{en:'I bought a souvenir for my mom.',vi:'Tôi mua quà lưu niệm cho mẹ.'}]}],synonyms:['memento','keepsake','token','reminder'],antonyms:[],collocations:['souvenir shop','buy souvenirs','souvenir magnet'],tip:'Từ gốc Pháp. Phát âm: /ˌsuːvəˈnɪər/.'},

// HOME
{w:'landlord',p:'/ˈlændlɔːrd/',type:'n',band:'B1',usage:'daily',topic:'home',vi:'chủ nhà (cho thuê)',meanings:[{vi:'người sở hữu nhà và cho thuê',en:'the owner of a property that is rented',ex:[{en:'The landlord raised the rent.',vi:'Chủ nhà tăng tiền thuê.'}]}],synonyms:['property owner','lessor'],antonyms:['tenant','renter'],collocations:['contact the landlord','landlord and tenant','absentee landlord'],tip:'"Landlord" (nam) / "Landlady" (nữ). "Tenant" = người thuê.'},
{w:'mortgage',p:'/ˈmɔːrɡɪdʒ/',type:'n',band:'B1',usage:'daily',topic:'home',vi:'thế chấp, vay mua nhà',meanings:[{vi:'khoản vay ngân hàng để mua nhà',en:'a loan for buying property',ex:[{en:'We\'re paying off our mortgage.',vi:'Chúng tôi đang trả nợ thế chấp.'}]}],synonyms:['home loan','property loan'],antonyms:[],collocations:['mortgage rate','pay the mortgage','mortgage payment','get a mortgage'],tip:'"Mortgage" — chữ "t" câm, phát âm /ˈmɔːrɡɪdʒ/.'},

// TECH
{w:'update',p:'/ʌpˈdeɪt/',type:'v/n',band:'A2',usage:'daily',topic:'tech',vi:'cập nhật',meanings:[{vi:'đưa thông tin mới nhất',en:'to make something more current',ex:[{en:'Don\'t forget to update your phone.',vi:'Đừng quên cập nhật điện thoại.'}]}],synonyms:['upgrade','refresh','modernise','renew'],antonyms:['downgrade','revert'],collocations:['software update','update regularly','status update','keep updated'],tip:'"Keep me updated" = cho tôi biết tin mới nhé.'},
{w:'password',p:'/ˈpæswɜːrd/',type:'n',band:'A1',usage:'daily',topic:'tech',vi:'mật khẩu',meanings:[{vi:'chuỗi ký tự bí mật để đăng nhập',en:'a secret word for accessing an account',ex:[{en:'I forgot my password again.',vi:'Tôi lại quên mật khẩu rồi.'}]}],synonyms:['passcode','PIN','access code'],antonyms:[],collocations:['change password','strong password','reset password','password manager'],tip:'"Strong password" = mật khẩu mạnh. Nên dùng password manager.'},
{w:'download',p:'/ˈdaʊnloʊd/',type:'v/n',band:'A1',usage:'daily',topic:'tech',vi:'tải xuống',meanings:[{vi:'tải dữ liệu từ internet về thiết bị',en:'to copy data from the internet',ex:[{en:'I downloaded the app.',vi:'Tôi đã tải ứng dụng xuống.'}]}],synonyms:['save','install','get'],antonyms:['upload','delete'],collocations:['download an app','free download','download speed'],tip:'"Download" ↔ "Upload" (tải lên).'},

// MONEY
{w:'budget',p:'/ˈbʌdʒɪt/',type:'n/v',band:'B1',usage:'daily',topic:'money',vi:'ngân sách',meanings:[{vi:'kế hoạch chi tiêu tiền',en:'the money available to spend',ex:[{en:'We need to stick to our budget.',vi:'Chúng ta cần tuân theo ngân sách.'}]}],synonyms:['funds','finances','allowance','spending plan'],antonyms:[],collocations:['on a budget','budget-friendly','annual budget','budget cuts'],tip:'"On a budget" = có ngân sách hạn hẹp. "Budget-friendly" = giá phải chăng.'},
{w:'bargain',p:'/ˈbɑːrɡɪn/',type:'n/v',band:'B1',usage:'daily',topic:'money',vi:'món hời, mặc cả',meanings:[{vi:'mua được giá rẻ hoặc thương lượng giá',en:'a good deal; to negotiate price',ex:[{en:'This shirt is a real bargain!',vi:'Cái áo này là món hời thật!'}]}],synonyms:['deal','discount','negotiate','haggle'],antonyms:['rip-off','overpay'],collocations:['bargain hunter','real bargain','bargain price','drive a hard bargain'],tip:'"What a bargain!" = món hời quá! "Bargain hunter" = người săn hàng giảm giá.'},
{w:'receipt',p:'/rɪˈsiːt/',type:'n',band:'A2',usage:'daily',topic:'money',vi:'hóa đơn, biên lai',meanings:[{vi:'giấy chứng nhận đã thanh toán',en:'written proof of payment',ex:[{en:'Can I have the receipt, please?',vi:'Cho tôi xin hóa đơn.'}]}],synonyms:['bill','proof of purchase','invoice','ticket'],antonyms:[],collocations:['keep the receipt','email receipt','receipt of payment'],tip:'Chữ "p" câm: phát âm /rɪˈsiːt/ KHÔNG phải /rɪˈsiːpt/.'},
{w:'debt',p:'/det/',type:'n',band:'B1',usage:'daily',topic:'money',vi:'nợ',meanings:[{vi:'khoản tiền phải trả',en:'money that you owe',ex:[{en:'He is deep in debt.',vi:'Anh ấy nợ nần chồng chất.'}]}],synonyms:['loan','liability','obligation','dues'],antonyms:['credit','surplus','savings'],collocations:['in debt','pay off debt','debt-free','student debt'],tip:'Chữ "b" câm: phát âm /det/. "Debt-free" = hết nợ.'},

// TIME
{w:'postpone',p:'/poʊstˈpoʊn/',type:'v',band:'B1',usage:'daily',topic:'time',vi:'hoãn lại, dời lại',meanings:[{vi:'chuyển sang thời gian muộn hơn',en:'to arrange for something to happen later',ex:[{en:'The meeting was postponed to Friday.',vi:'Cuộc họp bị hoãn đến thứ Sáu.'}]}],synonyms:['delay','defer','put off','reschedule'],antonyms:['advance','bring forward'],collocations:['postpone a meeting','postpone indefinitely','postponed until'],tip:'"Postpone" (trang trọng) = "Put off" (thông tục).'},
{w:'meanwhile',p:'/ˈmiːnwaɪl/',type:'adv',band:'B1',usage:'daily',topic:'time',vi:'trong khi đó',meanings:[{vi:'cùng thời gian đó',en:'at the same time; in the intervening period',ex:[{en:'I\'ll cook. Meanwhile, you set the table.',vi:'Tôi nấu ăn. Trong khi đó, bạn dọn bàn.'}]}],synonyms:['in the meantime','at the same time','simultaneously'],antonyms:[],collocations:['meanwhile, back at','in the meanwhile'],tip:'"In the meantime" = trong lúc chờ đợi. Rất hay dùng.'},
{w:'eventually',p:'/ɪˈventʃuəli/',type:'adv',band:'B1',usage:'daily',topic:'time',vi:'cuối cùng, rốt cuộc',meanings:[{vi:'sau một khoảng thời gian dài',en:'in the end; after a period of time',ex:[{en:'He eventually found a job.',vi:'Cuối cùng anh ấy cũng tìm được việc.'}]}],synonyms:['finally','ultimately','in the end','at last'],antonyms:['immediately','right away','never'],collocations:['eventually become','will eventually','eventually lead to'],tip:'"Eventually" ≠ "finally". Eventually nhấn mạnh quá trình dài.'},
];
