// DT2 Extra Words — expansion to ~150 total
var DT2_EXTRA = [
  // DESCRIBE (thêm)
  {w:'peculiar',p:'/pɪˈkjuːliər/',type:'adj',band:'B2',usage:'daily',topic:'describe',vi:'kỳ lạ, đặc biệt',meanings:[{vi:'kỳ lạ, khác thường',en:'strange or unusual',ex:[{en:'There is a peculiar smell in the room.',vi:'Có một mùi kỳ lạ trong phòng.'}]}],synonyms:['strange','odd','unusual','bizarre'],antonyms:['normal','ordinary'],collocations:['peculiar smell','peculiar behaviour','peculiar to'],tip:'"Peculiar to" = đặc trưng riêng. "A peculiar sense of humour."'},
  {w:'profound',p:'/prəˈfaʊnd/',type:'adj',band:'B2',usage:'formal',topic:'describe',vi:'sâu sắc, uyên thâm',meanings:[{vi:'rất sâu, có ý nghĩa lớn',en:'very great or intense; showing deep insight',ex:[{en:'The book had a profound impact on me.',vi:'Cuốn sách có tác động sâu sắc lên tôi.'}]}],synonyms:['deep','significant','intense','far-reaching'],antonyms:['shallow','superficial','trivial'],collocations:['profound impact','profound effect','profound change'],tip:'IELTS Writing: "have a profound impact on" = band 7+.'},
  {w:'absurd',p:'/əbˈsɜːrd/',type:'adj',band:'B2',usage:'daily',topic:'describe',vi:'vô lý, phi lý',meanings:[{vi:'hoàn toàn không hợp lý',en:'wildly unreasonable or illogical',ex:[{en:'The idea is absolutely absurd.',vi:'Ý tưởng hoàn toàn vô lý.'}]}],synonyms:['ridiculous','ludicrous','preposterous','nonsensical'],antonyms:['reasonable','sensible','logical'],collocations:['utterly absurd','absurd idea','absurd situation'],tip:'Stronger than "silly". IELTS: "It would be absurd to suggest that..."'},

  // THINK & OPINION (thêm)
  {w:'scrutinise',p:'/ˈskruːtɪnaɪz/',type:'v',band:'B2',usage:'formal',topic:'think',vi:'xem xét kỹ lưỡng',meanings:[{vi:'kiểm tra rất cẩn thận',en:'to examine closely and thoroughly',ex:[{en:'The report was scrutinised by experts.',vi:'Báo cáo được các chuyên gia xem xét kỹ lưỡng.'}]}],synonyms:['examine','inspect','analyse','investigate'],antonyms:['ignore','overlook','glance'],collocations:['closely scrutinised','scrutinise data','public scrutiny'],tip:'"Under scrutiny" = đang bị kiểm tra. Very academic tone.'},
  {w:'deduce',p:'/dɪˈdjuːs/',type:'v',band:'B2',usage:'formal',topic:'think',vi:'suy luận, suy ra',meanings:[{vi:'đi đến kết luận bằng logic',en:'to arrive at a conclusion by reasoning',ex:[{en:'We can deduce that the trend will continue.',vi:'Chúng ta có thể suy ra rằng xu hướng sẽ tiếp tục.'}]}],synonyms:['infer','conclude','reason','derive'],antonyms:['guess','assume'],collocations:['deduce from','logically deduce','it can be deduced'],tip:'IELTS Reading: "What can be deduced from the passage?" = câu hỏi thường gặp.'},
  {w:'distort',p:'/dɪˈstɔːrt/',type:'v',band:'B2',usage:'formal',topic:'think',vi:'bóp méo, xuyên tạc',meanings:[{vi:'làm sai lệch sự thật',en:'to give a misleading account of',ex:[{en:'The media can distort the truth.',vi:'Truyền thông có thể bóp méo sự thật.'}]}],synonyms:['misrepresent','twist','warp','falsify'],antonyms:['clarify','represent accurately'],collocations:['distort the truth','distort facts','distorted image'],tip:'"Distort the truth" = bóp méo sự thật. Rất hay trong media/society essays.'},

  // CHANGE & DEVELOP (thêm)
  {w:'revolutionise',p:'/ˌrevəˈluːʃənaɪz/',type:'v',band:'B2',usage:'formal',topic:'change',vi:'cách mạng hóa',meanings:[{vi:'thay đổi hoàn toàn, đổi mới triệt để',en:'to change fundamentally or dramatically',ex:[{en:'The internet revolutionised communication.',vi:'Internet đã cách mạng hóa giao tiếp.'}]}],synonyms:['transform','overhaul','reshape','reform'],antonyms:['preserve','maintain'],collocations:['revolutionise industry','revolutionise the way','technological revolution'],tip:'Stronger than "change". IELTS: "AI has revolutionised healthcare."'},
  {w:'accelerate',p:'/əkˈseləreɪt/',type:'v',band:'B2',usage:'formal',topic:'change',vi:'tăng tốc, đẩy nhanh',meanings:[{vi:'làm nhanh hơn',en:'to increase in rate or speed',ex:[{en:'The pandemic accelerated digital transformation.',vi:'Đại dịch đã đẩy nhanh chuyển đổi số.'}]}],synonyms:['speed up','hasten','quicken','expedite'],antonyms:['slow down','decelerate','hinder'],collocations:['accelerate growth','accelerate change','rapidly accelerating'],tip:'IELTS Task 1: "The rate of growth accelerated sharply."'},
  {w:'erode',p:'/ɪˈroʊd/',type:'v',band:'B2',usage:'formal',topic:'change',vi:'xói mòn, bào mòn',meanings:[{vi:'phá hủy dần dần',en:'to gradually destroy or wear away',ex:[{en:'Trust in government has eroded over time.',vi:'Niềm tin vào chính phủ đã bị xói mòn theo thời gian.'}]}],synonyms:['wear away','corrode','deteriorate','undermine'],antonyms:['build','strengthen','reinforce'],collocations:['erode trust','erode confidence','soil erosion'],tip:'Figurative: "erode trust/freedom/values". Very powerful in IELTS essays.'},

  // PROBLEM & SOLUTION (thêm)
  {w:'aggravate',p:'/ˈæɡrəveɪt/',type:'v',band:'B2',usage:'formal',topic:'problem',vi:'làm tệ hơn, chọc tức',meanings:[{vi:'làm vấn đề trầm trọng hơn',en:'to make worse or more serious',ex:[{en:'Pollution aggravates respiratory problems.',vi:'Ô nhiễm làm trầm trọng thêm vấn đề hô hấp.'}]}],synonyms:['worsen','exacerbate','intensify','compound'],antonyms:['alleviate','improve','ease'],collocations:['aggravate the situation','aggravating factor','further aggravated'],tip:'Similar to "exacerbate" but slightly less formal.'},
  {w:'feasible',p:'/ˈfiːzəbəl/',type:'adj',band:'B2',usage:'formal',topic:'problem',vi:'khả thi, có thể thực hiện',meanings:[{vi:'có thể làm được',en:'possible to do easily or conveniently',ex:[{en:'Is this plan feasible within the budget?',vi:'Kế hoạch này có khả thi trong ngân sách không?'}]}],synonyms:['possible','viable','achievable','practical'],antonyms:['impossible','impractical','unfeasible'],collocations:['economically feasible','feasible solution','feasibility study'],tip:'"Feasibility study" = nghiên cứu tính khả thi. Very professional vocabulary.'},

  // RELATIONSHIPS (thêm)
  {w:'compromise',p:'/ˈkɒmprəmaɪz/',type:'n/v',band:'B1',usage:'daily',topic:'relate',vi:'thỏa hiệp, nhượng bộ',meanings:[{vi:'mỗi bên nhường một phần',en:'an agreement reached by each side making concessions',ex:[{en:'Both sides need to compromise.',vi:'Cả hai bên cần thỏa hiệp.'}]}],synonyms:['concession','settlement','middle ground','trade-off'],antonyms:['stubbornness','inflexibility'],collocations:['reach a compromise','willing to compromise','compromise on'],tip:'"Reach a compromise" = đạt được thỏa hiệp. Essential for discussion essays.'},
  {w:'alienate',p:'/ˈeɪliəneɪt/',type:'v',band:'B2',usage:'formal',topic:'relate',vi:'xa lánh, cô lập',meanings:[{vi:'làm ai đó cảm thấy bị tách biệt',en:'to make someone feel isolated',ex:[{en:'His behaviour alienated his colleagues.',vi:'Hành vi của anh ấy khiến đồng nghiệp xa lánh.'}]}],synonyms:['isolate','estrange','exclude','distance'],antonyms:['unite','connect','include'],collocations:['alienate voters','feel alienated','alienate customers'],tip:'"Social alienation" = sự cô lập xã hội. Good for society essays.'},

  // QUANTITY & DEGREE (thêm)
  {w:'ample',p:'/ˈæmpəl/',type:'adj',band:'B2',usage:'formal',topic:'quantity',vi:'dồi dào, đủ đầy',meanings:[{vi:'đủ và hơn mức cần thiết',en:'enough or more than enough',ex:[{en:'There is ample evidence to support this.',vi:'Có đủ bằng chứng để hỗ trợ điều này.'}]}],synonyms:['sufficient','plenty','adequate','generous'],antonyms:['insufficient','scarce','meagre'],collocations:['ample time','ample evidence','ample opportunity'],tip:'More formal than "enough". IELTS: "There is ample evidence that..."'},
  {w:'merely',p:'/ˈmɪərli/',type:'adv',band:'B1',usage:'formal',topic:'quantity',vi:'chỉ, đơn thuần',meanings:[{vi:'chỉ là, không gì hơn',en:'just; only',ex:[{en:'It is merely a suggestion.',vi:'Đó chỉ đơn thuần là một gợi ý.'}]}],synonyms:['just','only','simply','purely'],antonyms:['significantly','greatly'],collocations:['merely a suggestion','not merely','merely scratching the surface'],tip:'"Not merely X but also Y" = không chỉ X mà còn Y. Elegant writing structure.'},

  // CAUSE & EFFECT (thêm)
  {w:'attribute',p:'/əˈtrɪbjuːt/',type:'v',band:'B2',usage:'formal',topic:'cause',vi:'quy cho, gán cho',meanings:[{vi:'coi là do nguyên nhân nào đó',en:'to regard as being caused by',ex:[{en:'She attributes her success to hard work.',vi:'Cô ấy quy thành công cho sự chăm chỉ.'}]}],synonyms:['credit','ascribe','put down to','assign'],antonyms:['deny','disclaim'],collocations:['attribute to','widely attributed','attribute success to'],tip:'IELTS: "This can be attributed to..." = nguyên nhân là do...'},
  {w:'provoke',p:'/prəˈvoʊk/',type:'v',band:'B2',usage:'daily',topic:'cause',vi:'khiêu khích, kích động',meanings:[{vi:'gây ra phản ứng, làm nổi giận',en:'to stimulate a reaction or emotion',ex:[{en:'The speech provoked widespread debate.',vi:'Bài phát biểu đã kích động cuộc tranh luận rộng rãi.'}]}],synonyms:['trigger','incite','stimulate','arouse'],antonyms:['calm','soothe','pacify'],collocations:['provoke debate','provoke anger','provoke a response'],tip:'"Provoke thought/debate" = kích thích suy nghĩ/tranh luận. Academic tone.'},
  {w:'undergo',p:'/ˌʌndərˈɡoʊ/',type:'v',band:'B2',usage:'formal',topic:'cause',vi:'trải qua',meanings:[{vi:'trải qua một quá trình hoặc thay đổi',en:'to experience or be subjected to',ex:[{en:'The city has undergone significant changes.',vi:'Thành phố đã trải qua những thay đổi đáng kể.'}]}],synonyms:['experience','go through','endure','face'],antonyms:['avoid','escape'],collocations:['undergo changes','undergo surgery','undergo transformation'],tip:'IELTS Task 1: "The area underwent significant development between 2000 and 2020."'},

  // DAILY LIFE 2 (thêm)
  {w:'savour',p:'/ˈseɪvər/',type:'v',band:'B2',usage:'daily',topic:'daily2',vi:'thưởng thức, tận hưởng từ từ',meanings:[{vi:'tận hưởng trọn vẹn',en:'to enjoy something to the full',ex:[{en:'Take time to savour every moment.',vi:'Hãy dành thời gian thưởng thức từng khoảnh khắc.'}]}],synonyms:['enjoy','relish','appreciate','delight in'],antonyms:['rush','ignore'],collocations:['savour the moment','savour every bite','savour the taste'],tip:'"Savour" implies slow, mindful enjoyment. More poetic than "enjoy".'},
  {w:'multitask',p:'/ˈmʌltiˌtæsk/',type:'v',band:'B1',usage:'daily',topic:'daily2',vi:'làm nhiều việc cùng lúc',meanings:[{vi:'thực hiện nhiều nhiệm vụ đồng thời',en:'to deal with more than one task at the same time',ex:[{en:'Modern workers need to multitask efficiently.',vi:'Người lao động hiện đại cần làm nhiều việc cùng lúc hiệu quả.'}]}],synonyms:['juggle tasks','handle multiple tasks'],antonyms:['focus','specialise'],collocations:['ability to multitask','multitasking skills'],tip:'"Multitasking" — skill thường hỏi trong phỏng vấn xin việc.'},

  // EXPRESSING OPINION (thêm)
  {w:'advocate',p:'/ˈædvəkeɪt/',type:'v/n',band:'B2',usage:'formal',topic:'opinion',vi:'ủng hộ, người bênh vực',meanings:[{vi:'ủng hộ công khai',en:'to publicly recommend or support',ex:[{en:'She advocates for equal rights.',vi:'Cô ấy ủng hộ quyền bình đẳng.'}]}],synonyms:['support','promote','champion','endorse'],antonyms:['oppose','criticise','reject'],collocations:['advocate for','strong advocate','advocate change'],tip:'IELTS: "Many experts advocate..." = nhiều chuyên gia ủng hộ...'},
  {w:'dispute',p:'/dɪˈspjuːt/',type:'v/n',band:'B2',usage:'formal',topic:'opinion',vi:'tranh chấp, phản bác',meanings:[{vi:'không đồng ý hoặc tranh cãi',en:'to argue about; a disagreement',ex:[{en:'The findings are hotly disputed.',vi:'Các phát hiện bị phản bác gay gắt.'}]}],synonyms:['argue','contest','challenge','debate'],antonyms:['agree','accept','concur'],collocations:['dispute a claim','territorial dispute','beyond dispute'],tip:'"Beyond dispute" = không thể tranh cãi. "A hotly disputed topic."'},
  {w:'endorse',p:'/ɪnˈdɔːrs/',type:'v',band:'B2',usage:'formal',topic:'opinion',vi:'xác nhận, tán thành',meanings:[{vi:'công khai ủng hộ hoặc chấp thuận',en:'to declare public approval of',ex:[{en:'The committee endorsed the proposal.',vi:'Ủy ban đã tán thành đề xuất.'}]}],synonyms:['approve','support','back','sanction'],antonyms:['reject','oppose','condemn'],collocations:['publicly endorse','endorse a product','endorse a policy'],tip:'"Celebrity endorsement" = người nổi tiếng quảng bá sản phẩm.'},

  // ACADEMIC (thêm)
  {w:'coherent',p:'/koʊˈhɪərənt/',type:'adj',band:'B2',usage:'formal',topic:'academic',vi:'mạch lạc, chặt chẽ',meanings:[{vi:'logic và nhất quán',en:'logical and consistent',ex:[{en:'Your essay needs a more coherent structure.',vi:'Bài luận cần cấu trúc mạch lạc hơn.'}]}],synonyms:['logical','consistent','clear','organised'],antonyms:['incoherent','disjointed','confused'],collocations:['coherent argument','coherent plan','coherent structure'],tip:'IELTS Writing band 7 criterion: "coherence and cohesion".'},

  // PERSONALITY (thêm)
  {w:'conscientious',p:'/ˌkɒnʃiˈenʃəs/',type:'adj',band:'B2',usage:'formal',topic:'personality',vi:'tận tâm, cần mẫn',meanings:[{vi:'làm việc rất cẩn thận và kỹ lưỡng',en:'wishing to do what is right; thorough',ex:[{en:'She is a conscientious worker.',vi:'Cô ấy là người lao động tận tâm.'}]}],synonyms:['diligent','careful','thorough','dedicated'],antonyms:['careless','lazy','negligent'],collocations:['conscientious worker','conscientious effort','conscientious objector'],tip:'"Conscientious" shows you care about quality. One of Big Five personality traits.'},
  {w:'charismatic',p:'/ˌkærɪzˈmætɪk/',type:'adj',band:'B2',usage:'daily',topic:'personality',vi:'có sức thu hút, lôi cuốn',meanings:[{vi:'có khả năng thu hút và truyền cảm hứng',en:'exercising a compelling charm that inspires devotion',ex:[{en:'She is a charismatic leader.',vi:'Cô ấy là một nhà lãnh đạo lôi cuốn.'}]}],synonyms:['charming','magnetic','captivating','inspiring'],antonyms:['uninspiring','dull','bland'],collocations:['charismatic leader','charismatic personality','naturally charismatic'],tip:'"Charisma" (n) = sức hút cá nhân. Very useful for IELTS Speaking Part 2.'},

  // MODERN LIFE (thêm)
  {w:'streamline',p:'/ˈstriːmlaɪn/',type:'v',band:'B2',usage:'formal',topic:'modern',vi:'tinh gọn, tối ưu hóa',meanings:[{vi:'làm cho hiệu quả hơn',en:'to make more efficient by simplifying',ex:[{en:'The company streamlined its operations.',vi:'Công ty đã tinh gọn hoạt động.'}]}],synonyms:['simplify','optimise','rationalise','modernise'],antonyms:['complicate','hinder'],collocations:['streamline processes','streamline operations','streamlined approach'],tip:'"Streamline" = cắt bỏ thứ thừa, giữ lại cái hiệu quả.'},
  {w:'outsource',p:'/ˈaʊtsɔːrs/',type:'v',band:'B2',usage:'formal',topic:'modern',vi:'thuê ngoài',meanings:[{vi:'giao công việc cho bên ngoài',en:'to obtain goods or services from an outside supplier',ex:[{en:'Many companies outsource their IT.',vi:'Nhiều công ty thuê ngoài phần IT.'}]}],synonyms:['subcontract','delegate','farm out'],antonyms:['insource','keep in-house'],collocations:['outsource jobs','outsource production','outsource to'],tip:'"Outsourcing" = thuê ngoài — IELTS globalisation topic.'},

  // NEW TOPIC: COMMUNICATION
  {w:'articulate',p:'/ɑːrˈtɪkjʊleɪt/',type:'adj/v',band:'B2',usage:'formal',topic:'opinion',vi:'ăn nói lưu loát; diễn đạt rõ ràng',meanings:[{vi:'nói rõ ràng, mạch lạc',en:'able to express ideas clearly',ex:[{en:'She is very articulate in English.',vi:'Cô ấy rất lưu loát trong tiếng Anh.'}]}],synonyms:['eloquent','fluent','expressive','clear'],antonyms:['inarticulate','unclear','mumbling'],collocations:['articulate speaker','clearly articulated','well-articulated'],tip:'"Articulate your ideas" = diễn đạt ý tưởng rõ ràng — IELTS Speaking goal.'},
  {w:'eloquent',p:'/ˈeləkwənt/',type:'adj',band:'B2',usage:'formal',topic:'opinion',vi:'hùng biện, có tài ăn nói',meanings:[{vi:'nói hay, thuyết phục',en:'fluent and persuasive in speaking or writing',ex:[{en:'He gave an eloquent speech.',vi:'Anh ấy đã đọc một bài diễn văn hùng biện.'}]}],synonyms:['articulate','persuasive','expressive','fluent'],antonyms:['inarticulate','tongue-tied'],collocations:['eloquent speech','eloquent argument','most eloquent'],tip:'Higher level than "articulate". "An eloquent defence of..." = bài bênh vực hay.'},
  {w:'concise',p:'/kənˈsaɪs/',type:'adj',band:'B2',usage:'formal',topic:'academic',vi:'ngắn gọn, súc tích',meanings:[{vi:'nói/viết ngắn gọn nhưng đầy đủ ý',en:'giving information clearly and in few words',ex:[{en:'Keep your answers concise.',vi:'Giữ câu trả lời ngắn gọn.'}]}],synonyms:['brief','succinct','to the point','compact'],antonyms:['verbose','wordy','lengthy'],collocations:['concise summary','concise and clear','be concise'],tip:'IELTS Writing tip: "Be concise" = viết ngắn gọn, đủ ý. Không lặp lại.'},
  {w:'imply',p:'/ɪmˈplaɪ/',type:'v',band:'B1',usage:'daily',topic:'think',vi:'ngụ ý, ám chỉ',meanings:[{vi:'gợi ý gián tiếp mà không nói thẳng',en:'to suggest without stating directly',ex:[{en:'Are you implying I was wrong?',vi:'Bạn đang ám chỉ tôi sai à?'}]}],synonyms:['suggest','hint','indicate','insinuate'],antonyms:['state','declare','specify'],collocations:['strongly imply','imply that','implied meaning'],tip:'"Imply" (người nói) vs "Infer" (người nghe). IELTS Reading thường hỏi "What is implied?"'},

  // NEW: WORK & SUCCESS
  {w:'competent',p:'/ˈkɒmpɪtənt/',type:'adj',band:'B2',usage:'formal',topic:'personality',vi:'có năng lực, giỏi',meanings:[{vi:'có đủ kỹ năng để làm tốt',en:'having the necessary ability or knowledge',ex:[{en:'She is a highly competent manager.',vi:'Cô ấy là quản lý rất có năng lực.'}]}],synonyms:['capable','skilled','proficient','qualified'],antonyms:['incompetent','incapable','unqualified'],collocations:['highly competent','competent enough','competent professional'],tip:'"Competence" (n) = năng lực. "Core competencies" = năng lực cốt lõi.'},
  {w:'initiative',p:'/ɪˈnɪʃətɪv/',type:'n',band:'B1',usage:'daily',topic:'personality',vi:'sáng kiến, sự chủ động',meanings:[{vi:'khả năng tự quyết định và hành động',en:'the ability to act independently',ex:[{en:'She showed great initiative.',vi:'Cô ấy thể hiện sáng kiến tuyệt vời.'}]}],synonyms:['enterprise','drive','resourcefulness','inventiveness'],antonyms:['passivity','dependence'],collocations:['take the initiative','show initiative','own initiative'],tip:'"Take the initiative" = chủ động hành động. Employers love this quality.'},
  {w:'delegate',p:'/ˈdelɪɡeɪt/',type:'v',band:'B2',usage:'formal',topic:'relate',vi:'giao phó, ủy quyền',meanings:[{vi:'giao nhiệm vụ cho người khác',en:'to entrust a task to another person',ex:[{en:'Good managers know how to delegate.',vi:'Quản lý giỏi biết cách giao phó công việc.'}]}],synonyms:['assign','entrust','hand over','allocate'],antonyms:['micromanage','do yourself'],collocations:['delegate tasks','delegate authority','delegate responsibility'],tip:'"Delegate effectively" = key management skill. "Delegation" (n).'},
  {w:'thrive',p:'/θraɪv/',type:'v',band:'B2',usage:'daily',topic:'change',vi:'phát triển mạnh, thịnh vượng',meanings:[{vi:'phát triển tốt và thành công',en:'to prosper; to grow vigorously',ex:[{en:'Children thrive in a supportive environment.',vi:'Trẻ em phát triển mạnh trong môi trường hỗ trợ.'}]}],synonyms:['flourish','prosper','bloom','succeed'],antonyms:['decline','wither','struggle','stagnate'],collocations:['thrive in','thrive on challenges','thriving business'],tip:'"Thrive on challenges" = phát triển nhờ thử thách. Very positive word.'},
  {w:'aspire',p:'/əˈspaɪər/',type:'v',band:'B2',usage:'formal',topic:'change',vi:'khao khát, mong ước',meanings:[{vi:'mong muốn đạt được điều gì lớn lao',en:'to have a strong desire to achieve something',ex:[{en:'She aspires to become a doctor.',vi:'Cô ấy khao khát trở thành bác sĩ.'}]}],synonyms:['aim','desire','strive','dream of'],antonyms:['settle','give up'],collocations:['aspire to','aspiring writer','aspiration'],tip:'"Aspiring" = đang mong ước trở thành. "An aspiring musician."'},
  {w:'benchmark',p:'/ˈbentʃmɑːrk/',type:'n/v',band:'B2',usage:'formal',topic:'academic',vi:'tiêu chuẩn, mốc đánh giá',meanings:[{vi:'tiêu chuẩn để so sánh',en:'a standard against which things may be compared',ex:[{en:'This score serves as a benchmark.',vi:'Điểm số này dùng làm tiêu chuẩn.'}]}],synonyms:['standard','reference point','yardstick','criterion'],antonyms:[],collocations:['set a benchmark','industry benchmark','benchmark against'],tip:'"Set the benchmark" = đặt ra tiêu chuẩn. Business and academic vocabulary.'},

  // NEW: EMOTIONS & FEELINGS
  {w:'devastate',p:'/ˈdevəsteɪt/',type:'v',band:'B2',usage:'daily',topic:'describe',vi:'tàn phá, suy sụp',meanings:[{vi:'phá hủy hoàn toàn hoặc gây sốc lớn',en:'to destroy or cause great shock',ex:[{en:'The community was devastated by the flood.',vi:'Cộng đồng bị tàn phá bởi trận lụt.'}]}],synonyms:['destroy','ruin','wreck','shatter'],antonyms:['rebuild','restore','repair'],collocations:['utterly devastated','devastating news','devastating impact'],tip:'"Devastating" = tàn khốc. "A devastating earthquake/loss."'},
  {w:'gratitude',p:'/ˈɡrætɪtjuːd/',type:'n',band:'B2',usage:'daily',topic:'relate',vi:'lòng biết ơn',meanings:[{vi:'cảm giác cảm kích và biết ơn',en:'the quality of being thankful',ex:[{en:'I want to express my gratitude.',vi:'Tôi muốn bày tỏ lòng biết ơn.'}]}],synonyms:['thankfulness','appreciation','gratefulness'],antonyms:['ingratitude','ungratefulness'],collocations:['express gratitude','deep gratitude','gratitude towards'],tip:'"Express/show gratitude" = bày tỏ biết ơn. IELTS Writing formal closing.'},
  {w:'resentment',p:'/rɪˈzentmənt/',type:'n',band:'B2',usage:'daily',topic:'relate',vi:'sự oán giận, bất mãn',meanings:[{vi:'cảm giác tức giận kéo dài vì bị đối xử bất công',en:'bitter indignation at being treated unfairly',ex:[{en:'There is growing resentment among workers.',vi:'Có sự bất mãn ngày càng tăng trong công nhân.'}]}],synonyms:['bitterness','hostility','grudge','indignation'],antonyms:['forgiveness','acceptance','goodwill'],collocations:['deep resentment','growing resentment','harbour resentment'],tip:'"Harbour resentment" = nuôi dưỡng sự oán giận. Strong negative emotion.'},
  {w:'nostalgia',p:'/nɒˈstældʒə/',type:'n',band:'B2',usage:'daily',topic:'describe',vi:'nỗi nhớ, hoài niệm',meanings:[{vi:'cảm giác nhớ nhung quá khứ',en:'a sentimental longing for the past',ex:[{en:'The song fills me with nostalgia.',vi:'Bài hát khiến tôi tràn đầy hoài niệm.'}]}],synonyms:['longing','wistfulness','reminiscence','sentimentality'],antonyms:['indifference'],collocations:['feel nostalgia','wave of nostalgia','nostalgic for'],tip:'"Nostalgic" (adj). IELTS Speaking Part 2: describe a memory → "It fills me with nostalgia."'},
  {w:'empathise',p:'/ˈempəθaɪz/',type:'v',band:'B2',usage:'daily',topic:'relate',vi:'đồng cảm, thấu cảm',meanings:[{vi:'hiểu và chia sẻ cảm xúc người khác',en:'to understand and share the feelings of another',ex:[{en:'I can empathise with your situation.',vi:'Tôi có thể đồng cảm với tình huống của bạn.'}]}],synonyms:['relate to','identify with','sympathise','understand'],antonyms:['disregard','ignore'],collocations:['empathise with','ability to empathise','deeply empathise'],tip:'"Empathise" (v) vs "empathy" (n). Key emotional intelligence skill.'},

  // NEW: ENVIRONMENT & NATURE
  {w:'sustain',p:'/səˈsteɪn/',type:'v',band:'B1',usage:'formal',topic:'change',vi:'duy trì, hỗ trợ',meanings:[{vi:'giữ cho tiếp tục theo thời gian',en:'to keep going over time',ex:[{en:'Economic growth must be sustained.',vi:'Tăng trưởng kinh tế phải được duy trì.'}]}],synonyms:['maintain','uphold','continue','support'],antonyms:['abandon','neglect','cease'],collocations:['sustain growth','sustain life','sustained effort'],tip:'"Sustained" = kéo dài. "A sustained effort" = nỗ lực bền bỉ. Root of "sustainable".'},
  {w:'curb',p:'/kɜːrb/',type:'v/n',band:'B2',usage:'formal',topic:'problem',vi:'kiềm chế, hạn chế',meanings:[{vi:'kiểm soát hoặc hạn chế',en:'to restrain or keep in check',ex:[{en:'Measures to curb pollution are needed.',vi:'Cần các biện pháp kiềm chế ô nhiễm.'}]}],synonyms:['restrain','control','limit','check'],antonyms:['encourage','promote','stimulate'],collocations:['curb emissions','curb spending','curb inflation'],tip:'IELTS: "curb pollution/emissions" = kiềm chế ô nhiễm/khí thải.'},
  {w:'foster',p:'/ˈfɒstər/',type:'v',band:'B2',usage:'formal',topic:'change',vi:'thúc đẩy, nuôi dưỡng',meanings:[{vi:'khuyến khích phát triển',en:'to encourage or promote the development of',ex:[{en:'Education fosters critical thinking.',vi:'Giáo dục thúc đẩy tư duy phê phán.'}]}],synonyms:['encourage','promote','nurture','cultivate'],antonyms:['discourage','hinder','suppress'],collocations:['foster growth','foster innovation','foster a sense of'],tip:'"Foster" = nuôi dưỡng. "Foster a love of learning" = nuôi dưỡng tình yêu học hỏi.'},
  {w:'safeguard',p:'/ˈseɪfɡɑːrd/',type:'v/n',band:'B2',usage:'formal',topic:'problem',vi:'bảo vệ, biện pháp an toàn',meanings:[{vi:'bảo vệ khỏi nguy hiểm',en:'to protect from harm',ex:[{en:'We must safeguard the environment.',vi:'Chúng ta phải bảo vệ môi trường.'}]}],synonyms:['protect','defend','shield','preserve'],antonyms:['endanger','threaten','neglect'],collocations:['safeguard rights','safeguard the environment','safeguard against'],tip:'"Safeguard" = bảo vệ chủ động. Stronger intention than "protect".'},

  // NEW: TIME & SEQUENCE
  {w:'simultaneously',p:'/ˌsɪməlˈteɪniəsli/',type:'adv',band:'B2',usage:'formal',topic:'quantity',vi:'đồng thời, cùng lúc',meanings:[{vi:'xảy ra cùng một lúc',en:'at the same time',ex:[{en:'Both events occurred simultaneously.',vi:'Cả hai sự kiện xảy ra đồng thời.'}]}],synonyms:['concurrently','at the same time','in parallel'],antonyms:['sequentially','separately'],collocations:['occur simultaneously','simultaneously with','work simultaneously'],tip:'More formal than "at the same time". IELTS Task 1 describing charts.'},
  {w:'subsequently',p:'/ˈsʌbsɪkwəntli/',type:'adv',band:'B2',usage:'formal',topic:'cause',vi:'sau đó, tiếp theo',meanings:[{vi:'xảy ra sau một sự kiện khác',en:'after a particular event or time',ex:[{en:'He moved to London and subsequently got a job.',vi:'Anh ấy chuyển đến London và sau đó có việc làm.'}]}],synonyms:['afterwards','later','then','following that'],antonyms:['previously','beforehand','earlier'],collocations:['subsequently found','subsequently revealed','subsequently changed'],tip:'More formal than "then/later". IELTS: "The policy was subsequently revised."'},
  {w:'preliminary',p:'/prɪˈlɪmɪnəri/',type:'adj',band:'B2',usage:'formal',topic:'academic',vi:'sơ bộ, ban đầu',meanings:[{vi:'trước giai đoạn chính, mang tính chuẩn bị',en:'before the main event or stage',ex:[{en:'Preliminary results are promising.',vi:'Kết quả sơ bộ rất hứa hẹn.'}]}],synonyms:['initial','introductory','preparatory','provisional'],antonyms:['final','conclusive','definitive'],collocations:['preliminary results','preliminary study','preliminary investigation'],tip:'"Preliminary findings suggest that..." — academic writing opener.'},
  {w:'duration',p:'/djʊˈreɪʃən/',type:'n',band:'B1',usage:'formal',topic:'quantity',vi:'khoảng thời gian, thời lượng',meanings:[{vi:'khoảng thời gian kéo dài',en:'the length of time something lasts',ex:[{en:'The duration of the course is 6 months.',vi:'Thời lượng khóa học là 6 tháng.'}]}],synonyms:['length','period','span','extent'],antonyms:[],collocations:['for the duration','short duration','duration of stay'],tip:'IELTS Task 1: "over the duration of the period" — formal time phrase.'},
];
