// Từ điển Đời thường 3 — Data file
// 10 chủ đề mới: environment, psychology, education, crime, politics, sports, arts, genz, housing, relationships

const WORDS3 = [
// ═══ ENVIRONMENT & CLIMATE ═══
{w:'renewable',p:'/rɪˈnjuːəbl/',type:'adj',band:'B1',usage:'daily',topic:'environment',vi:'tái tạo được',meanings:[{vi:'có thể tái tạo, không cạn kiệt',en:'able to be replaced naturally and not used up',ex:[{en:'Solar power is a renewable energy source.',vi:'Năng lượng mặt trời là nguồn năng lượng tái tạo.'},{en:'We must invest in renewable resources.',vi:'Chúng ta phải đầu tư vào tài nguyên tái tạo.'}]}],synonyms:['sustainable','green','clean','inexhaustible'],antonyms:['non-renewable','fossil','finite'],collocations:['renewable energy','renewable resources','renewable sources'],tip:'Đối lập: renewable ↔ non-renewable (fossil fuels). IELTS Writing must-know.'},
{w:'endangered',p:'/ɪnˈdeɪndʒərd/',type:'adj',band:'B1',usage:'daily',topic:'environment',vi:'có nguy cơ tuyệt chủng',meanings:[{vi:'loài đang bị đe dọa tuyệt chủng',en:'at risk of extinction',ex:[{en:'Tigers are an endangered species.',vi:'Hổ là loài có nguy cơ tuyệt chủng.'},{en:'We must protect endangered animals.',vi:'Chúng ta phải bảo vệ động vật có nguy cơ tuyệt chủng.'}]}],synonyms:['threatened','at risk','vulnerable'],antonyms:['thriving','abundant','safe'],collocations:['endangered species','critically endangered','endangered wildlife'],tip:'"Endangered species" = loài có nguy cơ tuyệt chủng. Band 7+ vocabulary.'},
{w:'recycle',p:'/riːˈsaɪkl/',type:'v',band:'A2',usage:'daily',topic:'environment',vi:'tái chế',meanings:[{vi:'xử lý rác thải để tái sử dụng',en:'to convert waste into reusable material',ex:[{en:'We should recycle plastic and paper.',vi:'Chúng ta nên tái chế nhựa và giấy.'},{en:'Only 9% of plastic is actually recycled.',vi:'Chỉ 9% nhựa thực sự được tái chế.'}]}],synonyms:['reuse','repurpose','reclaim'],antonyms:['waste','dispose','discard'],collocations:['recycle waste','recycling bin','recycling rate','recyclable materials'],tip:'3Rs: Reduce, Reuse, Recycle — thứ tự ưu tiên. Reduce là quan trọng nhất.'},
{w:'extinction',p:'/ɪkˈstɪŋkʃn/',type:'n',band:'B2',usage:'formal',topic:'environment',vi:'sự tuyệt chủng',meanings:[{vi:'sự biến mất hoàn toàn của một loài',en:'the state of no longer existing',ex:[{en:'Many species face extinction due to habitat loss.',vi:'Nhiều loài đối mặt tuyệt chủng do mất môi trường sống.'},{en:'The dodo went extinct in the 17th century.',vi:'Chim dodo tuyệt chủng vào thế kỷ 17.'}]}],synonyms:['dying out','disappearance','annihilation'],antonyms:['survival','conservation','preservation'],collocations:['mass extinction','face extinction','risk of extinction','drive to extinction'],tip:'"Mass extinction" = tuyệt chủng hàng loạt. Trái Đất đã trải qua 5 lần, lần thứ 6 đang diễn ra.'},
{w:'waste',p:'/weɪst/',type:'n/v',band:'A2',usage:'daily',topic:'environment',vi:'rác thải, lãng phí',meanings:[{vi:'rác, đồ bỏ đi',en:'unwanted or unusable materials',ex:[{en:'Plastic waste pollutes the oceans.',vi:'Rác thải nhựa ô nhiễm đại dương.'},{en:'Don\'t waste water.',vi:'Đừng lãng phí nước.'}]}],synonyms:['rubbish','garbage','trash','refuse'],antonyms:['resource','treasure'],collocations:['waste management','waste disposal','food waste','toxic waste','waste reduction'],tip:'"Waste" vừa là danh từ (rác) vừa là động từ (lãng phí). "Food waste" = lãng phí thực phẩm.'},
{w:'solar energy',p:'/ˈsoʊlər ˈenərdʒi/',type:'n',band:'A2',usage:'daily',topic:'environment',vi:'năng lượng mặt trời',meanings:[{vi:'năng lượng thu được từ ánh sáng mặt trời',en:'energy from the sun converted into electricity',ex:[{en:'Solar energy is becoming more affordable.',vi:'Năng lượng mặt trời ngày càng phải chăng hơn.'},{en:'Many countries invest heavily in solar energy.',vi:'Nhiều quốc gia đầu tư mạnh vào năng lượng mặt trời.'}]}],synonyms:['solar power','photovoltaic energy','sun power'],antonyms:['fossil fuel','coal power'],collocations:['solar panels','solar farm','solar-powered','harness solar energy'],tip:'"Solar panels" = tấm pin mặt trời. "Harness solar energy" = khai thác NLMT — academic vocabulary.'},

// ═══ PSYCHOLOGY & MENTAL HEALTH ═══
{w:'cope',p:'/koʊp/',type:'v',band:'B1',usage:'daily',topic:'psychology',vi:'đối phó, xoay sở',meanings:[{vi:'xử lý tình huống khó khăn',en:'to deal effectively with something difficult',ex:[{en:'How do you cope with stress?',vi:'Bạn đối phó với stress như thế nào?'},{en:'She struggled to cope after losing her job.',vi:'Cô ấy vật lộn để xoay sở sau khi mất việc.'}]}],synonyms:['manage','handle','deal with','endure','get through'],antonyms:['struggle','collapse','give up'],collocations:['cope with stress','cope with loss','coping mechanism','unable to cope'],tip:'"Coping mechanism" = cơ chế đối phó — thuật ngữ tâm lý học quan trọng.'},
{w:'toxic',p:'/ˈtɒksɪk/',type:'adj',band:'B1',usage:'daily',topic:'psychology',vi:'độc hại (cả nghĩa bóng)',meanings:[{vi:'gây hại cho sức khỏe thể chất hoặc tinh thần',en:'poisonous; very harmful or unpleasant',ex:[{en:'She left a toxic relationship.',vi:'Cô ấy rời khỏi mối quan hệ độc hại.'},{en:'Social media can create a toxic environment.',vi:'Mạng xã hội có thể tạo ra môi trường độc hại.'}]}],synonyms:['poisonous','harmful','destructive','damaging','unhealthy'],antonyms:['healthy','positive','nurturing','supportive'],collocations:['toxic relationship','toxic workplace','toxic behavior','toxic masculinity'],tip:'"Toxic" nghĩa bóng rất phổ biến Gen Z: "toxic relationship/workplace/behavior".'},
{w:'boundary',p:'/ˈbaʊndəri/',type:'n',band:'B1',usage:'daily',topic:'psychology',vi:'ranh giới, giới hạn',meanings:[{vi:'giới hạn cá nhân mà người khác không nên vượt qua',en:'a limit of acceptable behavior; a dividing line',ex:[{en:'It\'s important to set boundaries in relationships.',vi:'Quan trọng phải đặt ranh giới trong các mối quan hệ.'},{en:'She learned to set healthy boundaries.',vi:'Cô ấy học cách đặt ranh giới lành mạnh.'}]}],synonyms:['limit','border','line','threshold'],antonyms:[],collocations:['set boundaries','personal boundaries','healthy boundaries','cross a boundary'],tip:'"Set boundaries" = đặt ranh giới — kỹ năng sống quan trọng được nhắc nhiều trong tâm lý học.'},
{w:'vulnerable',p:'/ˈvʌlnərəbl/',type:'adj',band:'B2',usage:'daily',topic:'psychology',vi:'dễ bị tổn thương, mong manh',meanings:[{vi:'dễ bị ảnh hưởng bởi tác động xấu',en:'susceptible to physical or emotional harm',ex:[{en:'Children are particularly vulnerable to stress.',vi:'Trẻ em đặc biệt dễ bị tổn thương bởi stress.'},{en:'Being vulnerable is not a weakness.',vi:'Dễ bị tổn thương không phải là yếu đuối.'}]}],synonyms:['exposed','susceptible','fragile','at risk','defenseless'],antonyms:['resilient','strong','protected','invulnerable'],collocations:['vulnerable groups','emotionally vulnerable','vulnerable to attack'],tip:'"Vulnerability" — Brené Brown khiến từ này nổi tiếng: showing vulnerability = showing courage.'},
{w:'overwhelm',p:'/ˌoʊvərˈwelm/',type:'v',band:'B1',usage:'daily',topic:'psychology',vi:'choáng ngợp, quá tải',meanings:[{vi:'cảm thấy quá nhiều, không xử lý nổi',en:'to be too much to deal with; to overpower',ex:[{en:'She was overwhelmed by work.',vi:'Cô ấy bị quá tải bởi công việc.'},{en:'Don\'t let stress overwhelm you.',vi:'Đừng để stress choáng ngợp bạn.'}]}],synonyms:['overpower','swamp','flood','overload','crush'],antonyms:['underwhelm','manage','handle'],collocations:['feel overwhelmed','overwhelmed with work','overwhelmed by emotions'],tip:'"I feel overwhelmed" = tôi cảm thấy quá tải — rất phổ biến trong giao tiếp hàng ngày.'},
{w:'well-being',p:'/ˌwel ˈbiːɪŋ/',type:'n',band:'B1',usage:'daily',topic:'psychology',vi:'sức khỏe toàn diện, hạnh phúc',meanings:[{vi:'trạng thái khỏe mạnh và hạnh phúc tổng thể',en:'the state of being comfortable, healthy, and happy',ex:[{en:'Exercise improves your overall well-being.',vi:'Tập thể dục cải thiện sức khỏe toàn diện.'},{en:'Employers should care about employee well-being.',vi:'Nhà tuyển dụng nên quan tâm đến sức khỏe nhân viên.'}]}],synonyms:['welfare','health','happiness','wellness','prosperity'],antonyms:['suffering','misery','illness'],collocations:['mental well-being','physical well-being','overall well-being','sense of well-being'],tip:'"Well-being" bao gồm cả thể chất + tinh thần + xã hội. Rộng hơn "health".'},
{w:'insomnia',p:'/ɪnˈsɒmniə/',type:'n',band:'B2',usage:'daily',topic:'psychology',vi:'mất ngủ',meanings:[{vi:'tình trạng khó ngủ hoặc không ngủ được',en:'habitual inability to sleep',ex:[{en:'Stress often causes insomnia.',vi:'Stress thường gây mất ngủ.'},{en:'She has suffered from insomnia for years.',vi:'Cô ấy bị mất ngủ nhiều năm.'}]}],synonyms:['sleeplessness','wakefulness','restlessness'],antonyms:['drowsiness','sleepiness'],collocations:['chronic insomnia','suffer from insomnia','treat insomnia'],tip:'"Insomnia" chuyên ngành hơn "can\'t sleep". Dùng trong IELTS health/lifestyle topics.'},
{w:'addiction',p:'/əˈdɪkʃn/',type:'n',band:'B1',usage:'daily',topic:'psychology',vi:'nghiện, sự nghiện',meanings:[{vi:'trạng thái phụ thuộc vào một chất hoặc hành vi',en:'the state of being dependent on a substance or activity',ex:[{en:'Phone addiction is a growing concern.',vi:'Nghiện điện thoại là mối lo ngày càng tăng.'},{en:'Addiction recovery requires support.',vi:'Hồi phục từ nghiện cần sự hỗ trợ.'}]}],synonyms:['dependence','habit','obsession','compulsion'],antonyms:['sobriety','self-control','moderation'],collocations:['social media addiction','addiction recovery','addiction treatment','struggle with addiction'],tip:'"Addicted to" + noun/gerund. "Phone/social media addiction" — rất relevant cho IELTS technology topics.'},
{w:'perfectionism',p:'/pərˈfekʃənɪzm/',type:'n',band:'B2',usage:'formal',topic:'psychology',vi:'chủ nghĩa cầu toàn',meanings:[{vi:'xu hướng đòi hỏi mọi thứ phải hoàn hảo',en:'the refusal to accept any standard short of perfection',ex:[{en:'Perfectionism can lead to burnout.',vi:'Chủ nghĩa cầu toàn có thể dẫn đến kiệt sức.'},{en:'Healthy vs unhealthy perfectionism.',vi:'Cầu toàn lành mạnh vs không lành mạnh.'}]}],synonyms:['meticulousness','exactness','high standards'],antonyms:['sloppiness','carelessness'],collocations:['toxic perfectionism','overcome perfectionism','perfectionist tendencies'],tip:'"Perfectionism" có mặt tốt (high standards) và xấu (never satisfied). IELTS nuanced topic.'},

// ═══ EDUCATION ═══
{w:'graduate',p:'/ˈɡrædʒueɪt/',type:'v/n',band:'A2',usage:'daily',topic:'education',vi:'tốt nghiệp / cử nhân',meanings:[{vi:'hoàn thành khóa học và nhận bằng',en:'to complete a course of study and receive a degree',ex:[{en:'She graduated from university last year.',vi:'Cô ấy tốt nghiệp đại học năm ngoái.'},{en:'Many graduates struggle to find jobs.',vi:'Nhiều cử nhân vật lộn tìm việc.'}]}],synonyms:['complete','finish','qualify'],antonyms:['drop out','fail'],collocations:['graduate from','recent graduate','graduate school','post-graduate'],tip:'"Graduate from" (không dùng "graduate at"). "Postgraduate" = sau đại học.'},
{w:'semester',p:'/sɪˈmestər/',type:'n',band:'A2',usage:'daily',topic:'education',vi:'học kỳ',meanings:[{vi:'nửa năm học',en:'a half-year term in a school or university',ex:[{en:'There are two semesters per academic year.',vi:'Có hai học kỳ mỗi năm học.'},{en:'I failed two subjects last semester.',vi:'Tôi trượt hai môn học kỳ trước.'}]}],synonyms:['term','quarter','half-year'],antonyms:[],collocations:['fall semester','spring semester','semester break'],tip:'US: "semester" (2/năm). UK: "term" (3/năm). Australia: "semester".'},
{w:'assignment',p:'/əˈsaɪnmənt/',type:'n',band:'A2',usage:'daily',topic:'education',vi:'bài tập, bài giao',meanings:[{vi:'nhiệm vụ học tập được giao',en:'a task or piece of work assigned to someone',ex:[{en:'Submit the assignment by Friday.',vi:'Nộp bài tập trước thứ Sáu.'},{en:'Group assignments develop teamwork skills.',vi:'Bài tập nhóm phát triển kỹ năng làm việc nhóm.'}]}],synonyms:['task','homework','project','coursework'],antonyms:[],collocations:['submit an assignment','group assignment','assignment deadline'],tip:'"Assignment" formal hơn "homework". Dùng ở đại học nhiều hơn.'},
{w:'dropout',p:'/ˈdrɒpaʊt/',type:'n',band:'B1',usage:'daily',topic:'education',vi:'người bỏ học',meanings:[{vi:'người rời trường trước khi hoàn thành chương trình',en:'a person who has left school or university without finishing',ex:[{en:'The dropout rate is alarmingly high.',vi:'Tỷ lệ bỏ học đáng báo động cao.'},{en:'Some famous dropouts became billionaires.',vi:'Một số người bỏ học nổi tiếng đã trở thành tỷ phú.'}]}],synonyms:['quitter','leaver'],antonyms:['graduate','completer'],collocations:['school dropout','dropout rate','high school dropout','college dropout'],tip:'"Drop out of school" (v) → "dropout" (n). Steve Jobs, Bill Gates đều là dropouts.'},
{w:'enroll',p:'/ɪnˈroʊl/',type:'v',band:'B1',usage:'daily',topic:'education',vi:'ghi danh, đăng ký học',meanings:[{vi:'đăng ký tham gia khóa học hoặc trường',en:'to officially register for a course or institution',ex:[{en:'She enrolled in an online course.',vi:'Cô ấy đăng ký một khóa học trực tuyến.'},{en:'Enrollment opens in August.',vi:'Đăng ký mở vào tháng Tám.'}]}],synonyms:['register','sign up','join','enter'],antonyms:['withdraw','drop out','unenroll'],collocations:['enroll in a course','enrollment rate','open enrollment'],tip:'"Enroll in" (không dùng "enroll to"). UK spelling: "enrol". US: "enroll".'},
{w:'campus',p:'/ˈkæmpəs/',type:'n',band:'A2',usage:'daily',topic:'education',vi:'khuôn viên trường',meanings:[{vi:'khu vực đất và tòa nhà của trường',en:'the grounds and buildings of a university or college',ex:[{en:'The campus has a beautiful library.',vi:'Khuôn viên trường có thư viện đẹp.'},{en:'Students live on campus.',vi:'Sinh viên sống trong khuôn viên trường.'}]}],synonyms:['grounds','site','university grounds'],antonyms:[],collocations:['on campus','off campus','campus life','campus tour'],tip:'"On campus" = trong trường. "Off campus" = ngoài trường. "Campus life" = đời sống sinh viên.'},

// ═══ CRIME & LAW ═══
{w:'suspect',p:'/ˈsʌspekt/',type:'n/v',band:'B1',usage:'daily',topic:'crime',vi:'nghi phạm / nghi ngờ',meanings:[{vi:'người bị nghi là phạm tội; nghi ngờ ai đó',en:'a person thought to be guilty; to think something is likely',ex:[{en:'The police arrested a suspect.',vi:'Cảnh sát bắt giữ một nghi phạm.'},{en:'I suspect he is lying.',vi:'Tôi nghi anh ta đang nói dối.'}]}],synonyms:['accused','perpetrator','alleged','doubt'],antonyms:['trust','believe','victim'],collocations:['prime suspect','suspect of','under suspicion','main suspect'],tip:'Phát âm khác nhau: "SUSpect" (n) vs "susPECT" (v). Stress thay đổi theo loại từ!'},
{w:'witness',p:'/ˈwɪtnəs/',type:'n/v',band:'B1',usage:'daily',topic:'crime',vi:'nhân chứng / chứng kiến',meanings:[{vi:'người nhìn thấy sự việc xảy ra',en:'a person who sees an event happen',ex:[{en:'The witness described the accident.',vi:'Nhân chứng mô tả vụ tai nạn.'},{en:'Did anyone witness the robbery?',vi:'Có ai chứng kiến vụ cướp không?'}]}],synonyms:['observer','bystander','onlooker','testifier'],antonyms:[],collocations:['eyewitness','key witness','witness statement','bear witness'],tip:'"Eyewitness" = nhân chứng trực tiếp. "Bear witness to" = chứng kiến/xác nhận (formal).'},
{w:'arrest',p:'/əˈrest/',type:'v/n',band:'B1',usage:'daily',topic:'crime',vi:'bắt giữ',meanings:[{vi:'cảnh sát bắt giữ người nghi phạm',en:'to seize someone by legal authority',ex:[{en:'The police arrested three people.',vi:'Cảnh sát bắt giữ ba người.'},{en:'He was under arrest for fraud.',vi:'Anh ta bị bắt vì tội gian lận.'}]}],synonyms:['detain','apprehend','seize','capture'],antonyms:['release','free','liberate'],collocations:['under arrest','arrest warrant','arrested for','make an arrest'],tip:'"Under arrest" = đang bị bắt. "Arrest warrant" = lệnh bắt giữ.'},
{w:'trial',p:'/ˈtraɪəl/',type:'n',band:'B1',usage:'daily',topic:'crime',vi:'phiên tòa, xét xử',meanings:[{vi:'quá trình xét xử tại tòa án',en:'a judicial examination of issues in a court',ex:[{en:'The trial lasted three weeks.',vi:'Phiên tòa kéo dài ba tuần.'},{en:'He was found guilty at trial.',vi:'Anh ta bị kết tội tại phiên tòa.'}]}],synonyms:['hearing','court case','prosecution','lawsuit'],antonyms:['acquittal','dismissal'],collocations:['stand trial','fair trial','trial by jury','on trial'],tip:'"Trial" cũng có nghĩa "thử nghiệm": "clinical trial" = thử nghiệm lâm sàng.'},
{w:'guilty',p:'/ˈɡɪlti/',type:'adj',band:'A2',usage:'daily',topic:'crime',vi:'có tội, tội lỗi',meanings:[{vi:'bị kết tội; cảm thấy hối hận',en:'responsible for a crime; feeling remorse',ex:[{en:'The jury found him guilty.',vi:'Bồi thẩm đoàn tuyên anh ta có tội.'},{en:'I feel guilty about lying.',vi:'Tôi cảm thấy tội lỗi vì nói dối.'}]}],synonyms:['culpable','responsible','at fault','convicted'],antonyms:['innocent','not guilty','blameless'],collocations:['plead guilty','found guilty','guilty verdict','feel guilty'],tip:'"Plead guilty" = nhận tội. "Not guilty" = vô tội. "Guilty pleasure" = thú vui bí mật (không xấu).'},
{w:'innocent',p:'/ˈɪnəsnt/',type:'adj',band:'A2',usage:'daily',topic:'crime',vi:'vô tội, ngây thơ',meanings:[{vi:'không phạm tội; không biết gì về điều xấu',en:'not guilty of a crime; free from moral wrong',ex:[{en:'He was proved innocent.',vi:'Anh ta được chứng minh vô tội.'},{en:'Innocent civilians were affected.',vi:'Thường dân vô tội bị ảnh hưởng.'}]}],synonyms:['not guilty','blameless','guiltless','naive'],antonyms:['guilty','culpable','responsible'],collocations:['prove innocent','innocent victim','presumed innocent','innocent bystander'],tip:'"Presumed innocent until proven guilty" = nguyên tắc suy đoán vô tội — nền tảng pháp luật.'},
{w:'theft',p:'/θeft/',type:'n',band:'B1',usage:'daily',topic:'crime',vi:'trộm cắp',meanings:[{vi:'hành vi lấy đồ của người khác mà không có phép',en:'the action of stealing someone\'s property',ex:[{en:'Car theft is common in this area.',vi:'Trộm xe phổ biến trong khu vực này.'},{en:'She reported the theft to the police.',vi:'Cô ấy báo vụ trộm cho cảnh sát.'}]}],synonyms:['stealing','robbery','burglary','larceny'],antonyms:[],collocations:['identity theft','car theft','petty theft','report a theft'],tip:'"Theft" vs "robbery": theft = trộm (không dùng vũ lực). Robbery = cướp (có đe dọa/bạo lực).'},
{w:'bribe',p:'/braɪb/',type:'n/v',band:'B2',usage:'daily',topic:'crime',vi:'hối lộ',meanings:[{vi:'đưa tiền hoặc quà để mua chuộc',en:'to give money or gifts to someone in a position of trust to gain an unfair advantage',ex:[{en:'Officials were accused of taking bribes.',vi:'Các quan chức bị cáo buộc nhận hối lộ.'},{en:'Bribery is a serious crime.',vi:'Hối lộ là tội nghiêm trọng.'}]}],synonyms:['payoff','kickback','incentive','sweetener'],antonyms:[],collocations:['take a bribe','offer a bribe','bribery and corruption','anti-bribery'],tip:'"Bribery and corruption" = hối lộ và tham nhũng — cặp từ thường đi cùng nhau.'},
{w:'sentence',p:'/ˈsentəns/',type:'n/v',band:'B1',usage:'daily',topic:'crime',vi:'bản án / kết án',meanings:[{vi:'hình phạt do tòa án quyết định',en:'the punishment given by a court of law',ex:[{en:'He received a five-year prison sentence.',vi:'Anh ta nhận bản án 5 năm tù.'},{en:'She was sentenced to community service.',vi:'Cô ấy bị kết án lao động công ích.'}]}],synonyms:['punishment','verdict','penalty','judgement'],antonyms:['acquittal','pardon'],collocations:['prison sentence','life sentence','death sentence','serve a sentence'],tip:'"Sentence" = cả "câu" lẫn "bản án". "Life sentence" = tù chung thân. "Death sentence" = tử hình.'},
{w:'smuggle',p:'/ˈsmʌɡl/',type:'v',band:'B2',usage:'daily',topic:'crime',vi:'buôn lậu',meanings:[{vi:'vận chuyển hàng bất hợp pháp qua biên giới',en:'to move goods illegally into or out of a country',ex:[{en:'They smuggled drugs across the border.',vi:'Họ buôn lậu ma túy qua biên giới.'},{en:'Smuggling is a global problem.',vi:'Buôn lậu là vấn đề toàn cầu.'}]}],synonyms:['traffic','bootleg','sneak','run'],antonyms:['import legally','declare'],collocations:['drug smuggling','smuggle goods','human smuggling','anti-smuggling'],tip:'"Human smuggling/trafficking" = buôn người — vấn đề nhân quyền nghiêm trọng toàn cầu.'},
{w:'corruption',p:'/kəˈrʌpʃn/',type:'n',band:'B1',usage:'daily',topic:'crime',vi:'tham nhũng, sự suy đồi',meanings:[{vi:'hành vi bất chính vì lợi ích cá nhân',en:'dishonest conduct by those in power for personal gain',ex:[{en:'Corruption undermines democracy.',vi:'Tham nhũng phá hoại dân chủ.'},{en:'Anti-corruption campaigns are essential.',vi:'Chiến dịch chống tham nhũng là thiết yếu.'}]}],synonyms:['dishonesty','bribery','graft','fraud'],antonyms:['integrity','honesty','transparency'],collocations:['fight corruption','political corruption','anti-corruption','rampant corruption'],tip:'"Corruption" = tham nhũng. "Corrupt" = tham nhũng (adj/v). IELTS Politics & Society topic.'},

// ═══ POLITICS & SOCIETY ═══
{w:'democracy',p:'/dɪˈmɒkrəsi/',type:'n',band:'B1',usage:'formal',topic:'politics',vi:'dân chủ',meanings:[{vi:'hệ thống chính trị do người dân quyết định',en:'a system of government by the whole population',ex:[{en:'Democracy gives people a voice.',vi:'Dân chủ cho người dân tiếng nói.'},{en:'Many countries are still fighting for democracy.',vi:'Nhiều quốc gia vẫn đang đấu tranh cho dân chủ.'}]}],synonyms:['self-government','republic','freedom'],antonyms:['dictatorship','tyranny','autocracy'],collocations:['democratic society','promote democracy','democracy and freedom'],tip:'"Democracy" = dân chủ. "Democratic" (adj). Đối lập: "autocracy/dictatorship".'},
{w:'election',p:'/ɪˈlekʃn/',type:'n',band:'B1',usage:'daily',topic:'politics',vi:'cuộc bầu cử',meanings:[{vi:'quá trình chọn người lãnh đạo bằng bỏ phiếu',en:'a formal process of choosing a person for office by voting',ex:[{en:'The presidential election is next year.',vi:'Cuộc bầu cử tổng thống vào năm tới.'},{en:'Voter turnout was low in the last election.',vi:'Tỷ lệ cử tri đi bỏ phiếu thấp trong cuộc bầu cử vừa qua.'}]}],synonyms:['vote','poll','ballot','referendum'],antonyms:[],collocations:['general election','election campaign','win an election','election results'],tip:'"General election" = tổng tuyển cử. "By-election" = bầu cử bổ sung.'},
{w:'protest',p:'/ˈproʊtest/',type:'n/v',band:'B1',usage:'daily',topic:'politics',vi:'biểu tình, phản đối',meanings:[{vi:'bày tỏ sự phản đối công khai',en:'a statement or action expressing disapproval',ex:[{en:'Thousands joined the protest.',vi:'Hàng nghìn người tham gia biểu tình.'},{en:'Students protested against tuition increases.',vi:'Sinh viên biểu tình phản đối tăng học phí.'}]}],synonyms:['demonstration','rally','march','objection'],antonyms:['support','approval','endorsement'],collocations:['peaceful protest','protest march','protest against','stage a protest'],tip:'Phát âm: "PROtest" (n) vs "proTEST" (v). "Peaceful protest" = biểu tình ôn hòa.'},
{w:'policy',p:'/ˈpɒləsi/',type:'n',band:'B1',usage:'formal',topic:'politics',vi:'chính sách',meanings:[{vi:'kế hoạch hành động của chính phủ hoặc tổ chức',en:'a course of action adopted by a government or organization',ex:[{en:'The government introduced a new education policy.',vi:'Chính phủ giới thiệu chính sách giáo dục mới.'},{en:'Foreign policy shapes international relations.',vi:'Chính sách đối ngoại định hình quan hệ quốc tế.'}]}],synonyms:['strategy','plan','regulation','guidelines'],antonyms:[],collocations:['government policy','foreign policy','policy reform','implement a policy'],tip:'"Policy" (chính sách) vs "politics" (chính trị) vs "polity" (thể chế). Ba từ khác nhau!'},

// ═══ ARTS & ENTERTAINMENT ═══
{w:'masterpiece',p:'/ˈmɑːstərpiːs/',type:'n',band:'B1',usage:'daily',topic:'arts',vi:'kiệt tác, tuyệt phẩm',meanings:[{vi:'tác phẩm nghệ thuật xuất sắc nhất',en:'a work of outstanding artistry or skill',ex:[{en:'The Mona Lisa is a masterpiece.',vi:'Mona Lisa là một kiệt tác.'},{en:'His latest novel is a modern masterpiece.',vi:'Cuốn tiểu thuyết mới nhất của anh ấy là kiệt tác hiện đại.'}]}],synonyms:['magnum opus','classic','gem','work of art'],antonyms:['failure','flop'],collocations:['literary masterpiece','artistic masterpiece','create a masterpiece'],tip:'"Magnum opus" = kiệt tác đời người (Latin). "Masterpiece" dùng hàng ngày nhiều hơn.'},
{w:'exhibition',p:'/ˌeksɪˈbɪʃn/',type:'n',band:'B1',usage:'daily',topic:'arts',vi:'triển lãm',meanings:[{vi:'sự trưng bày tác phẩm nghệ thuật hoặc hiện vật',en:'a public display of works of art or items of interest',ex:[{en:'The art exhibition attracted thousands of visitors.',vi:'Triển lãm nghệ thuật thu hút hàng nghìn du khách.'},{en:'A photography exhibition opens next week.',vi:'Triển lãm nhiếp ảnh khai mạc tuần tới.'}]}],synonyms:['show','display','exposition','gallery'],antonyms:[],collocations:['art exhibition','photography exhibition','hold an exhibition'],tip:'"Exhibition" (UK) = "exhibit" (US). "Hold/host an exhibition" = tổ chức triển lãm.'},
{w:'blockbuster',p:'/ˈblɒkbʌstər/',type:'n',band:'B1',usage:'daily',topic:'arts',vi:'bom tấn, phim đình đám',meanings:[{vi:'phim hoặc sách rất thành công về thương mại',en:'a movie or book that is very successful commercially',ex:[{en:'Marvel movies are global blockbusters.',vi:'Phim Marvel là những bom tấn toàn cầu.'},{en:'The blockbuster earned $1 billion.',vi:'Bom tấn này kiếm được 1 tỷ đô.'}]}],synonyms:['hit','smash hit','box office success'],antonyms:['flop','bomb','failure'],collocations:['blockbuster movie','summer blockbuster','box office blockbuster'],tip:'"Blockbuster" = phim thu về cả tỷ đô. "Box office flop" = phim thất bại phòng vé.'},
{w:'rehearsal',p:'/rɪˈhɜːrsl/',type:'n',band:'B2',usage:'daily',topic:'arts',vi:'buổi tập dượt, diễn tập',meanings:[{vi:'buổi luyện tập trước khi biểu diễn chính thức',en:'a practice session in preparation for a performance',ex:[{en:'The band had a rehearsal before the concert.',vi:'Ban nhạc có buổi tập dượt trước buổi hòa nhạc.'},{en:'Dress rehearsal is tomorrow.',vi:'Tổng duyệt vào ngày mai.'}]}],synonyms:['practice','run-through','drill','preparation'],antonyms:['performance','show'],collocations:['dress rehearsal','final rehearsal','rehearsal schedule'],tip:'"Dress rehearsal" = tổng duyệt (mặc trang phục chính thức). "Rehearse" = động từ.'},
{w:'compose',p:'/kəmˈpoʊz/',type:'v',band:'B1',usage:'daily',topic:'arts',vi:'sáng tác, soạn nhạc',meanings:[{vi:'tạo ra tác phẩm âm nhạc hoặc văn học',en:'to write or create a work of music or literature',ex:[{en:'Beethoven composed nine symphonies.',vi:'Beethoven sáng tác chín bản giao hưởng.'},{en:'She composed a poem for the competition.',vi:'Cô ấy sáng tác một bài thơ cho cuộc thi.'}]}],synonyms:['write','create','produce','author','pen'],antonyms:[],collocations:['compose music','compose a song','compose a letter','musical composition'],tip:'"Composer" = nhà soạn nhạc. "Composition" = tác phẩm. "Compose yourself" = bình tĩnh lại.'},
{w:'portrait',p:'/ˈpɔːrtrət/',type:'n',band:'B1',usage:'daily',topic:'arts',vi:'bức chân dung',meanings:[{vi:'tranh hoặc ảnh vẽ mặt và thân trên của người',en:'a painting, drawing, or photograph of a person',ex:[{en:'The portrait hangs in the museum.',vi:'Bức chân dung treo trong bảo tàng.'},{en:'She sat for a portrait.',vi:'Cô ấy ngồi để vẽ chân dung.'}]}],synonyms:['painting','picture','likeness','depiction'],antonyms:['landscape'],collocations:['self-portrait','portrait painting','portrait gallery','family portrait'],tip:'"Self-portrait" = tự họa. "Portrait" vs "landscape" (ngang) — cũng dùng cho hướng giấy/ảnh.'},
{w:'lyrics',p:'/ˈlɪrɪks/',type:'n',band:'A2',usage:'daily',topic:'arts',vi:'lời bài hát',meanings:[{vi:'phần chữ trong một bài hát',en:'the words of a song',ex:[{en:'The lyrics are really meaningful.',vi:'Lời bài hát rất ý nghĩa.'},{en:'She writes her own lyrics.',vi:'Cô ấy tự viết lời bài hát.'}]}],synonyms:['words','text','verses','lines'],antonyms:['melody','tune','instrumental'],collocations:['song lyrics','write lyrics','lyricist','lyrics and melody'],tip:'"Lyrics" luôn dùng số nhiều. "Lyricist" = người viết lời. "Melody" = giai điệu.'},

// ═══ HOUSING & REAL ESTATE ═══
{w:'suburb',p:'/ˈsʌbɜːrb/',type:'n',band:'B1',usage:'daily',topic:'housing',vi:'vùng ngoại ô',meanings:[{vi:'khu vực ở bên ngoài trung tâm thành phố',en:'an outlying area of a city, typically residential',ex:[{en:'They moved to the suburbs for more space.',vi:'Họ chuyển ra ngoại ô để có nhiều không gian hơn.'},{en:'Suburban life is quieter.',vi:'Cuộc sống ngoại ô yên tĩnh hơn.'}]}],synonyms:['outskirts','periphery','residential area'],antonyms:['downtown','city center','urban core'],collocations:['live in the suburbs','suburban area','suburb of','suburban lifestyle'],tip:'"Suburbs" = vùng ngoại ô. "Suburban" (adj). "Suburbanization" = quá trình đô thị hóa ngoại ô.'},
{w:'furnished',p:'/ˈfɜːrnɪʃt/',type:'adj',band:'B1',usage:'daily',topic:'housing',vi:'có nội thất',meanings:[{vi:'nhà/phòng đã có sẵn bàn ghế, giường, tủ',en:'equipped with furniture',ex:[{en:'The apartment comes fully furnished.',vi:'Căn hộ có đầy đủ nội thất.'},{en:'Furnished rooms cost more to rent.',vi:'Phòng có nội thất thuê đắt hơn.'}]}],synonyms:['equipped','fitted','appointed'],antonyms:['unfurnished','bare','empty'],collocations:['fully furnished','furnished apartment','furnished room','semi-furnished'],tip:'"Fully furnished" = đầy đủ nội thất. "Unfurnished" = trống, chỉ có tường. Quan trọng khi thuê nhà.'},
{w:'neighborhood',p:'/ˈneɪbərhʊd/',type:'n',band:'A2',usage:'daily',topic:'housing',vi:'khu phố, láng giềng',meanings:[{vi:'khu vực xung quanh nơi bạn sống',en:'the area surrounding someone\'s home',ex:[{en:'It\'s a safe and friendly neighborhood.',vi:'Đây là khu phố an toàn và thân thiện.'},{en:'The neighborhood has good schools.',vi:'Khu phố có trường học tốt.'}]}],synonyms:['area','district','community','locality','vicinity'],antonyms:[],collocations:['quiet neighborhood','residential neighborhood','neighborhood watch','neighborhood association'],tip:'UK: "neighbourhood". US: "neighborhood". "Neighborhood watch" = đội tuần tra khu phố.'},

// ═══ RELATIONSHIPS & FAMILY ═══
{w:'sibling',p:'/ˈsɪblɪŋ/',type:'n',band:'B1',usage:'daily',topic:'relationships',vi:'anh chị em ruột',meanings:[{vi:'anh, chị hoặc em ruột',en:'a brother or sister',ex:[{en:'She has three siblings.',vi:'Cô ấy có ba anh chị em.'},{en:'Sibling rivalry is common.',vi:'Sự ganh đua giữa anh chị em là phổ biến.'}]}],synonyms:['brother','sister','kin'],antonyms:['only child'],collocations:['sibling rivalry','younger sibling','older sibling'],tip:'"Sibling" formal hơn "brother/sister". "Sibling rivalry" = ganh đua anh chị em.'},
{w:'spouse',p:'/spaʊs/',type:'n',band:'B1',usage:'formal',topic:'relationships',vi:'vợ/chồng',meanings:[{vi:'người bạn đời (vợ hoặc chồng)',en:'a husband or wife',ex:[{en:'You may bring your spouse to the event.',vi:'Bạn có thể mang theo vợ/chồng đến sự kiện.'},{en:'Both spouses must sign the document.',vi:'Cả hai vợ chồng phải ký vào tài liệu.'}]}],synonyms:['partner','husband','wife','mate'],antonyms:['ex','stranger'],collocations:['spouse and children','military spouse','surviving spouse'],tip:'"Spouse" trung tính giới — dùng trong văn bản chính thức thay vì husband/wife.'},
{w:'nurture',p:'/ˈnɜːrtʃər/',type:'v/n',band:'B2',usage:'formal',topic:'relationships',vi:'nuôi dưỡng, chăm sóc',meanings:[{vi:'chăm sóc và khuyến khích phát triển',en:'to care for and encourage growth',ex:[{en:'Parents nurture their children.',vi:'Cha mẹ nuôi dưỡng con cái.'},{en:'We must nurture young talent.',vi:'Chúng ta phải nuôi dưỡng tài năng trẻ.'}]}],synonyms:['raise','cultivate','foster','nourish'],antonyms:['neglect','ignore','abandon'],collocations:['nurture talent','nature vs nurture','nurture growth'],tip:'"Nature vs nurture" = bẩm sinh vs dưỡng dục — debate kinh điển trong tâm lý học.'},
{w:'commitment',p:'/kəˈmɪtmənt/',type:'n',band:'B1',usage:'daily',topic:'relationships',vi:'cam kết, sự tận tụy',meanings:[{vi:'sự cam kết, lời hứa gắn bó',en:'dedication to a cause or relationship',ex:[{en:'Marriage requires commitment.',vi:'Hôn nhân đòi hỏi sự cam kết.'},{en:'She showed great commitment to her work.',vi:'Cô ấy thể hiện sự tận tụy lớn với công việc.'}]}],synonyms:['dedication','devotion','pledge','loyalty'],antonyms:['indifference','neglect'],collocations:['make a commitment','long-term commitment','commitment to'],tip:'"Committed relationship" = mối quan hệ nghiêm túc. "Commitment issues" = sợ gắn bó.'},
{w:'breakup',p:'/ˈbreɪkʌp/',type:'n',band:'A2',usage:'daily',topic:'relationships',vi:'chia tay',meanings:[{vi:'việc kết thúc mối quan hệ tình cảm',en:'the end of a romantic relationship',ex:[{en:'The breakup was painful.',vi:'Việc chia tay rất đau đớn.'},{en:'She is going through a breakup.',vi:'Cô ấy đang trải qua chia tay.'}]}],synonyms:['split','separation','split-up'],antonyms:['reconciliation','reunion','makeup'],collocations:['go through a breakup','messy breakup','breakup song'],tip:'"Break up" (verb) → "breakup" (noun). "They broke up" = họ chia tay.'},
{w:'divorce',p:'/dɪˈvɔːrs/',type:'n/v',band:'B1',usage:'daily',topic:'relationships',vi:'ly hôn',meanings:[{vi:'chấm dứt hôn nhân hợp pháp',en:'the legal ending of a marriage',ex:[{en:'The divorce rate is increasing.',vi:'Tỷ lệ ly hôn đang tăng.'},{en:'They divorced after 10 years.',vi:'Họ ly hôn sau 10 năm.'}]}],synonyms:['separation','split','dissolution'],antonyms:['marriage','wedding','union'],collocations:['divorce rate','file for divorce','get divorced'],tip:'"Divorce rate" = tỷ lệ ly hôn — IELTS Society topic. "File for divorce" = nộp đơn ly hôn.'},
{w:'adoption',p:'/əˈdɒpʃn/',type:'n',band:'B1',usage:'daily',topic:'relationships',vi:'nhận con nuôi, sự áp dụng',meanings:[{vi:'việc nhận và nuôi dưỡng con người khác',en:'the act of legally taking another\'s child as your own',ex:[{en:'Adoption gives children a second chance.',vi:'Nhận con nuôi cho trẻ em cơ hội thứ hai.'},{en:'The adoption process takes months.',vi:'Quá trình nhận con nuôi mất nhiều tháng.'}]}],synonyms:['fostering','guardianship'],antonyms:['abandonment'],collocations:['adoption agency','put up for adoption','adoption process'],tip:'"Adopt" cũng có nghĩa "áp dụng": "adopt a new approach" = áp dụng cách tiếp cận mới.'},
{w:'upbringing',p:'/ˈʌpbrɪŋɪŋ/',type:'n',band:'B2',usage:'daily',topic:'relationships',vi:'sự nuôi dạy, cách giáo dục',meanings:[{vi:'cách cha mẹ nuôi dạy con cái',en:'the way a child is raised and educated',ex:[{en:'Her upbringing shaped her values.',vi:'Cách nuôi dạy đã hình thành giá trị của cô ấy.'},{en:'He had a strict upbringing.',vi:'Anh ấy được nuôi dạy nghiêm khắc.'}]}],synonyms:['childhood','raising','rearing','education'],antonyms:[],collocations:['strict upbringing','sheltered upbringing','humble upbringing'],tip:'"Upbringing" = cách lớn lên. "She had a humble upbringing" = cô ấy lớn lên giản dị.'},

// ═══ SPORTS & FITNESS ═══
{w:'opponent',p:'/əˈpoʊnənt/',type:'n',band:'B1',usage:'daily',topic:'sports',vi:'đối thủ',meanings:[{vi:'người hoặc đội thi đấu chống lại',en:'a person or team competing against another',ex:[{en:'She defeated her opponent easily.',vi:'Cô ấy đánh bại đối thủ dễ dàng.'},{en:'Respect your opponents.',vi:'Tôn trọng đối thủ.'}]}],synonyms:['rival','competitor','adversary','challenger'],antonyms:['teammate','ally','partner'],collocations:['political opponent','tough opponent','face an opponent'],tip:'"Opponent" dùng cả trong thể thao lẫn chính trị: "political opponent" = đối thủ chính trị.'},
{w:'tournament',p:'/ˈtʊrnəmənt/',type:'n',band:'B1',usage:'daily',topic:'sports',vi:'giải đấu',meanings:[{vi:'chuỗi trận đấu để chọn ra người thắng',en:'a series of contests to determine a winner',ex:[{en:'She entered a tennis tournament.',vi:'Cô ấy tham gia giải đấu tennis.'},{en:'The tournament attracted 32 teams.',vi:'Giải đấu thu hút 32 đội.'}]}],synonyms:['competition','championship','contest','event'],antonyms:[],collocations:['tennis tournament','enter a tournament','tournament bracket'],tip:'"Tournament" = nhiều trận. "Match" = một trận. "Fixture" = lịch trận đấu (UK).'},
{w:'defeat',p:'/dɪˈfiːt/',type:'v/n',band:'B1',usage:'daily',topic:'sports',vi:'đánh bại / thất bại',meanings:[{vi:'thắng ai đó trong cuộc thi; sự thua cuộc',en:'to win against someone; a loss',ex:[{en:'They defeated the champions 3-1.',vi:'Họ đánh bại nhà vô địch 3-1.'},{en:'It was a crushing defeat.',vi:'Đó là thất bại nặng nề.'}]}],synonyms:['beat','overcome','conquer','loss'],antonyms:['victory','win','triumph'],collocations:['suffer a defeat','crushing defeat','defeat an opponent','admit defeat'],tip:'"Admit defeat" = thừa nhận thua. "Crushing/humiliating defeat" = thua nhục nhã.'},
{w:'qualify',p:'/ˈkwɒlɪfaɪ/',type:'v',band:'B1',usage:'daily',topic:'sports',vi:'đủ điều kiện, vượt qua vòng loại',meanings:[{vi:'đạt tiêu chuẩn để tham gia',en:'to meet the requirements to compete or participate',ex:[{en:'Vietnam qualified for the World Cup.',vi:'Việt Nam đủ điều kiện tham dự World Cup.'},{en:'She qualified as a doctor.',vi:'Cô ấy đã đủ điều kiện hành nghề bác sĩ.'}]}],synonyms:['eligible','meet criteria','pass','certify'],antonyms:['disqualify','fail','eliminate'],collocations:['qualify for','qualification round','fully qualified'],tip:'"Qualify for" = đủ điều kiện cho. "Disqualified" = bị loại. Dùng cả trong thể thao lẫn nghề nghiệp.'},
{w:'penalty',p:'/ˈpenəlti/',type:'n',band:'B1',usage:'daily',topic:'sports',vi:'phạt đền, hình phạt',meanings:[{vi:'hình phạt vì vi phạm luật; cú đá phạt',en:'a punishment for breaking a rule; a penalty kick in football',ex:[{en:'He scored from a penalty.',vi:'Anh ấy ghi bàn từ quả phạt đền.'},{en:'The penalty for speeding is a fine.',vi:'Hình phạt cho vượt tốc độ là tiền phạt.'}]}],synonyms:['punishment','fine','sanction','free kick'],antonyms:['reward','bonus'],collocations:['penalty kick','death penalty','pay a penalty','penalty shootout'],tip:'"Penalty shootout" = loạt sút luân lưu. "Death penalty" = tử hình — nghĩa hoàn toàn khác!'},
{w:'amateur',p:'/ˈæmətər/',type:'n/adj',band:'B1',usage:'daily',topic:'sports',vi:'nghiệp dư, không chuyên',meanings:[{vi:'người chơi vì đam mê, không phải chuyên nghiệp',en:'a person who does something for pleasure, not as a profession',ex:[{en:'He is an amateur photographer.',vi:'Anh ấy là nhiếp ảnh gia nghiệp dư.'},{en:'Amateur athletes don\'t get paid.',vi:'Vận động viên nghiệp dư không được trả lương.'}]}],synonyms:['hobbyist','non-professional','beginner'],antonyms:['professional','expert','pro'],collocations:['amateur athlete','amateur photographer','amateur mistake'],tip:'"Amateur mistake" = lỗi nghiệp dư (nghĩa bóng, hơi tiêu cực). Phát âm: /ˈæmətər/ không phải /ˈæmətʃʊr/.'},

// ═══ GEN Z & MODERN SLANG ═══
{w:'vibe',p:'/vaɪb/',type:'n/v',band:'A2',usage:'slang',topic:'genz',vi:'cảm giác, bầu không khí',meanings:[{vi:'cảm giác hoặc không khí của một nơi/người',en:'a feeling or atmosphere',ex:[{en:'This café has a great vibe.',vi:'Quán cà phê này có bầu không khí tuyệt.'},{en:'I\'m vibing to this song.',vi:'Tôi đang chill theo bài hát này.'}]}],synonyms:['atmosphere','feeling','energy','mood','aura'],antonyms:['bad energy','negativity'],collocations:['good vibes','bad vibes','vibe check','vibe with'],tip:'"Vibe check" = kiểm tra cảm xúc/năng lượng. "Good vibes only" = chỉ nhận năng lượng tích cực.'},
{w:'slay',p:'/sleɪ/',type:'v',band:'B1',usage:'slang',topic:'genz',vi:'cực đỉnh, làm tốt xuất sắc',meanings:[{vi:'làm điều gì đó xuất sắc, ấn tượng',en:'to do something exceptionally well; to look amazing',ex:[{en:'She slayed that presentation!',vi:'Cô ấy trình bày quá đỉnh!'},{en:'You look amazing — slay queen!',vi:'Bạn trông tuyệt vời — nữ hoàng!'}]}],synonyms:['crush it','nail it','kill it','rock it'],antonyms:['fail','flop','bomb'],collocations:['slay queen','slay the game','absolutely slaying'],tip:'"Slay" gốc = giết (cổ). Gen Z dùng = làm cực đỉnh. "Slay queen!" = khen ai đó tự tin.'},
{w:'flex',p:'/fleks/',type:'v/n',band:'A2',usage:'slang',topic:'genz',vi:'khoe, thể hiện',meanings:[{vi:'khoe khoang thành tích hoặc tài sản',en:'to show off or boast about something',ex:[{en:'He\'s flexing his new car.',vi:'Anh ta đang khoe chiếc xe mới.'},{en:'That\'s a big flex.',vi:'Đó là một cú khoe lớn.'}]}],synonyms:['show off','boast','brag','flaunt'],antonyms:['humble','modest','hide'],collocations:['weird flex','humble flex','flex on someone'],tip:'"Weird flex but okay" = khoe kỳ lạ nhưng ok — meme rất nổi tiếng. "Humble flex" = khoe một cách khiêm tốn.'},
{w:'sus',p:'/sʌs/',type:'adj',band:'A2',usage:'slang',topic:'genz',vi:'đáng ngờ, mờ ám',meanings:[{vi:'đáng nghi, có gì đó không đúng',en:'suspicious or questionable',ex:[{en:'That excuse sounds really sus.',vi:'Cái lý do đó nghe rất đáng ngờ.'},{en:'He\'s been acting sus lately.',vi:'Gần đây anh ta hành xử mờ ám.'}]}],synonyms:['suspicious','shady','sketchy','dodgy'],antonyms:['trustworthy','legit','genuine'],collocations:['acting sus','looking sus','that\'s sus'],tip:'Từ game "Among Us" năm 2020. "Sus" = viết tắt "suspicious". Đã trở thành slang phổ biến.'},
{w:'no cap',p:'/noʊ kæp/',type:'phr',band:'B1',usage:'slang',topic:'genz',vi:'không nói dối, thật đấy',meanings:[{vi:'nói thật, không phóng đại',en:'used to indicate that one is being truthful',ex:[{en:'That movie was amazing, no cap.',vi:'Phim đó hay thật sự, không nói dối.'},{en:'No cap, this is the best pizza ever.',vi:'Thật đấy, đây là pizza ngon nhất từ trước đến giờ.'}]}],synonyms:['for real','honestly','no lie','seriously'],antonyms:['cap','lying','joking'],collocations:['no cap','that\'s cap','cap or no cap'],tip:'"Cap" = nói dối. "No cap" = thật đấy. "That\'s cap!" = Xạo! Rất phổ biến trên TikTok.'},
{w:'FOMO',p:'/ˈfoʊmoʊ/',type:'n',band:'B1',usage:'slang',topic:'genz',vi:'sợ bị bỏ lỡ',meanings:[{vi:'nỗi sợ bị lỡ mất điều gì đó thú vị',en:'Fear Of Missing Out — anxiety about missing fun events',ex:[{en:'I have serious FOMO right now.',vi:'Tôi đang bị FOMO nghiêm trọng.'},{en:'Social media increases FOMO.',vi:'Mạng xã hội làm tăng FOMO.'}]}],synonyms:['fear of missing out','anxiety','envy'],antonyms:['JOMO (joy of missing out)'],collocations:['FOMO-inducing','social media FOMO','have FOMO'],tip:'"JOMO" = Joy Of Missing Out = hạnh phúc vì không tham gia — xu hướng mới đối lập FOMO.'},
{w:'GOAT',p:'/ɡoʊt/',type:'n',band:'A2',usage:'slang',topic:'genz',vi:'huyền thoại, giỏi nhất mọi thời đại',meanings:[{vi:'Greatest Of All Time — người giỏi nhất',en:'Greatest Of All Time — the best ever in their field',ex:[{en:'Messi is the GOAT of football.',vi:'Messi là huyền thoại bóng đá.'},{en:'She is the GOAT, no debate.',vi:'Cô ấy là giỏi nhất, không cần bàn.'}]}],synonyms:['legend','the best','icon','greatest'],antonyms:['worst','amateur','nobody'],collocations:['the GOAT','GOAT status','GOAT debate'],tip:'"GOAT" = viết tắt. Dùng emoji 🐐 thay thế. "Messi or Ronaldo — who is the GOAT?"'},
{w:'ghosting',p:'/ˈɡoʊstɪŋ/',type:'n',band:'B1',usage:'slang',topic:'genz',vi:'bỗng dưng biến mất, cắt liên lạc',meanings:[{vi:'đột ngột ngừng liên lạc mà không giải thích',en:'suddenly cutting off all communication without explanation',ex:[{en:'He ghosted me after three dates.',vi:'Anh ta biến mất sau ba buổi hẹn.'},{en:'Ghosting is rude but common.',vi:'Ghosting là bất lịch sự nhưng phổ biến.'}]}],synonyms:['ignoring','disappearing','cutting off'],antonyms:['communicating','responding','engaging'],collocations:['ghost someone','get ghosted','stop ghosting'],tip:'"Ghost" (v) = biến mất không nói lời nào. Rất phổ biến trong dating culture hiện đại.'},
{w:'glow up',p:'/ɡloʊ ʌp/',type:'n/v',band:'B1',usage:'slang',topic:'genz',vi:'lột xác, thay đổi ngoại hình tốt hơn',meanings:[{vi:'thay đổi ngoại hình hoặc cuộc sống tốt hơn đáng kể',en:'a dramatic positive transformation in appearance or life',ex:[{en:'She had an incredible glow up.',vi:'Cô ấy lột xác không thể tin được.'},{en:'High school glow ups are real.',vi:'Lột xác sau phổ thông là có thật.'}]}],synonyms:['transformation','makeover','upgrade','level up'],antonyms:['glow down','deterioration'],collocations:['major glow up','glow up challenge','incredible glow up'],tip:'"Glow up" = thay đổi tích cực (ngoại hình + tự tin). "Glow down" = ngược lại. Rất viral trên TikTok.'},
{w:'cringe',p:'/krɪndʒ/',type:'adj/n/v',band:'A2',usage:'slang',topic:'genz',vi:'xấu hổ thay, ngại chịu không nổi',meanings:[{vi:'gây cảm giác xấu hổ hoặc khó chịu',en:'causing feelings of embarrassment or awkwardness',ex:[{en:'That video is so cringe.',vi:'Video đó xấu hổ thay quá.'},{en:'I cringed watching his speech.',vi:'Tôi ngại chịu không nổi khi xem bài phát biểu của anh ta.'}]}],synonyms:['embarrassing','awkward','cringeworthy','painful'],antonyms:['cool','smooth','impressive'],collocations:['so cringe','cringe moment','cringeworthy','cringe compilation'],tip:'"Cringe" = vừa adj (that\'s cringe) vừa verb (I cringed). "Cringetopia" = nơi tập trung sự ngại.'},
];
