var IELTS2_EXTRA=[
// ═══ ENVIRONMENT 2 (thêm) ═══
{w:'afforestation',p:'/ˌæfɒrɪˈsteɪʃən/',t:'n',band:'7.5',topic:'env2',skill:'writing',vi:'trồng rừng',ex:'Afforestation helps combat climate change.',exvi:'Trồng rừng giúp chống biến đổi khí hậu.',syn:['reforestation','tree planting','woodland creation'],ielts:'"Afforestation vs deforestation" — IELTS contrast.',col:['afforestation program','urban afforestation','large-scale afforestation']},
{w:'microplastic',p:'/ˈmaɪkroʊˌplæstɪk/',t:'n',band:'7.0',topic:'env2',skill:'reading',vi:'vi nhựa',ex:'Microplastics have been found in drinking water.',exvi:'Vi nhựa đã được tìm thấy trong nước uống.',syn:['plastic particle','micro-pollution'],ielts:'Modern IELTS environment reading.',col:['microplastic pollution','microplastic contamination','microplastic particles']},
{w:'permafrost',p:'/ˈpɜːrməfrɒst/',t:'n',band:'8.0',topic:'env2',skill:'reading',vi:'lớp đất đóng băng vĩnh cửu',ex:'Melting permafrost releases methane gas.',exvi:'Lớp đất đóng băng tan giải phóng khí mê-tan.',syn:['frozen ground','frozen soil'],ielts:'Band 8 — climate science vocabulary.',col:['permafrost thaw','melting permafrost','permafrost region']},
{w:'desertification',p:'/dɪˌzɜːrtɪfɪˈkeɪʃən/',t:'n',band:'7.0',topic:'env2',skill:'writing',vi:'sa mạc hóa',ex:'Desertification threatens food security in Africa.',exvi:'Sa mạc hóa đe dọa an ninh lương thực ở châu Phi.',syn:['land degradation','soil erosion','drought expansion'],ielts:'IELTS Environment: "combat desertification".',col:['combat desertification','prevent desertification','desertification process']},

// ═══ TECHNOLOGY 2 (thêm) ═══
{w:'blockchain',p:'/ˈblɒktʃeɪn/',t:'n',band:'7.0',topic:'tech2',skill:'reading',vi:'chuỗi khối',ex:'Blockchain technology ensures data transparency.',exvi:'Công nghệ chuỗi khối đảm bảo minh bạch dữ liệu.',syn:['distributed ledger','decentralized technology'],ielts:'Modern IELTS technology reading.',col:['blockchain technology','blockchain platform','blockchain-based']},
{w:'biometric',p:'/ˌbaɪoʊˈmetrɪk/',t:'adj/n',band:'7.0',topic:'tech2',skill:'reading',vi:'sinh trắc học',ex:'Biometric data is used for security authentication.',exvi:'Dữ liệu sinh trắc học dùng để xác thực bảo mật.',syn:['biological identification','fingerprint recognition'],ielts:'IELTS: privacy and security topic.',col:['biometric data','biometric authentication','biometric identification']},
{w:'autonomous',p:'/ɔːˈtɒnəməs/',t:'adj',band:'7.0',topic:'tech2',skill:'writing',vi:'tự chủ, tự hành',ex:'Autonomous vehicles may reduce accidents.',exvi:'Xe tự hành có thể giảm tai nạn.',syn:['self-driving','independent','self-governing','automated'],ielts:'"Autonomous vehicles/cars" — hot IELTS tech topic.',col:['autonomous vehicle','autonomous system','fully autonomous']},
{w:'telemedicine',p:'/ˌteləˈmedɪsɪn/',t:'n',band:'7.0',topic:'tech2',skill:'writing',vi:'y tế từ xa',ex:'Telemedicine expanded rapidly during the pandemic.',exvi:'Y tế từ xa mở rộng nhanh chóng trong đại dịch.',syn:['telehealth','remote healthcare','virtual consultation'],ielts:'IELTS Health/Technology crossover.',col:['telemedicine service','telemedicine platform','telemedicine consultation']},

// ═══ SOCIETY 2 (thêm) ═══
{w:'egalitarian',p:'/ɪˌɡælɪˈteəriən/',t:'adj',band:'8.0',topic:'soc2',skill:'writing',vi:'bình đẳng, công bằng',ex:'An egalitarian society treats all citizens equally.',exvi:'Một xã hội bình đẳng đối xử công bằng với mọi công dân.',syn:['equal','equitable','fair','democratic'],ielts:'Band 8 — social equality topic.',col:['egalitarian society','egalitarian principles','egalitarian values']},
{w:'philanthropy',p:'/fɪˈlænθrəpi/',t:'n',band:'7.5',topic:'soc2',skill:'writing',vi:'hoạt động từ thiện',ex:'Philanthropy plays a key role in addressing poverty.',exvi:'Hoạt động từ thiện đóng vai trò then chốt trong giải quyết nghèo đói.',syn:['charity','generosity','benevolence','giving'],ielts:'IELTS: "corporate philanthropy".',col:['corporate philanthropy','philanthropy work','philanthropic efforts']},
{w:'meritocracy',p:'/ˌmerɪˈtɒkrəsi/',t:'n',band:'8.0',topic:'soc2',skill:'writing',vi:'chế độ trọng dụng nhân tài',ex:'Some argue that meritocracy is a myth.',exvi:'Một số người cho rằng chế độ trọng dụng nhân tài là huyền thoại.',syn:['merit-based system','talent-based society'],ielts:'Band 8 — education/society debate.',col:['pure meritocracy','myth of meritocracy','meritocratic system']},
{w:'demographic shift',p:'/ˌdeməˈɡræfɪk ʃɪft/',t:'n',band:'7.0',topic:'soc2',skill:'writing',vi:'thay đổi nhân khẩu học',ex:'Demographic shifts are reshaping the workforce.',exvi:'Thay đổi nhân khẩu học đang định hình lại lực lượng lao động.',syn:['population change','demographic transition'],ielts:'IELTS: population and ageing topic.',col:['major demographic shift','demographic shift towards','respond to demographic shifts']},

// ═══ ECONOMY 2 (thêm) ═══
{w:'gross domestic product',p:'/ɡroʊs dəˈmestɪk ˈprɒdʌkt/',t:'n',band:'7.0',topic:'econ2',skill:'writing',vi:'tổng sản phẩm quốc nội (GDP)',ex:'GDP is the most common measure of economic output.',exvi:'GDP là thước đo phổ biến nhất về sản lượng kinh tế.',syn:['GDP','economic output','national income'],ielts:'IELTS Task 1: graph/chart description.',col:['GDP growth','GDP per capita','GDP ranking']},
{w:'deficit',p:'/ˈdefɪsɪt/',t:'n',band:'7.0',topic:'econ2',skill:'writing',vi:'thâm hụt, thiếu hụt',ex:'The country is running a huge budget deficit.',exvi:'Đất nước đang chạy thâm hụt ngân sách lớn.',syn:['shortfall','gap','deficiency','shortage'],ielts:'IELTS economy: "trade deficit", "budget deficit".',col:['budget deficit','trade deficit','fiscal deficit','deficit spending']},
{w:'monopoly',p:'/məˈnɒpəli/',t:'n',band:'7.0',topic:'econ2',skill:'writing',vi:'độc quyền',ex:'Tech giants have near-monopoly power.',exvi:'Các ông lớn công nghệ có quyền lực gần như độc quyền.',syn:['dominance','control','exclusivity'],ielts:'IELTS: regulation and business topic.',col:['monopoly power','break a monopoly','near-monopoly','state monopoly']},
{w:'outsourcing',p:'/ˈaʊtˌsɔːrsɪŋ/',t:'n',band:'7.0',topic:'econ2',skill:'writing',vi:'thuê ngoài, gia công',ex:'Outsourcing has both economic benefits and social costs.',exvi:'Thuê ngoài có cả lợi ích kinh tế và chi phí xã hội.',syn:['subcontracting','offshoring','delegating'],ielts:'IELTS globalisation/economy topic.',col:['outsourcing jobs','outsourcing overseas','outsourcing strategy']},

// ═══ GOVERNMENT & POLICY (thêm) ═══
{w:'bureaucracy',p:'/bjʊˈrɒkrəsi/',t:'n',band:'7.5',topic:'gov2',skill:'writing',vi:'bộ máy hành chính, quan liêu',ex:'Excessive bureaucracy slows down progress.',exvi:'Bộ máy quan liêu quá mức làm chậm tiến độ.',syn:['red tape','administration','officialdom'],ielts:'IELTS government/efficiency topic.',col:['excessive bureaucracy','government bureaucracy','reduce bureaucracy']},
{w:'sovereignty',p:'/ˈsɒvrɪnti/',t:'n',band:'7.5',topic:'gov2',skill:'writing',vi:'chủ quyền',ex:'National sovereignty must be respected.',exvi:'Chủ quyền quốc gia phải được tôn trọng.',syn:['independence','self-governance','autonomy'],ielts:'IELTS: globalisation vs national sovereignty.',col:['national sovereignty','sovereign state','sovereignty issue']},
{w:'referendum',p:'/ˌrefəˈrendəm/',t:'n',band:'7.5',topic:'gov2',skill:'reading',vi:'trưng cầu dân ý',ex:'The government held a referendum on the issue.',exvi:'Chính phủ tổ chức trưng cầu dân ý về vấn đề này.',syn:['public vote','plebiscite','ballot'],ielts:'IELTS: democracy and government topic.',col:['hold a referendum','national referendum','referendum result']},
{w:'sanction',p:'/ˈsæŋkʃən/',t:'n/v',band:'7.0',topic:'gov2',skill:'reading',vi:'trừng phạt; phê chuẩn',ex:'Economic sanctions were imposed on the country.',exvi:'Các biện pháp trừng phạt kinh tế được áp đặt lên đất nước.',syn:['penalty','punishment','restriction','embargo'],ielts:'IELTS: international relations topic.',col:['economic sanctions','impose sanctions','lift sanctions']},

// ═══ WRITING SKILLS 2 (thêm) ═══
{w:'dichotomy',p:'/daɪˈkɒtəmi/',t:'n',band:'8.0',topic:'writing',skill:'writing',vi:'sự phân đôi, đối lập',ex:'There is a false dichotomy between growth and sustainability.',exvi:'Có sự phân đôi sai lầm giữa tăng trưởng và bền vững.',syn:['division','contrast','split','opposition'],ielts:'Band 8: "false dichotomy" — sophisticated argument tool.',col:['false dichotomy','sharp dichotomy','dichotomy between']},
{w:'empirical',p:'/ɪmˈpɪrɪkəl/',t:'adj',band:'7.5',topic:'writing',skill:'writing',vi:'thực nghiệm, dựa trên kinh nghiệm',ex:'Empirical evidence supports this claim.',exvi:'Bằng chứng thực nghiệm hỗ trợ tuyên bố này.',syn:['experimental','observational','practical','scientific'],ielts:'"Empirical evidence/data" — academic writing.',col:['empirical evidence','empirical research','empirical data','empirical study']},
{w:'extrapolate',p:'/ɪkˈstræpəleɪt/',t:'v',band:'8.0',topic:'writing',skill:'writing',vi:'suy luận từ dữ liệu, ngoại suy',ex:'We cannot extrapolate from such a small sample.',exvi:'Chúng ta không thể suy luận từ mẫu nhỏ như vậy.',syn:['infer','project','estimate','deduce'],ielts:'Band 8: data analysis and argument.',col:['extrapolate from data','extrapolate results','difficult to extrapolate']},
{w:'oversimplify',p:'/ˌoʊvərˈsɪmplɪfaɪ/',t:'v',band:'7.5',topic:'writing',skill:'writing',vi:'đơn giản hóa quá mức',ex:'It would be wrong to oversimplify this issue.',exvi:'Sẽ sai nếu đơn giản hóa quá mức vấn đề này.',syn:['trivialize','reduce','water down'],ielts:'"This argument oversimplifies..." — Band 7.5 critique.',col:['oversimplify the issue','oversimplify the debate','tendency to oversimplify']},
];
