var IELTS1_EXTRA=[
// ═══ ENVIRONMENT (mới) ═══
{w:'ecosystem',p:'/ˈiːkoʊˌsɪstəm/',t:'n',band:'6.5',topic:'environment',skill:'writing',vi:'hệ sinh thái',ex:'Human activities are disrupting natural ecosystems.',exvi:'Hoạt động con người đang phá vỡ hệ sinh thái tự nhiên.',syn:['habitat','biosphere','environment'],ielts:'IELTS Environment topic essential.',col:['marine ecosystem','fragile ecosystem','ecosystem collapse']},
{w:'emission',p:'/ɪˈmɪʃən/',t:'n',band:'6.5',topic:'environment',skill:'writing',vi:'khí thải, sự phát thải',ex:'Countries must reduce carbon emissions.',exvi:'Các quốc gia phải giảm khí thải carbon.',syn:['discharge','output','pollution'],ielts:'"Carbon emissions" — must-know collocation.',col:['carbon emission','greenhouse gas emission','reduce emissions','zero emission']},
{w:'contaminate',p:'/kənˈtæmɪneɪt/',t:'v',band:'7.0',topic:'environment',skill:'writing',vi:'làm ô nhiễm, nhiễm bẩn',ex:'Industrial waste has contaminated the river.',exvi:'Chất thải công nghiệp đã làm ô nhiễm con sông.',syn:['pollute','taint','corrupt','poison'],ielts:'"Contaminate" trang trọng hơn "pollute".',col:['contaminated water','food contamination','soil contamination']},
{w:'conservation',p:'/ˌkɒnsərˈveɪʃən/',t:'n',band:'6.5',topic:'environment',skill:'writing',vi:'bảo tồn',ex:'Wildlife conservation is a global priority.',exvi:'Bảo tồn động vật hoang dã là ưu tiên toàn cầu.',syn:['preservation','protection','safeguarding'],ielts:'IELTS: "conservation efforts/programs".',col:['wildlife conservation','energy conservation','conservation area']},
{w:'drought',p:'/draʊt/',t:'n',band:'6.5',topic:'environment',skill:'reading',vi:'hạn hán',ex:'The region is experiencing a severe drought.',exvi:'Khu vực đang trải qua hạn hán nghiêm trọng.',syn:['dry spell','water shortage','arid period'],ielts:'IELTS Climate topic.',col:['severe drought','prolonged drought','drought-resistant']},
{w:'fossil fuel',p:'/ˈfɒsəl fjuːəl/',t:'n',band:'6.5',topic:'environment',skill:'writing',vi:'nhiên liệu hóa thạch',ex:'We must transition away from fossil fuels.',exvi:'Chúng ta phải chuyển đổi khỏi nhiên liệu hóa thạch.',syn:['coal','petroleum','non-renewable energy'],ielts:'IELTS Environment core phrase.',col:['burn fossil fuels','fossil fuel industry','fossil fuel dependence']},
{w:'carbon footprint',p:'/ˈkɑːrbən ˈfʊtprɪnt/',t:'n',band:'7.0',topic:'environment',skill:'writing',vi:'dấu chân carbon',ex:'Everyone should try to reduce their carbon footprint.',exvi:'Mọi người nên cố gắng giảm dấu chân carbon.',syn:['environmental impact','carbon output'],ielts:'"Reduce one\'s carbon footprint" — Band 7.',col:['reduce carbon footprint','carbon footprint calculator','large carbon footprint']},

// ═══ EDUCATION (mới) ═══
{w:'tuition',p:'/tjuˈɪʃən/',t:'n',band:'6.5',topic:'education',skill:'speaking',vi:'học phí; sự dạy kèm',ex:'University tuition fees keep rising.',exvi:'Học phí đại học liên tục tăng.',syn:['fees','teaching','instruction','coaching'],ielts:'IELTS Speaking/Writing: "tuition fees".',col:['tuition fees','private tuition','tuition-free']},
{w:'scholarship',p:'/ˈskɒlərʃɪp/',t:'n',band:'6.0',topic:'education',skill:'speaking',vi:'học bổng',ex:'She won a full scholarship to Oxford.',exvi:'Cô ấy giành được học bổng toàn phần đến Oxford.',syn:['grant','fellowship','bursary','award'],ielts:'IELTS Speaking Part 2/3.',col:['full scholarship','academic scholarship','scholarship program']},
{w:'dropout',p:'/ˈdrɒpaʊt/',t:'n',band:'7.0',topic:'education',skill:'writing',vi:'người bỏ học',ex:'The dropout rate is alarmingly high.',exvi:'Tỷ lệ bỏ học cao đáng báo động.',syn:['quitter','leaver','non-completer'],ielts:'IELTS Writing: "school dropout rate".',col:['dropout rate','high school dropout','college dropout']},
{w:'pedagogy',p:'/ˈpedəɡɒdʒi/',t:'n',band:'8.0',topic:'education',skill:'writing',vi:'phương pháp sư phạm',ex:'Modern pedagogy emphasises student-centred learning.',exvi:'Phương pháp sư phạm hiện đại nhấn mạnh học tập lấy sinh viên làm trung tâm.',syn:['teaching methods','instruction','didactics'],ielts:'Band 8 academic vocabulary.',col:['modern pedagogy','effective pedagogy','critical pedagogy']},
{w:'rote learning',p:'/roʊt ˈlɜːrnɪŋ/',t:'n',band:'7.0',topic:'education',skill:'writing',vi:'học vẹt, học thuộc lòng',ex:'Rote learning does not develop critical thinking.',exvi:'Học vẹt không phát triển tư duy phản biện.',syn:['memorization','cramming','parrot learning'],ielts:'"Rote learning vs critical thinking" — IELTS debate.',col:['rely on rote learning','rote memorization','move beyond rote learning']},

// ═══ HEALTH (mới) ═══
{w:'pandemic',p:'/pænˈdemɪk/',t:'n/adj',band:'7.0',topic:'health',skill:'reading',vi:'đại dịch',ex:'The pandemic changed how we work.',exvi:'Đại dịch đã thay đổi cách chúng ta làm việc.',syn:['epidemic','outbreak','plague','crisis'],ielts:'Post-COVID IELTS topic.',col:['global pandemic','pandemic response','pandemic era']},
{w:'malnutrition',p:'/ˌmælnjuˈtrɪʃən/',t:'n',band:'7.0',topic:'health',skill:'writing',vi:'suy dinh dưỡng',ex:'Malnutrition affects millions of children worldwide.',exvi:'Suy dinh dưỡng ảnh hưởng hàng triệu trẻ em trên thế giới.',syn:['undernourishment','starvation','hunger'],ielts:'IELTS Health/Development topic.',col:['child malnutrition','combat malnutrition','malnutrition rate']},
{w:'life expectancy',p:'/laɪf ɪkˈspektənsi/',t:'n',band:'6.5',topic:'health',skill:'writing',vi:'tuổi thọ trung bình',ex:'Life expectancy has increased dramatically.',exvi:'Tuổi thọ trung bình đã tăng đáng kể.',syn:['lifespan','longevity'],ielts:'IELTS Task 1 graph description.',col:['average life expectancy','life expectancy at birth','rising life expectancy']},
{w:'preventive',p:'/prɪˈventɪv/',t:'adj',band:'7.0',topic:'health',skill:'writing',vi:'phòng ngừa',ex:'Preventive healthcare saves lives and money.',exvi:'Chăm sóc sức khỏe phòng ngừa cứu sống mạng người và tiết kiệm tiền.',syn:['precautionary','protective','prophylactic'],ielts:'"Preventive measures/healthcare" — Band 7.',col:['preventive measures','preventive medicine','preventive healthcare']},

// ═══ TECHNOLOGY (mới) ═══
{w:'artificial intelligence',p:'/ˌɑːrtɪˈfɪʃəl ɪnˈtelɪdʒəns/',t:'n',band:'7.0',topic:'technology',skill:'writing',vi:'trí tuệ nhân tạo',ex:'Artificial intelligence is transforming industries.',exvi:'Trí tuệ nhân tạo đang chuyển đổi các ngành công nghiệp.',syn:['AI','machine learning','deep learning'],ielts:'Hot IELTS topic.',col:['AI system','AI-powered','AI revolution']},
{w:'cybersecurity',p:'/ˌsaɪbərsɪˈkjʊrəti/',t:'n',band:'7.0',topic:'technology',skill:'reading',vi:'an ninh mạng',ex:'Cybersecurity threats are increasing rapidly.',exvi:'Các mối đe dọa an ninh mạng đang tăng nhanh.',syn:['online security','digital security'],ielts:'Modern IELTS reading topic.',col:['cybersecurity threat','cybersecurity breach','cybersecurity expert']},
{w:'digital divide',p:'/ˈdɪdʒɪtəl dɪˈvaɪd/',t:'n',band:'7.0',topic:'technology',skill:'writing',vi:'khoảng cách số',ex:'The digital divide excludes many from opportunities.',exvi:'Khoảng cách số loại trừ nhiều người khỏi cơ hội.',syn:['technology gap','information gap'],ielts:'IELTS Technology/Society topic.',col:['bridge the digital divide','widen the digital divide','digital inequality']},
{w:'e-commerce',p:'/ˈiːkɒmɜːrs/',t:'n',band:'6.5',topic:'technology',skill:'writing',vi:'thương mại điện tử',ex:'E-commerce has revolutionised shopping.',exvi:'Thương mại điện tử đã cách mạng hóa mua sắm.',syn:['online shopping','digital trade','internet retail'],ielts:'IELTS Technology/Business topic.',col:['e-commerce platform','e-commerce growth','e-commerce industry']},
{w:'data privacy',p:'/ˈdeɪtə ˈprɪvəsi/',t:'n',band:'7.0',topic:'technology',skill:'writing',vi:'quyền riêng tư dữ liệu',ex:'Data privacy laws are becoming stricter.',exvi:'Luật quyền riêng tư dữ liệu đang trở nên nghiêm ngặt hơn.',syn:['information privacy','data protection','personal data security'],ielts:'IELTS: privacy vs convenience debate.',col:['data privacy law','data privacy concern','protect data privacy']},

// ═══ SOCIETY (mới) ═══
{w:'discrimination',p:'/dɪˌskrɪmɪˈneɪʃən/',t:'n',band:'6.5',topic:'society',skill:'writing',vi:'phân biệt đối xử',ex:'Racial discrimination remains a serious issue.',exvi:'Phân biệt chủng tộc vẫn là vấn đề nghiêm trọng.',syn:['prejudice','bias','bigotry','intolerance'],ielts:'IELTS Society topic.',col:['racial discrimination','age discrimination','discrimination against']},
{w:'heritage',p:'/ˈherɪtɪdʒ/',t:'n',band:'6.5',topic:'society',skill:'speaking',vi:'di sản',ex:'We must protect our cultural heritage.',exvi:'Chúng ta phải bảo vệ di sản văn hóa.',syn:['legacy','tradition','inheritance','culture'],ielts:'IELTS Speaking Part 2.',col:['cultural heritage','world heritage','heritage site']},
{w:'assimilation',p:'/əˌsɪmɪˈleɪʃən/',t:'n',band:'7.5',topic:'society',skill:'writing',vi:'đồng hóa, hòa nhập',ex:'Cultural assimilation is a complex process.',exvi:'Đồng hóa văn hóa là quá trình phức tạp.',syn:['integration','absorption','acculturation'],ielts:'IELTS Immigration/Culture topic.',col:['cultural assimilation','forced assimilation','assimilation policy']},
{w:'altruism',p:'/ˈæltruɪzəm/',t:'n',band:'8.0',topic:'society',skill:'writing',vi:'lòng vị tha',ex:'True altruism means helping without expecting anything.',exvi:'Lòng vị tha thực sự là giúp đỡ mà không mong đợi gì.',syn:['selflessness','generosity','philanthropy'],ielts:'Band 8 — psychology/society topic.',col:['pure altruism','act of altruism','altruistic behavior']},
{w:'cohesion',p:'/koʊˈhiːʒən/',t:'n',band:'7.5',topic:'society',skill:'writing',vi:'sự gắn kết',ex:'Social cohesion is essential for a stable society.',exvi:'Sự gắn kết xã hội cần thiết cho xã hội ổn định.',syn:['unity','solidarity','togetherness','harmony'],ielts:'"Social cohesion" — Band 7.5 society.',col:['social cohesion','community cohesion','promote cohesion']},

// ═══ ECONOMY (mới) ═══
{w:'entrepreneur',p:'/ˌɒntrəprəˈnɜːr/',t:'n',band:'7.0',topic:'economy',skill:'speaking',vi:'doanh nhân, người khởi nghiệp',ex:'Young entrepreneurs are driving innovation.',exvi:'Các doanh nhân trẻ đang thúc đẩy đổi mới.',syn:['businessman','founder','innovator'],ielts:'IELTS Speaking: describe an entrepreneur.',col:['serial entrepreneur','social entrepreneur','entrepreneurial spirit']},
{w:'commodity',p:'/kəˈmɒdəti/',t:'n',band:'7.0',topic:'economy',skill:'reading',vi:'hàng hóa, nguyên liệu',ex:'Oil is the world\'s most traded commodity.',exvi:'Dầu mỏ là hàng hóa được giao dịch nhiều nhất thế giới.',syn:['goods','product','raw material','resource'],ielts:'IELTS Reading economy passages.',col:['commodity price','commodity market','commodity trading']},
{w:'fiscal',p:'/ˈfɪskəl/',t:'adj',band:'7.5',topic:'economy',skill:'writing',vi:'thuộc tài chính công, thuộc ngân sách',ex:'The government announced new fiscal policies.',exvi:'Chính phủ công bố chính sách tài chính mới.',syn:['financial','monetary','budgetary','economic'],ielts:'"Fiscal policy" — Band 7.5 economics.',col:['fiscal policy','fiscal year','fiscal deficit','fiscal responsibility']},
{w:'austerity',p:'/ɒˈsterəti/',t:'n',band:'7.5',topic:'economy',skill:'reading',vi:'chính sách thắt lưng buộc bụng',ex:'Austerity measures led to public protests.',exvi:'Các biện pháp thắt lưng buộc bụng dẫn đến biểu tình.',syn:['cutback','frugality','belt-tightening'],ielts:'IELTS Reading economy/politics.',col:['austerity measures','austerity policy','age of austerity']},

// ═══ CRIME & LAW (mới) ═══
{w:'juvenile',p:'/ˈdʒuːvənaɪl/',t:'adj/n',band:'7.0',topic:'crime',skill:'writing',vi:'vị thành niên',ex:'Juvenile crime rates have increased.',exvi:'Tỷ lệ tội phạm vị thành niên đã tăng.',syn:['young','adolescent','minor','teenage'],ielts:'IELTS Crime topic.',col:['juvenile crime','juvenile delinquency','juvenile offender']},
{w:'incarceration',p:'/ɪnˌkɑːrsəˈreɪʃən/',t:'n',band:'8.0',topic:'crime',skill:'writing',vi:'bỏ tù, giam giữ',ex:'Mass incarceration is a controversial policy.',exvi:'Giam giữ hàng loạt là chính sách gây tranh cãi.',syn:['imprisonment','detention','confinement'],ielts:'Band 8: formal alternative to "prison".',col:['mass incarceration','rate of incarceration','incarceration policy']},
{w:'recidivism',p:'/rɪˈsɪdɪvɪzəm/',t:'n',band:'8.0',topic:'crime',skill:'writing',vi:'tái phạm',ex:'High recidivism rates suggest prisons are failing.',exvi:'Tỷ lệ tái phạm cao cho thấy nhà tù đang thất bại.',syn:['reoffending','relapse','repeat offending'],ielts:'Band 8 Crime topic.',col:['recidivism rate','reduce recidivism','high recidivism']},
{w:'white-collar crime',p:'/waɪt ˈkɒlər kraɪm/',t:'n',band:'7.0',topic:'crime',skill:'writing',vi:'tội phạm cổ cồn trắng',ex:'White-collar crime often goes unpunished.',exvi:'Tội phạm cổ cồn trắng thường không bị trừng phạt.',syn:['corporate crime','fraud','financial crime'],ielts:'IELTS Writing crime topic.',col:['commit white-collar crime','white-collar criminal','white-collar fraud']},

// ═══ ACADEMIC WRITING (mới) ═══
{w:'albeit',p:'/ɔːlˈbiːɪt/',t:'conj',band:'7.5',topic:'academic',skill:'writing',vi:'mặc dù, dù rằng',ex:'He accepted the offer, albeit reluctantly.',exvi:'Anh ấy chấp nhận đề nghị, dù miễn cưỡng.',syn:['although','though','even though'],ielts:'Band 7.5 linking word.',col:['albeit slowly','albeit briefly','albeit reluctantly']},
{w:'notwithstanding',p:'/ˌnɒtwɪðˈstændɪŋ/',t:'prep/adv',band:'8.0',topic:'academic',skill:'writing',vi:'mặc dù, bất chấp',ex:'Notwithstanding the difficulties, they succeeded.',exvi:'Bất chấp khó khăn, họ đã thành công.',syn:['despite','in spite of','regardless of'],ielts:'Band 8 formal linker.',col:['notwithstanding the fact','notwithstanding this']},
{w:'underpin',p:'/ˌʌndərˈpɪn/',t:'v',band:'7.5',topic:'academic',skill:'writing',vi:'làm nền tảng, hỗ trợ',ex:'Evidence must underpin any argument.',exvi:'Bằng chứng phải làm nền tảng cho mọi lập luận.',syn:['support','buttress','strengthen','reinforce'],ielts:'"Underpin an argument" — academic writing.',col:['underpin the argument','underpin the theory','values that underpin']},
{w:'corroborate',p:'/kəˈrɒbəreɪt/',t:'v',band:'8.0',topic:'academic',skill:'writing',vi:'chứng thực, xác nhận',ex:'The evidence corroborates the theory.',exvi:'Bằng chứng chứng thực lý thuyết.',syn:['confirm','verify','validate','substantiate'],ielts:'Band 8 academic verb.',col:['corroborate findings','corroborate evidence','corroborate a claim']},
{w:'juxtapose',p:'/ˌdʒʌkstəˈpoʊz/',t:'v',band:'8.0',topic:'academic',skill:'writing',vi:'đặt cạnh nhau để so sánh',ex:'The author juxtaposes tradition with modernity.',exvi:'Tác giả đặt truyền thống cạnh hiện đại để so sánh.',syn:['contrast','compare','place side by side'],ielts:'Band 8 — literary/analytical writing.',col:['juxtapose ideas','juxtapose images','juxtapose with']},
{w:'nuance',p:'/ˈnjuːɑːns/',t:'n',band:'7.5',topic:'academic',skill:'writing',vi:'sắc thái, chi tiết nhỏ',ex:'The essay lacks nuance in its argument.',exvi:'Bài luận thiếu sắc thái trong lập luận.',syn:['subtlety','shade','distinction','refinement'],ielts:'"A nuanced argument" — Band 7.5+.',col:['subtle nuance','nuanced argument','nuanced approach','nuanced understanding']},
{w:'paradox',p:'/ˈpærədɒks/',t:'n',band:'7.0',topic:'academic',skill:'writing',vi:'nghịch lý',ex:'It is a paradox that technology connects yet isolates us.',exvi:'Đó là nghịch lý khi công nghệ kết nối nhưng lại cô lập chúng ta.',syn:['contradiction','anomaly','inconsistency'],ielts:'IELTS: "The paradox of modern life".',col:['apparent paradox','the paradox of','paradoxical situation']},
{w:'paradigm',p:'/ˈpærədaɪm/',t:'n',band:'8.0',topic:'academic',skill:'writing',vi:'mô hình, khuôn mẫu',ex:'A paradigm shift is needed in education.',exvi:'Cần có sự thay đổi mô hình trong giáo dục.',syn:['model','framework','pattern','standard'],ielts:'"Paradigm shift" — Band 8 phrase.',col:['paradigm shift','new paradigm','dominant paradigm']},
];
