var IELTS1_EXTRA=[
// ═══ ENVIRONMENT (mới) ═══
{w:'contaminate',p:'/kənˈtæmɪneɪt/',t:'v',band:'7.0',topic:'environment',skill:'writing',vi:'làm ô nhiễm, nhiễm bẩn',ex:'Industrial waste has contaminated the river.',exvi:'Chất thải công nghiệp đã làm ô nhiễm con sông.',syn:['pollute','taint','corrupt','poison'],ielts:'"Contaminate" trang trọng hơn "pollute".',col:['contaminated water','food contamination','soil contamination']},

// ═══ EDUCATION (mới) ═══
{w:'rote learning',p:'/roʊt ˈlɜːrnɪŋ/',t:'n',band:'7.0',topic:'education',skill:'writing',vi:'học vẹt, học thuộc lòng',ex:'Rote learning does not develop critical thinking.',exvi:'Học vẹt không phát triển tư duy phản biện.',syn:['memorization','cramming','parrot learning'],ielts:'"Rote learning vs critical thinking" — IELTS debate.',col:['rely on rote learning','rote memorization','move beyond rote learning']},

// ═══ HEALTH (mới) ═══
{w:'life expectancy',p:'/laɪf ɪkˈspektənsi/',t:'n',band:'6.5',topic:'health',skill:'writing',vi:'tuổi thọ trung bình',ex:'Life expectancy has increased dramatically.',exvi:'Tuổi thọ trung bình đã tăng đáng kể.',syn:['lifespan','longevity'],ielts:'IELTS Task 1 graph description.',col:['average life expectancy','life expectancy at birth','rising life expectancy']},
{w:'preventive',p:'/prɪˈventɪv/',t:'adj',band:'7.0',topic:'health',skill:'writing',vi:'phòng ngừa',ex:'Preventive healthcare saves lives and money.',exvi:'Chăm sóc sức khỏe phòng ngừa cứu sống mạng người và tiết kiệm tiền.',syn:['precautionary','protective','prophylactic'],ielts:'"Preventive measures/healthcare" — Band 7.',col:['preventive measures','preventive medicine','preventive healthcare']},

// ═══ TECHNOLOGY (mới) ═══
{w:'digital divide',p:'/ˈdɪdʒɪtəl dɪˈvaɪd/',t:'n',band:'7.0',topic:'technology',skill:'writing',vi:'khoảng cách số',ex:'The digital divide excludes many from opportunities.',exvi:'Khoảng cách số loại trừ nhiều người khỏi cơ hội.',syn:['technology gap','information gap'],ielts:'IELTS Technology/Society topic.',col:['bridge the digital divide','widen the digital divide','digital inequality']},
{w:'e-commerce',p:'/ˈiːkɒmɜːrs/',t:'n',band:'6.5',topic:'technology',skill:'writing',vi:'thương mại điện tử',ex:'E-commerce has revolutionised shopping.',exvi:'Thương mại điện tử đã cách mạng hóa mua sắm.',syn:['online shopping','digital trade','internet retail'],ielts:'IELTS Technology/Business topic.',col:['e-commerce platform','e-commerce growth','e-commerce industry']},
{w:'data privacy',p:'/ˈdeɪtə ˈprɪvəsi/',t:'n',band:'7.0',topic:'technology',skill:'writing',vi:'quyền riêng tư dữ liệu',ex:'Data privacy laws are becoming stricter.',exvi:'Luật quyền riêng tư dữ liệu đang trở nên nghiêm ngặt hơn.',syn:['information privacy','data protection','personal data security'],ielts:'IELTS: privacy vs convenience debate.',col:['data privacy law','data privacy concern','protect data privacy']},

// ═══ SOCIETY (mới) ═══
{w:'altruism',p:'/ˈæltruɪzəm/',t:'n',band:'8.0',topic:'society',skill:'writing',vi:'lòng vị tha',ex:'True altruism means helping without expecting anything.',exvi:'Lòng vị tha thực sự là giúp đỡ mà không mong đợi gì.',syn:['selflessness','generosity','philanthropy'],ielts:'Band 8 — psychology/society topic.',col:['pure altruism','act of altruism','altruistic behavior']},

// ═══ ECONOMY (mới) ═══
{w:'fiscal',p:'/ˈfɪskəl/',t:'adj',band:'7.5',topic:'economy',skill:'writing',vi:'thuộc tài chính công, thuộc ngân sách',ex:'The government announced new fiscal policies.',exvi:'Chính phủ công bố chính sách tài chính mới.',syn:['financial','monetary','budgetary','economic'],ielts:'"Fiscal policy" — Band 7.5 economics.',col:['fiscal policy','fiscal year','fiscal deficit','fiscal responsibility']},
{w:'austerity',p:'/ɒˈsterəti/',t:'n',band:'7.5',topic:'economy',skill:'reading',vi:'chính sách thắt lưng buộc bụng',ex:'Austerity measures led to public protests.',exvi:'Các biện pháp thắt lưng buộc bụng dẫn đến biểu tình.',syn:['cutback','frugality','belt-tightening'],ielts:'IELTS Reading economy/politics.',col:['austerity measures','austerity policy','age of austerity']},

// ═══ CRIME & LAW (mới) ═══
{w:'juvenile',p:'/ˈdʒuːvənaɪl/',t:'adj/n',band:'7.0',topic:'crime',skill:'writing',vi:'vị thành niên',ex:'Juvenile crime rates have increased.',exvi:'Tỷ lệ tội phạm vị thành niên đã tăng.',syn:['young','adolescent','minor','teenage'],ielts:'IELTS Crime topic.',col:['juvenile crime','juvenile delinquency','juvenile offender']},
{w:'incarceration',p:'/ɪnˌkɑːrsəˈreɪʃən/',t:'n',band:'8.0',topic:'crime',skill:'writing',vi:'bỏ tù, giam giữ',ex:'Mass incarceration is a controversial policy.',exvi:'Giam giữ hàng loạt là chính sách gây tranh cãi.',syn:['imprisonment','detention','confinement'],ielts:'Band 8: formal alternative to "prison".',col:['mass incarceration','rate of incarceration','incarceration policy']},
{w:'white-collar crime',p:'/waɪt ˈkɒlər kraɪm/',t:'n',band:'7.0',topic:'crime',skill:'writing',vi:'tội phạm cổ cồn trắng',ex:'White-collar crime often goes unpunished.',exvi:'Tội phạm cổ cồn trắng thường không bị trừng phạt.',syn:['corporate crime','fraud','financial crime'],ielts:'IELTS Writing crime topic.',col:['commit white-collar crime','white-collar criminal','white-collar fraud']},

// ═══ ACADEMIC WRITING (mới) ═══
{w:'albeit',p:'/ɔːlˈbiːɪt/',t:'conj',band:'7.5',topic:'academic',skill:'writing',vi:'mặc dù, dù rằng',ex:'He accepted the offer, albeit reluctantly.',exvi:'Anh ấy chấp nhận đề nghị, dù miễn cưỡng.',syn:['although','though','even though'],ielts:'Band 7.5 linking word.',col:['albeit slowly','albeit briefly','albeit reluctantly']},
{w:'notwithstanding',p:'/ˌnɒtwɪðˈstændɪŋ/',t:'prep/adv',band:'8.0',topic:'academic',skill:'writing',vi:'mặc dù, bất chấp',ex:'Notwithstanding the difficulties, they succeeded.',exvi:'Bất chấp khó khăn, họ đã thành công.',syn:['despite','in spite of','regardless of'],ielts:'Band 8 formal linker.',col:['notwithstanding the fact','notwithstanding this']},
{w:'underpin',p:'/ˌʌndərˈpɪn/',t:'v',band:'7.5',topic:'academic',skill:'writing',vi:'làm nền tảng, hỗ trợ',ex:'Evidence must underpin any argument.',exvi:'Bằng chứng phải làm nền tảng cho mọi lập luận.',syn:['support','buttress','strengthen','reinforce'],ielts:'"Underpin an argument" — academic writing.',col:['underpin the argument','underpin the theory','values that underpin']},
{w:'corroborate',p:'/kəˈrɒbəreɪt/',t:'v',band:'8.0',topic:'academic',skill:'writing',vi:'chứng thực, xác nhận',ex:'The evidence corroborates the theory.',exvi:'Bằng chứng chứng thực lý thuyết.',syn:['confirm','verify','validate','substantiate'],ielts:'Band 8 academic verb.',col:['corroborate findings','corroborate evidence','corroborate a claim']},
{w:'nuance',p:'/ˈnjuːɑːns/',t:'n',band:'7.5',topic:'academic',skill:'writing',vi:'sắc thái, chi tiết nhỏ',ex:'The essay lacks nuance in its argument.',exvi:'Bài luận thiếu sắc thái trong lập luận.',syn:['subtlety','shade','distinction','refinement'],ielts:'"A nuanced argument" — Band 7.5+.',col:['subtle nuance','nuanced argument','nuanced approach','nuanced understanding']},
];
