var IELTS1_EXTRA=[
// ENVIRONMENT (thêm)
{w:'ecosystem',p:'/ˈiːkoʊˌsɪstəm/',t:'n',band:'6.5',topic:'environment',skill:'writing',vi:'hệ sinh thái',ex:'Human activities are disrupting natural ecosystems.',exvi:'Hoạt động con người đang phá vỡ hệ sinh thái tự nhiên.',syn:['habitat','biosphere','environment'],ielts:'IELTS Environment topic essential.',col:['marine ecosystem','fragile ecosystem','ecosystem collapse']},
{w:'emission',p:'/ɪˈmɪʃən/',t:'n',band:'6.5',topic:'environment',skill:'writing',vi:'khí thải, sự phát thải',ex:'Countries must reduce carbon emissions.',exvi:'Các quốc gia phải giảm khí thải carbon.',syn:['discharge','output','pollution'],ielts:'"Carbon emissions" — must-know collocation.',col:['carbon emission','greenhouse gas emission','reduce emissions','zero emission']},
{w:'contaminate',p:'/kənˈtæmɪneɪt/',t:'v',band:'7.0',topic:'environment',skill:'writing',vi:'làm ô nhiễm, nhiễm bẩn',ex:'Industrial waste has contaminated the river.',exvi:'Chất thải công nghiệp đã làm ô nhiễm con sông.',syn:['pollute','taint','corrupt','poison'],ielts:'"Contaminate" trang trọng hơn "pollute".',col:['contaminated water','food contamination','soil contamination']},
{w:'conservation',p:'/ˌkɒnsərˈveɪʃən/',t:'n',band:'6.5',topic:'environment',skill:'writing',vi:'bảo tồn',ex:'Wildlife conservation is a global priority.',exvi:'Bảo tồn động vật hoang dã là ưu tiên toàn cầu.',syn:['preservation','protection','safeguarding'],ielts:'IELTS: "conservation efforts/programs".',col:['wildlife conservation','energy conservation','conservation area']},
{w:'drought',p:'/draʊt/',t:'n',band:'6.5',topic:'environment',skill:'reading',vi:'hạn hán',ex:'The region is experiencing a severe drought.',exvi:'Khu vực đang trải qua hạn hán nghiêm trọng.',syn:['dry spell','water shortage','arid period'],ielts:'IELTS Climate topic. "Severe drought".',col:['severe drought','prolonged drought','drought-resistant']},

// EDUCATION (thêm)
{w:'curriculum',p:'/kəˈrɪkjʊləm/',t:'n',band:'6.5',topic:'education',skill:'writing',vi:'chương trình giảng dạy',ex:'The school revised its curriculum.',exvi:'Trường đã sửa đổi chương trình giảng dạy.',syn:['syllabus','program','course of study'],ielts:'IELTS Education: "national curriculum".',col:['school curriculum','national curriculum','curriculum reform']},
{w:'literacy',p:'/ˈlɪtərəsi/',t:'n',band:'6.5',topic:'education',skill:'writing',vi:'khả năng đọc viết, trình độ',ex:'Improving literacy rates is essential.',exvi:'Cải thiện tỷ lệ biết chữ là cần thiết.',syn:['education','learning','reading ability'],ielts:'"Digital literacy" — very modern IELTS topic.',col:['literacy rate','digital literacy','financial literacy','adult literacy']},
{w:'tuition',p:'/tjuˈɪʃən/',t:'n',band:'6.5',topic:'education',skill:'speaking',vi:'học phí; sự dạy kèm',ex:'University tuition fees keep rising.',exvi:'Học phí đại học liên tục tăng.',syn:['fees','teaching','instruction','coaching'],ielts:'IELTS Speaking/Writing: "tuition fees".',col:['tuition fees','private tuition','tuition-free','tuition increase']},
{w:'scholarship',p:'/ˈskɒlərʃɪp/',t:'n',band:'6.0',topic:'education',skill:'speaking',vi:'học bổng',ex:'She won a full scholarship to Oxford.',exvi:'Cô ấy giành được học bổng toàn phần đến Oxford.',syn:['grant','fellowship','bursary','award'],ielts:'Common in IELTS Speaking Part 2/3.',col:['full scholarship','academic scholarship','scholarship program']},
{w:'dropout',p:'/ˈdrɒpaʊt/',t:'n',band:'7.0',topic:'education',skill:'writing',vi:'người bỏ học',ex:'The dropout rate is alarmingly high.',exvi:'Tỷ lệ bỏ học cao đáng báo động.',syn:['quitter','leaver','non-completer'],ielts:'IELTS Writing: "school dropout rate".',col:['dropout rate','high school dropout','college dropout']},

// HEALTH
{w:'obesity',p:'/oʊˈbiːsəti/',t:'n',band:'6.5',topic:'health',skill:'writing',vi:'béo phì',ex:'Childhood obesity is a growing concern.',exvi:'Béo phì ở trẻ em là mối lo ngày càng tăng.',syn:['overweight','corpulence','fatness'],ielts:'Core IELTS health topic vocabulary.',col:['childhood obesity','obesity epidemic','combat obesity','obesity rate']},
{w:'sedentary',p:'/ˈsedəntəri/',t:'adj',band:'7.0',topic:'health',skill:'writing',vi:'ít vận động, ngồi nhiều',ex:'A sedentary lifestyle leads to health problems.',exvi:'Lối sống ít vận động dẫn đến vấn đề sức khỏe.',syn:['inactive','immobile','desk-bound','static'],ielts:'"Sedentary lifestyle" — Band 7 collocation.',col:['sedentary lifestyle','sedentary job','sedentary behavior']},
{w:'well-being',p:'/ˌwelˈbiːɪŋ/',t:'n',band:'6.5',topic:'health',skill:'writing',vi:'sức khỏe tổng thể, hạnh phúc',ex:'Exercise improves mental well-being.',exvi:'Tập thể dục cải thiện sức khỏe tinh thần.',syn:['welfare','health','happiness','wellness'],ielts:'Very common in IELTS essays about health/happiness.',col:['mental well-being','physical well-being','emotional well-being']},
{w:'pandemic',p:'/pænˈdemɪk/',t:'n/adj',band:'7.0',topic:'health',skill:'reading',vi:'đại dịch',ex:'The pandemic changed how we work.',exvi:'Đại dịch đã thay đổi cách chúng ta làm việc.',syn:['epidemic','outbreak','plague','crisis'],ielts:'Post-COVID IELTS topic. Very relevant.',col:['global pandemic','pandemic response','pandemic era']},
{w:'rehabilitation',p:'/ˌriːhəˌbɪlɪˈteɪʃən/',t:'n',band:'7.5',topic:'health',skill:'writing',vi:'phục hồi chức năng',ex:'The rehabilitation program helped many patients.',exvi:'Chương trình phục hồi đã giúp nhiều bệnh nhân.',syn:['recovery','restoration','therapy'],ielts:'IELTS Health/Crime topics.',col:['rehabilitation center','drug rehabilitation','physical rehabilitation']},

// TECHNOLOGY
{w:'automation',p:'/ˌɔːtəˈmeɪʃən/',t:'n',band:'7.0',topic:'technology',skill:'writing',vi:'tự động hóa',ex:'Automation is replacing manual jobs.',exvi:'Tự động hóa đang thay thế công việc thủ công.',syn:['mechanization','robotics','digitization'],ielts:'IELTS Technology/Employment topic.',col:['industrial automation','automation technology','job automation']},
{w:'artificial intelligence',p:'/ˌɑːrtɪˈfɪʃəl ɪnˈtelɪdʒəns/',t:'n',band:'7.0',topic:'technology',skill:'writing',vi:'trí tuệ nhân tạo',ex:'Artificial intelligence is transforming industries.',exvi:'Trí tuệ nhân tạo đang chuyển đổi các ngành công nghiệp.',syn:['AI','machine learning','deep learning'],ielts:'Hot IELTS topic. "AI" acceptable shorthand.',col:['artificial intelligence system','AI-powered','AI revolution']},
{w:'surveillance',p:'/sɜːrˈveɪləns/',t:'n',band:'7.5',topic:'technology',skill:'writing',vi:'giám sát',ex:'CCTV surveillance raises privacy concerns.',exvi:'Giám sát camera gây lo ngại về quyền riêng tư.',syn:['monitoring','observation','tracking','watching'],ielts:'IELTS: privacy vs security debate.',col:['surveillance camera','mass surveillance','government surveillance']},
{w:'cybersecurity',p:'/ˌsaɪbərsɪˈkjʊrəti/',t:'n',band:'7.0',topic:'technology',skill:'reading',vi:'an ninh mạng',ex:'Cybersecurity threats are increasing rapidly.',exvi:'Các mối đe dọa an ninh mạng đang tăng nhanh.',syn:['online security','digital security','information security'],ielts:'Modern IELTS reading topic.',col:['cybersecurity threat','cybersecurity expert','cybersecurity breach']},
{w:'obsolete',p:'/ˌɒbsəˈliːt/',t:'adj',band:'7.0',topic:'technology',skill:'writing',vi:'lỗi thời, không còn sử dụng',ex:'Smartphones have made maps nearly obsolete.',exvi:'Điện thoại thông minh đã khiến bản đồ gần như lỗi thời.',syn:['outdated','outmoded','antiquated','defunct'],ielts:'"Become obsolete" — useful for tech essays.',col:['become obsolete','render obsolete','obsolete technology']},

// SOCIETY
{w:'inequality',p:'/ˌɪnɪˈkwɒləti/',t:'n',band:'6.5',topic:'society',skill:'writing',vi:'bất bình đẳng',ex:'Income inequality is widening globally.',exvi:'Bất bình đẳng thu nhập đang mở rộng toàn cầu.',syn:['disparity','imbalance','unfairness','gap'],ielts:'Core IELTS Society/Economy topic.',col:['income inequality','social inequality','gender inequality','wealth inequality']},
{w:'discrimination',p:'/dɪˌskrɪmɪˈneɪʃən/',t:'n',band:'6.5',topic:'society',skill:'writing',vi:'phân biệt đối xử',ex:'Racial discrimination remains a serious issue.',exvi:'Phân biệt chủng tộc vẫn là vấn đề nghiêm trọng.',syn:['prejudice','bias','bigotry','intolerance'],ielts:'IELTS Society: "discrimination against".',col:['racial discrimination','age discrimination','discrimination against']},
{w:'urbanisation',p:'/ˌɜːrbənaɪˈzeɪʃən/',t:'n',band:'6.5',topic:'society',skill:'writing',vi:'đô thị hóa',ex:'Rapid urbanisation creates housing problems.',exvi:'Đô thị hóa nhanh tạo ra vấn đề nhà ở.',syn:['urban growth','city expansion','development'],ielts:'IELTS Task 1 trend description.',col:['rapid urbanisation','urbanisation rate','urbanisation trend']},
{w:'heritage',p:'/ˈherɪtɪdʒ/',t:'n',band:'6.5',topic:'society',skill:'speaking',vi:'di sản',ex:'We must protect our cultural heritage.',exvi:'Chúng ta phải bảo vệ di sản văn hóa.',syn:['legacy','tradition','inheritance','culture'],ielts:'IELTS Speaking Part 2: describe a heritage site.',col:['cultural heritage','world heritage','heritage site','heritage preservation']},
{w:'globalisation',p:'/ˌɡloʊbəlaɪˈzeɪʃən/',t:'n',band:'6.5',topic:'society',skill:'writing',vi:'toàn cầu hóa',ex:'Globalisation has both advantages and disadvantages.',exvi:'Toàn cầu hóa có cả ưu và nhược điểm.',syn:['internationalization','global integration'],ielts:'Classic IELTS Writing topic.',col:['economic globalisation','impact of globalisation','cultural globalisation']},

// ECONOMY
{w:'inflation',p:'/ɪnˈfleɪʃən/',t:'n',band:'7.0',topic:'economy',skill:'reading',vi:'lạm phát',ex:'Inflation is eroding purchasing power.',exvi:'Lạm phát đang xói mòn sức mua.',syn:['price rise','cost increase','devaluation'],ielts:'IELTS Economy/Graph description.',col:['inflation rate','high inflation','control inflation','inflation target']},
{w:'recession',p:'/rɪˈseʃən/',t:'n',band:'7.0',topic:'economy',skill:'reading',vi:'suy thoái kinh tế',ex:'The country entered a deep recession.',exvi:'Đất nước rơi vào suy thoái sâu.',syn:['downturn','slump','depression','decline'],ielts:'IELTS Reading economy passages.',col:['economic recession','global recession','recession period']},
{w:'entrepreneur',p:'/ˌɒntrəprəˈnɜːr/',t:'n',band:'7.0',topic:'economy',skill:'speaking',vi:'doanh nhân, người khởi nghiệp',ex:'Young entrepreneurs are driving innovation.',exvi:'Các doanh nhân trẻ đang thúc đẩy đổi mới.',syn:['businessman','founder','innovator','startup owner'],ielts:'IELTS Speaking: describe an entrepreneur.',col:['serial entrepreneur','social entrepreneur','entrepreneurial spirit']},
{w:'subsidy',p:'/ˈsʌbsɪdi/',t:'n',band:'7.5',topic:'economy',skill:'writing',vi:'trợ cấp, trợ giá',ex:'Government subsidies support renewable energy.',exvi:'Trợ cấp chính phủ hỗ trợ năng lượng tái tạo.',syn:['grant','aid','funding','financial support'],ielts:'"Government subsidies" — Band 7+ vocabulary.',col:['government subsidy','agricultural subsidy','subsidize']},

// CRIME & LAW
{w:'juvenile',p:'/ˈdʒuːvənaɪl/',t:'adj/n',band:'7.0',topic:'crime',skill:'writing',vi:'vị thành niên; trẻ vị thành niên',ex:'Juvenile crime rates have increased.',exvi:'Tỷ lệ tội phạm vị thành niên đã tăng.',syn:['young','adolescent','minor','teenage'],ielts:'IELTS Crime topic: "juvenile delinquency".',col:['juvenile crime','juvenile delinquency','juvenile offender']},
{w:'rehabilitation',p:'/ˌriːəˌbɪlɪˈteɪʃən/',t:'n',band:'7.0',topic:'crime',skill:'writing',vi:'cải tạo, phục hồi',ex:'Rehabilitation is more effective than punishment.',exvi:'Cải tạo hiệu quả hơn trừng phạt.',syn:['reform','recovery','reintegration'],ielts:'IELTS Crime debate: punishment vs rehabilitation.',col:['offender rehabilitation','rehabilitation program','social rehabilitation']},
{w:'deterrent',p:'/dɪˈterənt/',t:'n/adj',band:'7.5',topic:'crime',skill:'writing',vi:'sự răn đe; có tính răn đe',ex:'Harsh sentences act as a deterrent.',exvi:'Những bản án nặng có tác dụng răn đe.',syn:['discouragement','prevention','disincentive'],ielts:'"Act as a deterrent" — Band 7.5 phrase.',col:['crime deterrent','act as a deterrent','effective deterrent','nuclear deterrent']},
{w:'incarceration',p:'/ɪnˌkɑːrsəˈreɪʃən/',t:'n',band:'8.0',topic:'crime',skill:'writing',vi:'bỏ tù, giam giữ',ex:'Mass incarceration is a controversial policy.',exvi:'Giam giữ hàng loạt là chính sách gây tranh cãi.',syn:['imprisonment','detention','confinement','jailing'],ielts:'Band 8: formal alternative to "prison/jail".',col:['mass incarceration','rate of incarceration','incarceration policy']},

// MEDIA & COMMUNICATION
{w:'censorship',p:'/ˈsensərʃɪp/',t:'n',band:'7.0',topic:'media',skill:'writing',vi:'kiểm duyệt',ex:'Internet censorship limits freedom of expression.',exvi:'Kiểm duyệt internet hạn chế tự do ngôn luận.',syn:['suppression','restriction','control','ban'],ielts:'IELTS: media freedom vs censorship.',col:['internet censorship','government censorship','self-censorship']},
{w:'misinformation',p:'/ˌmɪsɪnfərˈmeɪʃən/',t:'n',band:'7.0',topic:'media',skill:'reading',vi:'thông tin sai lệch',ex:'Social media spreads misinformation rapidly.',exvi:'Mạng xã hội lan truyền thông tin sai lệch nhanh chóng.',syn:['fake news','disinformation','falsehood','propaganda'],ielts:'Hot IELTS topic post-2020.',col:['spread misinformation','combat misinformation','online misinformation']},
{w:'accountability',p:'/əˌkaʊntəˈbɪləti/',t:'n',band:'7.5',topic:'media',skill:'writing',vi:'trách nhiệm giải trình',ex:'There must be greater accountability in government.',exvi:'Cần có trách nhiệm giải trình cao hơn trong chính phủ.',syn:['responsibility','answerability','liability'],ielts:'"Hold accountable" — Band 7.5 phrase.',col:['public accountability','hold accountable','lack of accountability']},

// ACADEMIC WRITING SKILLS
{w:'albeit',p:'/ɔːlˈbiːɪt/',t:'conj',band:'7.5',topic:'academic',skill:'writing',vi:'mặc dù, dù rằng',ex:'He accepted the offer, albeit reluctantly.',exvi:'Anh ấy chấp nhận đề nghị, dù miễn cưỡng.',syn:['although','though','even though','despite'],ielts:'Band 7.5 linking word. Shows sophistication.',col:['albeit slowly','albeit briefly','albeit reluctantly']},
{w:'notwithstanding',p:'/ˌnɒtwɪðˈstændɪŋ/',t:'prep/adv',band:'8.0',topic:'academic',skill:'writing',vi:'mặc dù, bất chấp',ex:'Notwithstanding the difficulties, they succeeded.',exvi:'Bất chấp khó khăn, họ đã thành công.',syn:['despite','in spite of','regardless of','nevertheless'],ielts:'Band 8 formal linker. Use sparingly.',col:['notwithstanding the fact','notwithstanding this']},
{w:'underpin',p:'/ˌʌndərˈpɪn/',t:'v',band:'7.5',topic:'academic',skill:'writing',vi:'làm nền tảng, hỗ trợ',ex:'Evidence must underpin any argument.',exvi:'Bằng chứng phải làm nền tảng cho mọi lập luận.',syn:['support','buttress','strengthen','reinforce'],ielts:'"Underpin an argument" — academic writing verb.',col:['underpin the argument','underpin the theory','values that underpin']},
];
